/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuGioiThieu.DangNhap;

import com.wms.controller.TrangChuGioiThieu.DangNhapController;

import javax.swing.JOptionPane;
import com.wms.service.TrangChuGioiThieu.NguoiDungService;
import com.wms.view.TrangChuGioiThieu.DangKy.DangKyForm;
import com.wms.model.TrangChuQuanLy.QuanLyNguoiDung.NguoiDungDTO;

/**
 *
 * @author Thinkapd T14s
 */
public class DangNhapForm extends javax.swing.JPanel {

    /**
     * Creates new form DangNhapForm
     */
    public DangNhapForm() {
        initComponents();
        setupListeners();
    }

    private void setupListeners() {
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseClicked(evt);
            }
        });
        btnShowConfirmPass.addActionListener(e -> toggleShowPassword(txtPassword, btnShowConfirmPass));

        java.awt.event.KeyAdapter enterKeyAdapter = new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent e) {
                if (e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    btnLogin.doClick();
                }
            }
        };
        txtUsername.addKeyListener(enterKeyAdapter);
        txtPassword.addKeyListener(enterKeyAdapter);
    }

    private void toggleShowPassword(javax.swing.JPasswordField field, javax.swing.JToggleButton btn) {
        if (btn.isSelected()) {
            field.setEchoChar((char) 0);
        } else {
            field.setEchoChar('•');
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoginTitle = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblForgotPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblNoAccount = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnShowConfirmPass = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(420, 550));
        setLayout(null);

        lblLoginTitle.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(35, 30, 48));
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("Spring xin chào");
        add(lblLoginTitle);
        lblLoginTitle.setBounds(0, 50, 420, 50);

        lblSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(136, 136, 136));
        lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle.setText("Đăng nhập để vào hệ thống");
        add(lblSubTitle);
        lblSubTitle.setBounds(0, 100, 420, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(35, 30, 48));
        jLabel2.setText("Tên tài khoản (Email hoặc SĐT)");
        add(jLabel2);
        jLabel2.setBounds(40, 160, 340, 20);

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)),
                javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15)));
        add(txtUsername);
        txtUsername.setBounds(40, 185, 340, 45);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(35, 30, 48));
        jLabel3.setText("Mật khẩu");
        add(jLabel3);
        jLabel3.setBounds(40, 250, 340, 20);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)),
                javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15)));
        add(txtPassword);
        txtPassword.setBounds(40, 275, 280, 45);

        lblForgotPassword.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(235, 94, 141));
        lblForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblForgotPassword.setText("Quên mật khẩu?");
        lblForgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lblForgotPassword);
        lblForgotPassword.setBounds(240, 325, 140, 25);

        btnLogin.setBackground(new java.awt.Color(235, 94, 141));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Đăng nhập");
        btnLogin.setBorderPainted(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setFocusPainted(false);
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        add(btnLogin);
        btnLogin.setBounds(40, 370, 340, 50);

        lblNoAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNoAccount.setForeground(new java.awt.Color(136, 136, 136));
        lblNoAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNoAccount.setText("Chưa có tài khoản?");
        add(lblNoAccount);
        lblNoAccount.setBounds(80, 440, 130, 35);

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(235, 94, 141));
        btnRegister.setText("Đăng ký ngay");
        btnRegister.setBorderPainted(false);
        btnRegister.setContentAreaFilled(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegister.setMargin(new java.awt.Insets(2, 0, 2, 14));
        btnRegister.addActionListener(this::btnRegisterActionPerformed);
        add(btnRegister);
        btnRegister.setBounds(215, 440, 160, 35);

        btnShowConfirmPass.setText("👁");
        btnShowConfirmPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnShowConfirmPass);
        btnShowConfirmPass.setBounds(335, 275, 45, 45);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
        String username = txtUsername.getText().trim();
        String password = new String(txtPassword.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tên đăng nhập và mật khẩu!");
            return;
        }

        setDangNhapDangXuLy(true);
        long start = System.currentTimeMillis();

        new javax.swing.SwingWorker<NguoiDungService.ketQuaDangNhap, Void>() {
            @Override
            protected NguoiDungService.ketQuaDangNhap doInBackground() {
                DangNhapController controller = new DangNhapController();
                return controller.dangNhap(username, password);
            }

            @Override
            protected void done() {
                NguoiDungService.ketQuaDangNhap result;
                try {
                    result = get();
                } catch (Exception ex) {
                    setDangNhapDangXuLy(false);
                    JOptionPane.showMessageDialog(DangNhapForm.this,
                            "Lỗi đăng nhập: " + ex.getMessage(),
                            "Lỗi hệ thống",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }

                System.out.println("[Login] xu ly dang nhap mat " + (System.currentTimeMillis() - start) + " ms");
                xuLyKetQuaDangNhap(result);
            }
        }.execute();
    }

    private void xuLyKetQuaDangNhap(NguoiDungService.ketQuaDangNhap result) {
        switch (result) {
            case THANH_CONG:
                NguoiDungDTO user = DangNhapController.getCurrentUser();
                if (user == null) {
                    setDangNhapDangXuLy(false);
                    JOptionPane.showMessageDialog(this, "Không đọc được thông tin người dùng sau đăng nhập.",
                            "Lỗi đăng nhập", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                boolean laNhanVien = laNhanVien(user);

                if (laNhanVien) {
                    new com.wms.view.TrangChuQuanLy.TrangChuQuanLyForm().setVisible(true);
                } else {
                    new com.wms.view.TrangChuHoiVien.TrangChuHoiVienForm().setVisible(true);
                }

                java.awt.Window currentWin = javax.swing.SwingUtilities.getWindowAncestor(this);
                if (currentWin != null) {
                    currentWin.dispose();
                }
                break;
            case SAI_MAT_KHAU:
                setDangNhapDangXuLy(false);
                JOptionPane.showMessageDialog(this, "Sai mật khẩu!", "Lỗi đăng nhập", JOptionPane.ERROR_MESSAGE);
                break;
            case KHONG_THAY_TAI_KHOAN:
                setDangNhapDangXuLy(false);
                JOptionPane.showMessageDialog(this, "Tài khoản không tồn tại!", "Lỗi đăng nhập",
                        JOptionPane.ERROR_MESSAGE);
                break;
            case TAI_KHOAN_KHONG_HOAT_DONG:
                setDangNhapDangXuLy(false);
                JOptionPane.showMessageDialog(this, "Tài khoản đang bị khóa!", "Lỗi đăng nhập",
                        JOptionPane.WARNING_MESSAGE);
                break;
            case LOI_CSDL:
                setDangNhapDangXuLy(false);
                JOptionPane.showMessageDialog(this, "Lỗi kết nối Cơ sở dữ liệu!", "Lỗi hệ thống",
                        JOptionPane.ERROR_MESSAGE);
                break;
        }
    }

    private boolean laNhanVien(NguoiDungDTO user) {
        boolean laNhanVien = (user.getMaNV() != null && !user.getMaNV().trim().isEmpty());
        if (!laNhanVien && user.getVaiTro() != null) {
            for (String vt : user.getVaiTro()) {
                if (vt != null && !vt.equalsIgnoreCase(com.wms.config.AppConstants.ROLE_CUSTOMER_NAME)
                        && !vt.equalsIgnoreCase(com.wms.config.AppConstants.ROLE_CUSTOMER_CODE)) {
                    return true;
                }
            }
        }
        return laNhanVien;
    }

    private void setDangNhapDangXuLy(boolean dangXuLy) {
        btnLogin.setEnabled(!dangXuLy);
        btnRegister.setEnabled(!dangXuLy);
        txtUsername.setEnabled(!dangXuLy);
        txtPassword.setEnabled(!dangXuLy);
        btnShowConfirmPass.setEnabled(!dangXuLy);
        btnLogin.setText(dangXuLy ? "Đang đăng nhập..." : "Đăng nhập");
    }

    private void lblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof com.wms.view.TrangChuGioiThieu.TrangGioiThieuForm) {
            ((com.wms.view.TrangChuGioiThieu.TrangGioiThieuForm) win).showForgotPasswordForm();
        }
    }

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (win instanceof com.wms.view.TrangChuGioiThieu.TrangGioiThieuForm) {
            ((com.wms.view.TrangChuGioiThieu.TrangGioiThieuForm) win).showRegisterForm();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: Không tìm thấy TrangGioiThieuForm gốc!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JToggleButton btnShowConfirmPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblNoAccount;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
