/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuHoiVien.UuDaiCuaToi;

/**
 *
 * @author Thinkapd T14s
 */
public class UuDaiCuaToiForm extends javax.swing.JPanel {

    /**
     * Creates new form UuDaiCuaToiForm
     */
    public UuDaiCuaToiForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnTierCard = new javax.swing.JPanel();
        lblTierHeader = new javax.swing.JLabel();
        lblTierName = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblMinSpend = new javax.swing.JLabel();
        pnLeftCard = new javax.swing.JPanel();
        lblAddVoucher = new javax.swing.JLabel();
        txtVoucherCode = new javax.swing.JTextField();
        btnApplyVoucher = new javax.swing.JButton();
        pnLine = new javax.swing.JPanel();
        lblStatTitle = new javax.swing.JLabel();
        lblStat1 = new javax.swing.JLabel();
        lblStat2 = new javax.swing.JLabel();
        pnRightCard = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        scrollTable = new javax.swing.JScrollPane();
        tblUuDai = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(245, 246, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblTitle.setText("Ưu đãi & Đặc quyền của tôi");
        pnMain.add(lblTitle);
        lblTitle.setBounds(30, 20, 400, 32);

        pnTierCard.setBackground(new java.awt.Color(255, 255, 255));
        pnTierCard.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(235, 94, 141)));
        pnTierCard.setLayout(null);

        lblTierHeader.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTierHeader.setForeground(new java.awt.Color(136, 136, 136));
        lblTierHeader.setText("ĐẶC QUYỀN HẠNG THÀNH VIÊN");
        pnTierCard.add(lblTierHeader);
        lblTierHeader.setBounds(30, 15, 300, 20);

        lblTierName.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTierName.setForeground(new java.awt.Color(235, 94, 141));
        lblTierName.setText("VIP Kim Cương");
        pnTierCard.add(lblTierName);
        lblTierName.setBounds(30, 40, 300, 38);

        lblDiscount.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(48, 30, 35));
        lblDiscount.setText("✔ Giảm trực tiếp 15% trên tổng hóa đơn dịch vụ");
        pnTierCard.add(lblDiscount);
        lblDiscount.setBounds(400, 40, 550, 22);

        lblMinSpend.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMinSpend.setForeground(new java.awt.Color(68, 68, 68));
        lblMinSpend.setText("✔ Chi tiêu tối thiểu để duy trì: 10,000,000 VNĐ");
        pnTierCard.add(lblMinSpend);
        lblMinSpend.setBounds(400, 70, 550, 20);

        pnMain.add(pnTierCard);
        pnTierCard.setBounds(30, 70, 990, 130);

        pnLeftCard.setBackground(new java.awt.Color(255, 255, 255));
        pnLeftCard.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(35, 30, 48)));
        pnLeftCard.setLayout(null);

        lblAddVoucher.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblAddVoucher.setForeground(new java.awt.Color(48, 30, 35));
        lblAddVoucher.setText("LƯU MÃ KHUYẾN MÃI");
        pnLeftCard.add(lblAddVoucher);
        lblAddVoucher.setBounds(20, 20, 260, 30);

        txtVoucherCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtVoucherCode.setForeground(new java.awt.Color(235, 94, 141));
        txtVoucherCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVoucherCode.setToolTipText("Nhập mã tại đây...");
        pnLeftCard.add(txtVoucherCode);
        txtVoucherCode.setBounds(20, 60, 260, 40);

        btnApplyVoucher.setBackground(new java.awt.Color(235, 94, 141));
        btnApplyVoucher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApplyVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btnApplyVoucher.setText("Lưu mã vào ví");
        btnApplyVoucher.addActionListener(this::btnApplyVoucherActionPerformed);
        pnLeftCard.add(btnApplyVoucher);
        btnApplyVoucher.setBounds(20, 110, 260, 40);

        pnLine.setBackground(new java.awt.Color(224, 224, 224));
        pnLeftCard.add(pnLine);
        pnLine.setBounds(20, 180, 260, 1);

        lblStatTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblStatTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblStatTitle.setText("THỐNG KÊ ƯU ĐÃI");
        pnLeftCard.add(lblStatTitle);
        lblStatTitle.setBounds(20, 200, 260, 30);

        lblStat1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStat1.setForeground(new java.awt.Color(68, 68, 68));
        lblStat1.setText("• Số mã voucher khả dụng: 3");
        pnLeftCard.add(lblStat1);
        lblStat1.setBounds(20, 240, 260, 30);

        lblStat2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStat2.setForeground(new java.awt.Color(255, 51, 51));
        lblStat2.setText("• Sắp hết hạn (Trong 3 ngày): 1");
        pnLeftCard.add(lblStat2);
        lblStat2.setBounds(20, 280, 260, 30);

        pnMain.add(pnLeftCard);
        pnLeftCard.setBounds(30, 220, 300, 380);

        pnRightCard.setBackground(new java.awt.Color(255, 255, 255));
        pnRightCard.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(35, 30, 48)));
        pnRightCard.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("VOUCHER TRONG VÍ CỦA BẠN");
        pnRightCard.add(lblListTitle);
        lblListTitle.setBounds(30, 20, 600, 30);

        tblUuDai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Ưu Đãi", "Tên chương trình", "Mức giảm", "Hạn sử dụng", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUuDai.setRowHeight(35);
        tblUuDai.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblUuDai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUuDaiMouseClicked(evt);
            }
        });
        scrollTable.setViewportView(tblUuDai);

        pnRightCard.add(scrollTable);
        scrollTable.setBounds(30, 70, 610, 280);

        pnMain.add(pnRightCard);
        pnRightCard.setBounds(350, 220, 670, 380);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyVoucherActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void tblUuDaiMouseClicked(java.awt.event.MouseEvent evt) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyVoucher;
    private javax.swing.JLabel lblAddVoucher;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMinSpend;
    private javax.swing.JLabel lblStat1;
    private javax.swing.JLabel lblStat2;
    private javax.swing.JLabel lblStatTitle;
    private javax.swing.JLabel lblTierHeader;
    private javax.swing.JLabel lblTierName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnLeftCard;
    private javax.swing.JPanel pnLine;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRightCard;
    private javax.swing.JPanel pnTierCard;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblUuDai;
    private javax.swing.JTextField txtVoucherCode;
    // End of variables declaration//GEN-END:variables
}
