CREATE OR REPLACE TRIGGER TRG_HuyHieuLucVeCheckIn
AFTER INSERT ON PHIENLAMVIEC
FOR EACH ROW
WHEN (NEW.MaDatCho IS NOT NULL)
BEGIN
    UPDATE DATCHO
    SET TrangThaiDatTruoc = 'Đã sử dụng'
    WHERE MaDatCho = :NEW.MaDatCho;
END;
/

