package com.wms.view.TrangChuQuanLy.QuanLyChiNhanh;

import com.wms.controller.TrangChuQuanLy.QuanLyKhongGian.KhongGianController;
import com.wms.model.TrangChuQuanLy.QuanLyKhongGian.KhongGianDTO;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

public class QuanLySoDoKhongGianForm extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(QuanLySoDoKhongGianForm.class.getName());
    private final KhongGianController controller = new KhongGianController();
    private String maCN;
    private List<KhongGianDTO> dsKG;
    private Map<String, KhongGianDTO> mapKG = new HashMap<>(); // lookup nhanh theo MaKG
    private javax.swing.JPanel panelSoDo;
    
    private final Color mauHongChinh = Color.decode("#EB5E8D");
    private final Color mauTrong_Nen = Color.decode("#FFF0F5");
    private final Color mauTrong_Vien = Color.decode("#E0E0E0");
    private final Color mauDaDat_Nen = Color.decode("#FFF3E0");
    private final Color mauDaDat_Vien = Color.decode("#FFB74D");
    private final Color mauDangDung_Nen = Color.decode("#E8F5E9");
    private final Color mauDangDung_Vien = Color.decode("#66BB6A");
    private final Color mauBaoTri_Nen = Color.decode("#F5F5F5");
    private final Color mauBaoTri_Vien = Color.decode("#9E9E9E");
    private final Color mauLeTan = Color.decode("#34495E");

    private final int MAX_COLS = 12;
    private final int MAX_ROWS = 8;
    private final int DON_VI = 50;

    public QuanLySoDoKhongGianForm(java.awt.Frame parent, boolean modal, String maCN, String tenCN) {
        super(parent, modal);
        this.maCN = maCN;
        initComponents();
        this.setContentPane(pnMain);
        if (tenCN != null) lblHeaderTitle.setText("SƠ ĐỒ KHÔNG GIAN - " + tenCN.toUpperCase());
        initCustomUI();
        taiDanhSach();
        this.pack();
        this.setLocationRelativeTo(parent);
    }

    public QuanLySoDoKhongGianForm(java.awt.Frame parent, boolean modal) {
        this(parent, modal, "CN001", "Chi nhánh mặc định");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        scrollKhongGian = new javax.swing.JScrollPane();
        tblKhongGian = new javax.swing.JTable();
        lblToaDoX = new javax.swing.JLabel();
        txtToaDoX = new javax.swing.JTextField();
        lblToaDoY = new javax.swing.JLabel();
        txtToaDoY = new javax.swing.JTextField();
        lblChieuRong = new javax.swing.JLabel();
        txtChieuRong = new javax.swing.JTextField();
        lblChieuDai = new javax.swing.JLabel();
        txtChieuDai = new javax.swing.JTextField();
        btnCapNhatToaDo = new javax.swing.JButton();
        btnLuuCSDL = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        scrollSoDo = new javax.swing.JScrollPane();
        pnBaoNgoai = new javax.swing.JPanel();
        pnChuThich = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý Sơ đồ Không Gian");
        setModal(true);
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 650));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(35, 30, 48));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("CẦP NHẬT TỌA ĐỘ SƠ ĐỒ KHÔNG GIAN");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 50);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 50);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH KHÔNG GIAN");
        pnLeft.add(lblListTitle);
        lblListTitle.setBounds(15, 15, 250, 30);

        tblKhongGian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KG", "Tên KG", "X", "Y", "Rộng", "Dài"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhongGian.setRowHeight(25);
        tblKhongGian.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblKhongGian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhongGianMouseClicked(evt);
            }
        });
        scrollKhongGian.setViewportView(tblKhongGian);

        pnLeft.add(scrollKhongGian);
        scrollKhongGian.setBounds(15, 50, 320, 230);

        lblToaDoX.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblToaDoX.setForeground(new java.awt.Color(35, 30, 48));
        lblToaDoX.setText("Tỏa độ X:");
        pnLeft.add(lblToaDoX);
        lblToaDoX.setBounds(15, 290, 150, 18);

        txtToaDoX.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtToaDoX);
        txtToaDoX.setBounds(15, 310, 150, 30);

        lblToaDoY.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblToaDoY.setForeground(new java.awt.Color(35, 30, 48));
        lblToaDoY.setText("Tỏa độ Y:");
        pnLeft.add(lblToaDoY);
        lblToaDoY.setBounds(185, 290, 150, 18);

        txtToaDoY.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtToaDoY);
        txtToaDoY.setBounds(185, 310, 150, 30);

        lblChieuRong.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChieuRong.setForeground(new java.awt.Color(35, 30, 48));
        lblChieuRong.setText("Rộng (Ngang):");
        pnLeft.add(lblChieuRong);
        lblChieuRong.setBounds(15, 350, 150, 18);

        txtChieuRong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtChieuRong);
        txtChieuRong.setBounds(15, 370, 150, 30);

        lblChieuDai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChieuDai.setForeground(new java.awt.Color(35, 30, 48));
        lblChieuDai.setText("Dài (Dọc):");
        pnLeft.add(lblChieuDai);
        lblChieuDai.setBounds(185, 350, 150, 18);

        txtChieuDai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtChieuDai);
        txtChieuDai.setBounds(185, 370, 150, 30);

        btnCapNhatToaDo.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhatToaDo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhatToaDo.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatToaDo.setText("Cập nhật trên Sơ đồ");
        btnCapNhatToaDo.addActionListener(e -> btnCapNhatToaDoActionPerformed());
        pnLeft.add(btnCapNhatToaDo);
        btnCapNhatToaDo.setBounds(15, 420, 320, 35);

        btnLuuCSDL.setBackground(new java.awt.Color(220, 53, 69));
        btnLuuCSDL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuCSDL.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuCSDL.setText("Lưu thay đổi CSDL");
        btnLuuCSDL.addActionListener(e -> btnLuuCSDLActionPerformed());
        pnLeft.add(btnLuuCSDL);
        btnLuuCSDL.setBounds(15, 465, 320, 35);

        pnMain.add(pnLeft);
        pnLeft.setBounds(20, 70, 350, 530);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("XEM TRưỚC SƠ ĐỒ TRỰC QUAN");
        pnRight.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 300, 30);

        scrollSoDo.setBorder(null);

        pnBaoNgoai.setBackground(new java.awt.Color(254, 248, 250));
        scrollSoDo.setViewportView(pnBaoNgoai);

        pnRight.add(scrollSoDo);
        scrollSoDo.setBounds(20, 50, 610, 400);

        pnChuThich.setBackground(new java.awt.Color(255, 255, 255));
        pnChuThich.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        pnRight.add(pnChuThich);
        pnChuThich.setBounds(20, 470, 610, 50);

        pnMain.add(pnRight);
        pnRight.setBounds(380, 70, 650, 530);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initCustomUI() {
        panelSoDo = new GridPanel();
        javax.swing.JPanel canvas = new javax.swing.JPanel(new java.awt.BorderLayout());
        canvas.setOpaque(false);
        canvas.add(panelSoDo, java.awt.BorderLayout.CENTER);
        pnBaoNgoai.setLayout(new java.awt.BorderLayout());
        pnBaoNgoai.add(canvas, java.awt.BorderLayout.CENTER);

        pnChuThich.add(taoMucChuThich("Quầy lễ tân", mauLeTan, Color.BLACK));
        pnChuThich.add(taoMucChuThich("Trống", mauTrong_Nen, mauTrong_Vien));
        pnChuThich.add(taoMucChuThich("Đã đặt", mauDaDat_Nen, mauDaDat_Vien));
        pnChuThich.add(taoMucChuThich("Đang dùng", mauDangDung_Nen, mauDangDung_Vien));
        pnChuThich.add(taoMucChuThich("Bảo trì", mauBaoTri_Nen, mauBaoTri_Vien));
    }

    class GridPanel extends javax.swing.JPanel {
        public GridPanel() {
            setLayout(new java.awt.GridBagLayout());
            setBackground(Color.WHITE);
            setPreferredSize(new Dimension(MAX_COLS * DON_VI + 30, MAX_ROWS * DON_VI + 30));
        }

        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

            g2.setColor(new Color(240, 240, 240));
            g2.fillRect(0, 0, MAX_COLS * DON_VI, MAX_ROWS * DON_VI);
            g2.setColor(new Color(220, 220, 220));
            for (int i = 0; i <= MAX_COLS; i++) g2.drawLine(i * DON_VI, 0, i * DON_VI, MAX_ROWS * DON_VI);
            for (int j = 0; j <= MAX_ROWS; j++) g2.drawLine(0, j * DON_VI, MAX_COLS * DON_VI, j * DON_VI);

            g2.setColor(Color.GRAY);
            g2.setFont(new Font("Segoe UI", Font.BOLD, 10));
            for (int i = 0; i < MAX_COLS; i++) g2.drawString("X:" + i, i * DON_VI + 5, 12);
            for (int j = 0; j < MAX_ROWS; j++) g2.drawString("Y:" + j, 5, j * DON_VI + 12);

            g2.setColor(mauHongChinh);
            g2.setStroke(new java.awt.BasicStroke(2));
            g2.drawRect(0, 0, MAX_COLS * DON_VI, MAX_ROWS * DON_VI);
        }
    }

    private javax.swing.JPanel taoMucChuThich(String ten, Color nen, Color vien) {
        javax.swing.JPanel p = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        p.setOpaque(false);
        javax.swing.JLabel box = new javax.swing.JLabel();
        box.setPreferredSize(new Dimension(15, 15));
        box.setOpaque(true);
        box.setBackground(nen);
        box.setBorder(javax.swing.BorderFactory.createLineBorder(vien, 1));
        p.add(box);
        p.add(new javax.swing.JLabel(ten));
        return p;
    }

    private void taiDanhSach() {
        dsKG = controller.layTheoChiNhanh(maCN);
        mapKG.clear();
        for (KhongGianDTO dto : dsKG) mapKG.put(dto.getMaKG(), dto);

        DefaultTableModel model = (DefaultTableModel) tblKhongGian.getModel();
        model.setRowCount(0);
        for (KhongGianDTO dto : dsKG) {
            model.addRow(new Object[]{
                dto.getMaKG(), dto.getTenKG(), dto.getToaDoX(), dto.getToaDoY(),
                dto.getChieuDai(), dto.getChieuRong()
            });
        }
        veSoDo();
    }

    private void veSoDo() {
        panelSoDo.removeAll();
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(1, 1, 1, 1);
        gbc.fill = java.awt.GridBagConstraints.BOTH;

        // Cố định kích thước các cột và hàng để không bị co lại
        for (int i = 0; i < MAX_COLS; i++) {
            gbc.gridx = i;
            gbc.gridy = MAX_ROWS + 1;
            gbc.weightx = 0;
            panelSoDo.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(DON_VI, 1)), gbc);
        }
        for (int j = 0; j < MAX_ROWS; j++) {
            gbc.gridx = MAX_COLS + 1;
            gbc.gridy = j;
            gbc.weighty = 0;
            panelSoDo.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(1, DON_VI)), gbc);
        }

        // Nút Lễ tân cố định
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.gridheight = 1;
        gbc.weightx = 0;
        gbc.weighty = 0;
        javax.swing.JButton btnLeTan = new javax.swing.JButton("RECEPTION");
        btnLeTan.setPreferredSize(new java.awt.Dimension(DON_VI * 2, DON_VI));
        btnLeTan.setBackground(mauLeTan);
        btnLeTan.setForeground(java.awt.Color.WHITE);
        btnLeTan.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
        btnLeTan.setEnabled(false);
        panelSoDo.add(btnLeTan, gbc);

        // Vẽ các ô không gian
        for (com.wms.model.TrangChuQuanLy.QuanLyKhongGian.KhongGianDTO kg : dsKG) {
            gbc.gridx = kg.getToaDoX();
            gbc.gridy = kg.getToaDoY();
            gbc.gridwidth = kg.getChieuDai();
            gbc.gridheight = kg.getChieuRong();
            
            java.awt.Dimension size = new java.awt.Dimension(DON_VI * kg.getChieuDai(), DON_VI * kg.getChieuRong());
            
            javax.swing.JButton btn = new javax.swing.JButton(kg.getMaKG());
            btn.setPreferredSize(size);
            btn.setMinimumSize(size);
            btn.setToolTipText(kg.getTenKG() + " (X:" + kg.getToaDoX() + ", Y:" + kg.getToaDoY() + ")");
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 9));
            
            java.awt.Color color = mauTrong_Nen;
            if ("Đã đặt trước".equals(kg.getTrangThaiKG())) color = mauDaDat_Nen;
            else if ("Đang hoạt động".equals(kg.getTrangThaiKG())) color = mauDangDung_Nen;
            else if ("Bảo trì".equals(kg.getTrangThaiKG())) color = mauBaoTri_Nen;
            
            btn.setBackground(color);
            btn.addActionListener(e -> {
                for(int i=0; i<tblKhongGian.getRowCount(); i++) {
                    if(tblKhongGian.getValueAt(i, 0).equals(kg.getMaKG())) {
                        tblKhongGian.setRowSelectionInterval(i, i);
                        tblKhongGianMouseClicked(null);
                        break;
                    }
                }
            });
            
            panelSoDo.add(btn, gbc);
        }
        
        // Đẩy toàn bộ về góc trên bên trái
        gbc.gridx = MAX_COLS + 2;
        gbc.gridy = MAX_ROWS + 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panelSoDo.add(javax.swing.Box.createGlue(), gbc);

        panelSoDo.revalidate();
        panelSoDo.repaint();
    }

    private void tblKhongGianMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblKhongGian.getSelectedRow();
        if (row < 0) return;
        String maKG = tblKhongGian.getValueAt(row, 0).toString();
        KhongGianDTO dto = mapKG.get(maKG);
        if (dto == null) return;
        txtToaDoX.setText(String.valueOf(dto.getToaDoX()));
        txtToaDoY.setText(String.valueOf(dto.getToaDoY()));
        txtChieuRong.setText(String.valueOf(dto.getChieuDai()));
        txtChieuDai.setText(String.valueOf(dto.getChieuRong()));
    }

    private void btnCapNhatToaDoActionPerformed() {
        int row = tblKhongGian.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn một không gian trong bảng!");
            return;
        }
        try {
            String maKG = tblKhongGian.getValueAt(row, 0).toString();
            int x = Integer.parseInt(txtToaDoX.getText().trim());
            int y = Integer.parseInt(txtToaDoY.getText().trim());
            int w = Integer.parseInt(txtChieuRong.getText().trim());
            int h = Integer.parseInt(txtChieuDai.getText().trim());

            KhongGianDTO dto = mapKG.get(maKG);
            if (dto != null) {
                dto.setToaDoX(x); dto.setToaDoY(y);
                dto.setChieuDai(w); dto.setChieuRong(h);
                tblKhongGian.setValueAt(x, row, 2);
                tblKhongGian.setValueAt(y, row, 3);
                tblKhongGian.setValueAt(w, row, 4);
                tblKhongGian.setValueAt(h, row, 5);
                veSoDo();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Toạ độ và kích thước phải là số nguyên!");
        }
    }

    private void btnLuuCSDLActionPerformed() {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có muốn lưu toàn bộ thay đổi toạ độ vào CSDL không?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            String loi = controller.luuToaDo(dsKG);
            if (loi == null) {
                JOptionPane.showMessageDialog(this, "Lưu thành công!");
                taiDanhSach();
            } else {
                JOptionPane.showMessageDialog(this, loi, "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                QuanLySoDoKhongGianForm dialog = new QuanLySoDoKhongGianForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatToaDo;
    private javax.swing.JButton btnLuuCSDL;
    private javax.swing.JLabel lblChieuDai;
    private javax.swing.JLabel lblChieuRong;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblToaDoX;
    private javax.swing.JLabel lblToaDoY;
    private javax.swing.JPanel pnBaoNgoai;
    private javax.swing.JPanel pnChuThich;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JScrollPane scrollKhongGian;
    private javax.swing.JScrollPane scrollSoDo;
    private javax.swing.JTable tblKhongGian;
    private javax.swing.JTextField txtChieuDai;
    private javax.swing.JTextField txtChieuRong;
    private javax.swing.JTextField txtToaDoX;
    private javax.swing.JTextField txtToaDoY;
    // End of variables declaration//GEN-END:variables
}


