package com.wms.view.TrangChu.TrangChuHoiVien.DatChoKhongGian.DatCho;

import com.wms.model.ThanhToan_KhuyenMai.HoaDonDTO;
import com.wms.model.ThanhToan_KhuyenMai.PhieuGiamGiaDTO;
import javax.swing.JOptionPane;

/**
 * Màn hình Thanh Toán Trước (JPanel)
 * Chứa thông tin chi tiết hóa đơn và xử lý áp dụng mã giảm giá
 */
public class ThanhToanTruoc extends javax.swing.JPanel {

    private HoaDonDTO hoaDonHienTai;

    /**
     * Hàm khởi tạo mặc định
     */
    public ThanhToanTruoc() {
            initComponents();
        capNhatHienThiTien();
    }

    /**
     * Hàm khởi tạo nhận dữ liệu từ màn hình Chọn Không Gian
     * @param htmlThongTinDatCho Chuỗi HTML hiển thị chi tiết đặt chỗ
     * @param hoaDonDTO Đối tượng chứa thông tin hóa đơn và tổng tiền
     */
    public ThanhToanTruoc(String htmlThongTinDatCho, HoaDonDTO hoaDonDTO) {
        initComponents();
        this.hoaDonHienTai = hoaDonDTO;

        // Thiết lập hiển thị HTML cho khung chi tiết
        txtChiTietDatCho.setContentType("text/html");
        if (htmlThongTinDatCho != null && !htmlThongTinDatCho.isEmpty()) {
            txtChiTietDatCho.setText(htmlThongTinDatCho);
        }
        
        // Hiển thị tổng tiền lên ô txtTongCong
        capNhatHienThiTien();
    }
    
    private void capNhatHienThiTien() {
        if (hoaDonHienTai != null && hoaDonHienTai.getThanhTien() != null) {
            java.text.DecimalFormat formatter = new java.text.DecimalFormat("###,###,###");
            txtTongCong.setText(formatter.format(hoaDonHienTai.getThanhTien()) + " VNĐ");
        } else if (hoaDonHienTai != null && hoaDonHienTai.getTongTien() != null) {
            java.text.DecimalFormat formatter = new java.text.DecimalFormat("###,###,###");
            txtTongCong.setText(formatter.format(hoaDonHienTai.getTongTien()) + " VNĐ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChiTietDatCho = new javax.swing.JTextPane();
        lblTongCong = new javax.swing.JLabel();
        txtTongCong = new javax.swing.JTextField();
        btnMaGiamGia = new javax.swing.JButton();
        btnHoanTat = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(232, 85, 136));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("CHI TIẾT THANH TOÁN ĐẶT TRƯỚC");
        add(lblTitle);
        lblTitle.setBounds(150, 20, 500, 40);

        txtChiTietDatCho.setEditable(false);
        txtChiTietDatCho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin đặt chỗ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(199, 61, 110))); // NOI18N
        jScrollPane1.setViewportView(txtChiTietDatCho);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 80, 400, 420);

        lblTongCong.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTongCong.setText("Tổng cộng:");
        add(lblTongCong);
        lblTongCong.setBounds(470, 80, 150, 30);

        txtTongCong.setEditable(false);
        txtTongCong.setBackground(new java.awt.Color(240, 240, 240));
        txtTongCong.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        txtTongCong.setForeground(new java.awt.Color(199, 61, 110));
        txtTongCong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTongCong.setText("0 VNĐ");
        txtTongCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongCongActionPerformed(evt);
            }
        });
        add(txtTongCong);
        txtTongCong.setBounds(470, 120, 290, 40);

        btnMaGiamGia.setBackground(new java.awt.Color(255, 240, 245));
        btnMaGiamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMaGiamGia.setText("Sử dụng mã giảm giá");
        btnMaGiamGia.setToolTipText("");
        btnMaGiamGia.setBorderPainted(false);
        btnMaGiamGia.setFocusPainted(false);
        btnMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaGiamGiaActionPerformed(evt);
            }
        });
        add(btnMaGiamGia);
        btnMaGiamGia.setBounds(470, 180, 290, 40);

        btnHoanTat.setBackground(new java.awt.Color(232, 85, 136));
        btnHoanTat.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnHoanTat.setForeground(new java.awt.Color(255, 255, 255));
        btnHoanTat.setText("HOÀN TẤT THANH TOÁN");
        btnHoanTat.setBorderPainted(false);
        btnHoanTat.setFocusPainted(false);
        btnHoanTat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanTatActionPerformed(evt);
            }
        });
        add(btnHoanTat);
        btnHoanTat.setBounds(470, 510, 290, 50);

        btnQuayLai.setBackground(new java.awt.Color(178, 34, 34));
        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        btnQuayLai.setText("Quay lại");
        btnQuayLai.setBorderPainted(false);
        btnQuayLai.setFocusPainted(false);
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        add(btnQuayLai);
        btnQuayLai.setBounds(40, 520, 130, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        java.awt.Container khungChua = this.getParent(); 
        if (khungChua != null) {
            khungChua.removeAll();
            ChonKhongGian pnlChon = new ChonKhongGian();
            pnlChon.setSize(khungChua.getSize());
            khungChua.add(pnlChon);
            khungChua.revalidate(); 
            khungChua.repaint();    
        }
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaGiamGiaActionPerformed
        if (hoaDonHienTai == null || hoaDonHienTai.getTongTien() == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn để áp dụng mã!");
            return;
        }

        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (window instanceof java.awt.Frame) ? (java.awt.Frame) window : null;

        ApDungMaGiamGia dialog = new ApDungMaGiamGia(parentFrame, true, hoaDonHienTai.getTongTien());
        dialog.setVisible(true); 

        PhieuGiamGiaDTO voucher = dialog.getVoucherApDung();
        if (voucher != null) {
            hoaDonHienTai.setMaPGG(voucher.getMaPGG());
            double tienPhaiTra = hoaDonHienTai.getTongTien() - voucher.getGiaTriGiamGia();
            if (tienPhaiTra < 0) tienPhaiTra = 0;
            hoaDonHienTai.setThanhTien(tienPhaiTra);

            capNhatHienThiTien();
            btnMaGiamGia.setEnabled(false);
            btnMaGiamGia.setText("Đã áp mã: " + voucher.getMaPGG());
        }
    }//GEN-LAST:event_btnMaGiamGiaActionPerformed

    private void btnHoanTatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanTatActionPerformed
        if (hoaDonHienTai != null) {
            JOptionPane.showMessageDialog(this, "Đang xử lý thanh toán hóa đơn: " + hoaDonHienTai.getMaHoaDon());
            // Tại đây bạn sẽ gọi DAO để lưu trạng thái hóa đơn xuống DB
        }
    }//GEN-LAST:event_btnHoanTatActionPerformed

    private void txtTongCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongCongActionPerformed

    /**
     * Hàm main hỗ trợ chạy thử độc lập JPanel
     */
    public static void main(String[] args) {
        javax.swing.JFrame frame = new javax.swing.JFrame("Thanh Toán Trước Preview");
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        frame.add(new ThanhToanTruoc());
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoanTat;
    private javax.swing.JButton btnMaGiamGia;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTongCong;
    private javax.swing.JTextPane txtChiTietDatCho;
    private javax.swing.JTextField txtTongCong;
    // End of variables declaration//GEN-END:variables
}