package com.wms.view.TrangChuQuanLy.QuanLyThongTinDichVu;

import com.wms.controller.TrangChuQuanLy.QuanLyThongTinDichVu.DichVuController;
import com.wms.model.TrangChuQuanLy.QuanLyThongTinDichVu.DichVuDTO;
import com.wms.model.TrangChuQuanLy.QuanLyLoaiDichVu.LoaiDichVuDTO;
import com.wms.view.TrangChuQuanLy.QuanLyLoaiDichVu.QuanLyLoaiDichVuForm;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class QuanLyThongTinDichVuForm extends javax.swing.JPanel {

    private final DichVuController controller = new DichVuController();
    private List<LoaiDichVuDTO> dsLoai;
    private List<DichVuDTO> dsDichVu;

    public QuanLyThongTinDichVuForm() {
        initComponents();
        loadLoaiDV();
        loadData(null);
        txtMaDV.setText("");
        com.wms.util.InputFormatUtil.attachThousandsFormatter(txtDonGia);
        com.wms.util.TienIchFormQuanLy.apDung(this);
    }

    private void loadLoaiDV() {
        cbxLoaiDV.removeAllItems();
        cbxLoaiDV.addItem("-- Chọn loại DV --");
        dsLoai = controller.layDanhSachLoai();
        for (LoaiDichVuDTO l : dsLoai) {
            cbxLoaiDV.addItem(l.getTenLoaiDV());
            cbxLoaiDV.putClientProperty("maLoai_" + l.getTenLoaiDV(), l.getMaLoaiDV());
        }
    }

    private void loadData(String tuKhoa) {
        DefaultTableModel model = (DefaultTableModel) tblDichVu.getModel();
        model.setRowCount(0);
        dsDichVu = controller.layDanhSach(null, null, tuKhoa);
        for (DichVuDTO dv : dsDichVu) {
            model.addRow(new Object[]{
                dv.getMaDV(),
                dv.getTenDV(),
                getTenLoai(dv.getMaLoaiDV()),
                com.wms.util.InputFormatUtil.formatThousands(dv.getDonGia()),
                dv.getTrangThaiDV()
            });
        }
    }

    private String getTenLoai(String maLoai) {
        for (LoaiDichVuDTO l : dsLoai) {
            if (l.getMaLoaiDV().equals(maLoai)) return l.getTenLoaiDV();
        }
        return maLoai;
    }

    private String getMaLoaiDangChon() {
        String tenLoai = (String) cbxLoaiDV.getSelectedItem();
        if (tenLoai == null || tenLoai.startsWith("--")) return null;
        Object ma = cbxLoaiDV.getClientProperty("maLoai_" + tenLoai);
        return ma != null ? ma.toString() : null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblAnhDichVu = new javax.swing.JLabel();
        btnDoiAnh = new javax.swing.JButton();
        lblMaDV = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        lblTenDV = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        lblLoaiDV = new javax.swing.JLabel();
        cbxLoaiDV = new javax.swing.JComboBox<>();
        lblDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ THÔNG TIN DỊCH VỤ");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        lblAnhDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhDichVu.setText("[Ảnh dịch vụ]");
        lblAnhDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnMain.add(lblAnhDichVu);
        lblAnhDichVu.setBounds(20, 70, 140, 140);

        btnDoiAnh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoiAnh.setForeground(new java.awt.Color(235, 94, 141));
        btnDoiAnh.setText("Chọn ảnh");
        btnDoiAnh.addActionListener(this::btnDoiAnhActionPerformed);
        pnMain.add(btnDoiAnh);
        btnDoiAnh.setBounds(20, 220, 140, 30);

        lblMaDV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaDV.setForeground(new java.awt.Color(35, 30, 48));
        lblMaDV.setText("Mã Dịch vụ");
        pnMain.add(lblMaDV);
        lblMaDV.setBounds(180, 70, 100, 20);

        txtMaDV.setEditable(false);
        txtMaDV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaDV.setBackground(new java.awt.Color(240, 240, 240));
        pnMain.add(txtMaDV);
        txtMaDV.setBounds(180, 90, 210, 35);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái (*)");
        pnMain.add(lblTrangThai);
        lblTrangThai.setBounds(180, 140, 100, 18);

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Ngừng kinh doanh" }));
        pnMain.add(cbxTrangThai);
        cbxTrangThai.setBounds(180, 160, 210, 35);

        lblTenDV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenDV.setForeground(new java.awt.Color(35, 30, 48));
        lblTenDV.setText("Tên dịch vụ (*)");
        pnMain.add(lblTenDV);
        lblTenDV.setBounds(180, 280, 210, 18);

        txtTenDV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTenDV);
        txtTenDV.setBounds(180, 300, 210, 35);

        lblLoaiDV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoaiDV.setForeground(new java.awt.Color(35, 30, 48));
        lblLoaiDV.setText("Loại dịch vụ (*)");
        pnMain.add(lblLoaiDV);
        lblLoaiDV.setBounds(180, 210, 210, 18);

        cbxLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxLoaiDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn loại Dịch vụ --", "Nước uống", "Thức ăn nhẹ" }));
        cbxLoaiDV.addActionListener(this::cbxLoaiDVActionPerformed);
        pnMain.add(cbxLoaiDV);
        cbxLoaiDV.setBounds(180, 230, 210, 35);

        lblDonGia.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDonGia.setForeground(new java.awt.Color(35, 30, 48));
        lblDonGia.setText("Đơn giá (VNĐ) (*)");
        pnMain.add(lblDonGia);
        lblDonGia.setBounds(20, 280, 150, 18);

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtDonGia);
        txtDonGia.setBounds(20, 300, 150, 35);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnMain.add(btnThemMoi);
        btnThemMoi.setBounds(20, 360, 180, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnMain.add(btnCapNhat);
        btnCapNhat.setBounds(210, 360, 180, 40);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnMain.add(btnHuy);
        btnHuy.setBounds(20, 415, 370, 40);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm Tên/Mã:");
        pnMain.add(lblTimKiem);
        lblTimKiem.setBounds(420, 80, 130, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTimKiem);
        txtTimKiem.setBounds(550, 80, 350, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnMain.add(btnTimKiem);
        btnTimKiem.setBounds(920, 80, 100, 35);

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã DV", "Tên dịch vụ", "Loại dịch vụ", "Đơn giá", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichVu.setRowHeight(30);
        tblDichVu.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDichVu);

        pnMain.add(jScrollPane1);
        jScrollPane1.setBounds(420, 130, 600, 480);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiDVActionPerformed

    private void btnDoiAnhActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getAbsolutePath();
            lblAnhDichVu.setIcon(new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH)));
            lblAnhDichVu.setText("");
            lblAnhDichVu.putClientProperty("path", path);
        }
    }

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            DichVuDTO dv = getFormData();
            if (controller.themMoi(dv)) {
                JOptionPane.showMessageDialog(this, "Thêm dịch vụ thành công!");
                lamMoiForm();
                loadData(null);
            } else {
                com.wms.util.MessageUtil.showError(this, "Thêm thất bại. Vui lòng kiểm tra lại thông tin.");
            }
        } catch (Exception e) {
            com.wms.util.MessageUtil.showError(this, e.getMessage(), e);
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            DichVuDTO dv = getFormData();
            
            // Chặn ngừng kinh doanh cho dịch vụ hệ thống
            if ("DV0000".equals(dv.getMaDV()) && !"Đang hoạt động".equals(dv.getTrangThaiDV())) {
                JOptionPane.showMessageDialog(this, "Không thể ngừng kinh doanh dịch vụ hệ thống (Gia hạn giờ)!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (controller.capNhat(dv)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                loadData(null);
            } else {
                com.wms.util.MessageUtil.showError(this, "Cập nhật thất bại. Vui lòng kiểm tra lại thông tin.");
            }
        } catch (Exception e) {
            com.wms.util.MessageUtil.showError(this, e.getMessage(), e);
        }
    }

    private void btnQuanLyLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn mục 'Loại Dịch vụ' ở menu bên trái để quản lý!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        loadLoaiDV();
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        lamMoiForm();
        loadData(null);
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        loadData(txtTimKiem.getText().trim());
    }

    private void lamMoiForm() {
        txtMaDV.setText("");
        txtTenDV.setText("");
        txtDonGia.setText("");
        cbxLoaiDV.setSelectedIndex(0);
        cbxTrangThai.setSelectedIndex(0);
        lblAnhDichVu.setIcon(null);
        lblAnhDichVu.setText("[Ảnh dịch vụ]");
        lblAnhDichVu.putClientProperty("path", null);
        tblDichVu.clearSelection();
    }

    private DichVuDTO getFormData() throws Exception {
        if (txtTenDV.getText().trim().isEmpty()) {
            throw new IllegalArgumentException("Vui lòng nhập tên dịch vụ.");
        }
        if (cbxLoaiDV.getSelectedIndex() <= 0) {
            throw new IllegalArgumentException("Vui lòng chọn loại dịch vụ.");
        }
        if (txtDonGia.getText().trim().isEmpty()) {
            throw new IllegalArgumentException("Vui lòng nhập đơn giá.");
        }
        DichVuDTO dv = new DichVuDTO();
        dv.setMaDV(txtMaDV.getText());
        dv.setTenDV(txtTenDV.getText().trim());
        dv.setMaLoaiDV(getMaLoaiDangChon());
        try {
            java.math.BigDecimal donGia = com.wms.util.InputFormatUtil.getBigDecimalValue(txtDonGia);
            if (donGia == null) {
                throw new NumberFormatException();
            }
            if (donGia.signum() < 0) {
                throw new IllegalArgumentException("Đơn giá không được âm.");
            }
            dv.setDonGia(donGia.doubleValue());
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Đơn giá phải là số hợp lệ.");
        }
        dv.setTrangThaiDV((String) cbxTrangThai.getSelectedItem());
        Object pathObj = lblAnhDichVu.getClientProperty("path");
        if (pathObj != null) {
            String path = pathObj.toString();
            try {
                dv.setHinhAnh(java.nio.file.Files.readAllBytes(java.nio.file.Paths.get(path)));
            } catch (java.io.IOException e) {
                System.err.println("Lỗi đọc file ảnh: " + e.getMessage());
            }
        }
        return dv;
    }

    private void tblDichVuMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblDichVu.getSelectedRow();
        if (row < 0) return;
        DefaultTableModel model = (DefaultTableModel) tblDichVu.getModel();
        txtMaDV.setText(model.getValueAt(row, 0).toString());
        txtTenDV.setText(model.getValueAt(row, 1).toString());
        cbxLoaiDV.setSelectedItem(model.getValueAt(row, 2).toString());
        txtDonGia.setText(com.wms.util.InputFormatUtil.formatThousands(model.getValueAt(row, 3).toString()));
        cbxTrangThai.setSelectedItem(model.getValueAt(row, 4).toString());
        
        // Hiển thị ảnh
        String maDV = model.getValueAt(row, 0).toString();
        for (DichVuDTO dv : dsDichVu) {
            if (dv.getMaDV().equals(maDV)) {
                if (dv.getHinhAnh() != null) {
                    ImageIcon icon = new ImageIcon(dv.getHinhAnh());
                    Image img = icon.getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH);
                    lblAnhDichVu.setIcon(new ImageIcon(img));
                    lblAnhDichVu.setText("");
                } else {
                    lblAnhDichVu.setIcon(null);
                    lblAnhDichVu.setText("[Ảnh dịch vụ]");
                }
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDoiAnh;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxLoaiDV;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnhDichVu;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblLoaiDV;
    private javax.swing.JLabel lblMaDV;
    private javax.swing.JLabel lblTenDV;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
