/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyThongTinDichVu;

import com.wms.controller.DichVuController;

import com.wms.dao.LoaiDichVuDAO;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyLoaiDichVuForm extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyLoaiDichVuForm.class.getName());

    private final com.wms.controller.DichVuController controller;
    private javax.swing.table.DefaultTableModel tableModel;

    public QuanLyLoaiDichVuForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new com.wms.controller.DichVuController();
        tableModel = (javax.swing.table.DefaultTableModel) tblLoaiDichVu.getModel();
        loadData();
        txtMaLoaiDV.setText(generateMaLoai());
    }

    private void loadData() {
        tableModel.setRowCount(0);
        java.util.List<com.wms.model.LoaiDichVuDTO> list = controller.layDanhSachLoai();
        for (com.wms.model.LoaiDichVuDTO l : list) {
            tableModel.addRow(new Object[]{l.getMaLoaiDV(), l.getTenLoaiDV(), l.getTrangThaiLDV()});
        }
    }

    private String generateMaLoai() {
        return "LDV" + (System.currentTimeMillis() % 1000000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaLoaiDV = new javax.swing.JLabel();
        txtMaLoaiDV = new javax.swing.JTextField();
        lblTenLoaiDV = new javax.swing.JLabel();
        txtTenLoaiDV = new javax.swing.JTextField();
        lblTrangThaiLDV = new javax.swing.JLabel();
        cbxTrangThaiLDV = new javax.swing.JComboBox<>();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiDichVu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý Loại Dịch Vụ");
        setModal(true);
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(850, 550));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(35, 30, 48));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ LOẠI DỊCH VỤ");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 850, 50);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 850, 50);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("THÔNG TIN LOẠI");
        pnLeft.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 260, 30);

        lblMaLoaiDV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaLoaiDV.setForeground(new java.awt.Color(35, 30, 48));
        lblMaLoaiDV.setText("Mã loại DV (Tự động)");
        pnLeft.add(lblMaLoaiDV);
        lblMaLoaiDV.setBounds(20, 60, 260, 20);

        txtMaLoaiDV.setEditable(false);
        txtMaLoaiDV.setBackground(new java.awt.Color(240, 240, 240));
        txtMaLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtMaLoaiDV);
        txtMaLoaiDV.setBounds(20, 80, 260, 35);

        lblTenLoaiDV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenLoaiDV.setForeground(new java.awt.Color(35, 30, 48));
        lblTenLoaiDV.setText("Tên loại dịch vụ (*)");
        pnLeft.add(lblTenLoaiDV);
        lblTenLoaiDV.setBounds(20, 130, 260, 20);

        txtTenLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtTenLoaiDV);
        txtTenLoaiDV.setBounds(20, 150, 260, 35);

        lblTrangThaiLDV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThaiLDV.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThaiLDV.setText("Trạng thái (*)");
        pnLeft.add(lblTrangThaiLDV);
        lblTrangThaiLDV.setBounds(20, 200, 260, 20);

        cbxTrangThaiLDV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTrangThaiLDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Tạm ngừng" }));
        pnLeft.add(cbxTrangThaiLDV);
        cbxTrangThaiLDV.setBounds(20, 220, 260, 35);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnLeft.add(btnThemMoi);
        btnThemMoi.setBounds(20, 340, 125, 35);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnLeft.add(btnCapNhat);
        btnCapNhat.setBounds(155, 340, 125, 35);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnLeft.add(btnHuy);
        btnHuy.setBounds(20, 390, 260, 35);

        pnMain.add(pnLeft);
        pnLeft.setBounds(20, 70, 300, 450);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH LOẠI DỊCH VỤ");
        pnRight.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 260, 30);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(txtTimKiem);
        txtTimKiem.setBounds(20, 60, 350, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnRight.add(btnTimKiem);
        btnTimKiem.setBounds(380, 60, 90, 35);

        tblLoaiDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Loại", "Tên loại", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiDichVu.setRowHeight(30);
        tblLoaiDichVu.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblLoaiDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiDichVu);

        pnRight.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 450, 320);

        pnMain.add(pnRight);
        pnRight.setBounds(340, 70, 490, 450);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {
        if (txtTenLoaiDV.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập tên loại dịch vụ!");
            return;
        }
        com.wms.model.LoaiDichVuDTO l = new com.wms.model.LoaiDichVuDTO();
        l.setMaLoaiDV(txtMaLoaiDV.getText());
        l.setTenLoaiDV(txtTenLoaiDV.getText());
        l.setTrangThaiLDV(cbxTrangThaiLDV.getSelectedItem().toString());

        if (new com.wms.dao.LoaiDichVuDAO().them(l)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadData();
            btnHuyActionPerformed(null);
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        if (txtMaLoaiDV.getText().isEmpty()) return;
        com.wms.model.LoaiDichVuDTO l = new com.wms.model.LoaiDichVuDTO();
        l.setMaLoaiDV(txtMaLoaiDV.getText());
        l.setTenLoaiDV(txtTenLoaiDV.getText());
        l.setTrangThaiLDV(cbxTrangThaiLDV.getSelectedItem().toString());

        if (new com.wms.dao.LoaiDichVuDAO().capNhat(l)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadData();
        }
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        txtMaLoaiDV.setText(generateMaLoai());
        txtTenLoaiDV.setText("");
        cbxTrangThaiLDV.setSelectedIndex(0);
        tblLoaiDichVu.clearSelection();
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        // Tạm thời load lại toàn bộ vì SP chưa hỗ trợ search loại
        loadData();
    }

    private void tblLoaiDichVuMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblLoaiDichVu.getSelectedRow();
        if (row >= 0) {
            txtMaLoaiDV.setText(tableModel.getValueAt(row, 0).toString());
            txtTenLoaiDV.setText(tableModel.getValueAt(row, 1).toString());
            cbxTrangThaiLDV.setSelectedItem(tableModel.getValueAt(row, 2).toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                QuanLyLoaiDichVuForm dialog = new QuanLyLoaiDichVuForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxTrangThaiLDV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMaLoaiDV;
    private javax.swing.JLabel lblTenLoaiDV;
    private javax.swing.JLabel lblTrangThaiLDV;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTable tblLoaiDichVu;
    private javax.swing.JTextField txtMaLoaiDV;
    private javax.swing.JTextField txtTenLoaiDV;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}



