package com.wms.view.TrangChuHoiVien.ThongTinHoiVien;

import com.wms.controller.TrangChuQuanLy.QuanLyHoiVien.ThongTinHoiVienController;
import com.wms.model.TrangChuQuanLy.QuanLyHoiVien.HoiVienDTO;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.time.LocalDate;

public class ThongTinHoiVienForm extends javax.swing.JPanel {

    private ThongTinHoiVienController controller;

    public ThongTinHoiVienForm() {
        initComponents();
        com.wms.util.DateInputUtil.attachDatePicker(txtNgaySinh);
        controller = new ThongTinHoiVienController();
        loadData();
    }

    private void loadData() {
        HoiVienDTO dto = controller.layThongTin();
        if (dto == null || dto.getMaND() == null) return;
        
        lblDisplayName.setText(dto.getHoTen());
        lblDisplayTier.setText(dto.getHangThanhVien());
        if (dto.getThoiGianTao() != null) {
            lblJoinDate.setText("Tham gia từ: " + com.wms.util.DateInputUtil.formatDate(dto.getThoiGianTao()));
        }
        
        txtHoTen.setText(dto.getHoTen());
        txtSDT.setText(dto.getSdt());
        txtEmail.setText(dto.getEmail());
        if (dto.getNgaySinh() != null) {
            txtNgaySinh.setText(com.wms.util.DateInputUtil.formatDate(dto.getNgaySinh()));
        }
        
        if (dto.getGioiTinh() != null) {
            cbxGioiTinh.setSelectedItem(dto.getGioiTinh());
        }

        if (dto.getAnhDaiDien() != null) {
            try {
                ImageIcon icon = new ImageIcon(dto.getAnhDaiDien());
                Image img = icon.getImage().getScaledInstance(lblAvatar.getWidth(), lblAvatar.getHeight(), Image.SCALE_SMOOTH);
                lblAvatar.setIcon(new ImageIcon(img));
                lblAvatar.setText("");
                lblAvatar.putClientProperty("anhData", dto.getAnhDaiDien());
            } catch (Exception e) {
                lblAvatar.setIcon(null);
                lblAvatar.setText("[Lỗi ảnh]");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnLeftCard = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        btnChangeAvatar = new javax.swing.JButton();
        lblDisplayName = new javax.swing.JLabel();
        lblDisplayTier = new javax.swing.JLabel();
        lblJoinDate = new javax.swing.JLabel();
        pnRightCard = new javax.swing.JPanel();
        lblProfileTitle = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        cbxGioiTinh = new javax.swing.JComboBox<>();
        btnUpdateProfile = new javax.swing.JButton();
        pnLine = new javax.swing.JPanel();
        lblSecurityTitle = new javax.swing.JLabel();
        lblOldPass = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JPasswordField();
        lblNewPass = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JPasswordField();
        lblConfirmPass = new javax.swing.JLabel();
        txtConfirmPass = new javax.swing.JPasswordField();
        btnChangePass = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblTitle.setText("Thông tin tài khoản");
        pnMain.add(lblTitle);
        lblTitle.setBounds(30, 20, 400, 32);

        pnLeftCard.setBackground(new java.awt.Color(255, 255, 255));
        pnLeftCard.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeftCard.setLayout(null);

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setText("Ảnh đại diện");
        lblAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnLeftCard.add(lblAvatar);
        lblAvatar.setBounds(50, 40, 200, 200);

        btnChangeAvatar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnChangeAvatar.setForeground(new java.awt.Color(235, 94, 141));
        btnChangeAvatar.setText("Thay đổi ảnh");
        btnChangeAvatar.addActionListener(this::btnChangeAvatarActionPerformed);
        pnLeftCard.add(btnChangeAvatar);
        btnChangeAvatar.setBounds(50, 260, 200, 35);

        lblDisplayName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDisplayName.setForeground(new java.awt.Color(48, 30, 35));
        lblDisplayName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplayName.setText("Nguyễn Văn A");
        pnLeftCard.add(lblDisplayName);
        lblDisplayName.setBounds(0, 320, 300, 30);

        lblDisplayTier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDisplayTier.setForeground(new java.awt.Color(235, 94, 141));
        lblDisplayTier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplayTier.setText("VIP Kim Cương");
        pnLeftCard.add(lblDisplayTier);
        lblDisplayTier.setBounds(0, 350, 300, 25);

        lblJoinDate.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblJoinDate.setForeground(new java.awt.Color(136, 136, 136));
        lblJoinDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJoinDate.setText("Tham gia từ: 01/01/2024");
        pnLeftCard.add(lblJoinDate);
        lblJoinDate.setBounds(0, 380, 300, 25);

        pnMain.add(pnLeftCard);
        pnLeftCard.setBounds(30, 70, 300, 520);

        pnRightCard.setBackground(new java.awt.Color(255, 255, 255));
        pnRightCard.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRightCard.setLayout(null);

        lblProfileTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblProfileTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblProfileTitle.setText("HỒ SƠ CÁ NHÂN");
        pnRightCard.add(lblProfileTitle);
        lblProfileTitle.setBounds(30, 20, 300, 30);

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(35, 30, 48));
        lblHoTen.setText("Họ và tên");
        pnRightCard.add(lblHoTen);
        lblHoTen.setBounds(30, 60, 200, 18);

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRightCard.add(txtHoTen);
        txtHoTen.setBounds(30, 80, 280, 35);

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(35, 30, 48));
        lblSDT.setText("Số điện thoại");
        pnRightCard.add(lblSDT);
        lblSDT.setBounds(340, 60, 200, 18);

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRightCard.add(txtSDT);
        txtSDT.setBounds(340, 80, 280, 35);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(35, 30, 48));
        lblEmail.setText("Email (Tài khoản)");
        pnRightCard.add(lblEmail);
        lblEmail.setBounds(30, 130, 200, 18);

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setBackground(new java.awt.Color(240, 240, 240));
        pnRightCard.add(txtEmail);
        txtEmail.setBounds(30, 150, 280, 35);

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(35, 30, 48));
        lblNgaySinh.setText("Ngày sinh (dd/MM/yyyy)");
        pnRightCard.add(lblNgaySinh);
        lblNgaySinh.setBounds(340, 130, 200, 18);

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRightCard.add(txtNgaySinh);
        txtNgaySinh.setBounds(340, 150, 280, 35);

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(35, 30, 48));
        lblGioiTinh.setText("Giới tính");
        pnRightCard.add(lblGioiTinh);
        lblGioiTinh.setBounds(30, 200, 200, 18);

        cbxGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        pnRightCard.add(cbxGioiTinh);
        cbxGioiTinh.setBounds(30, 220, 280, 35);

        btnUpdateProfile.setBackground(new java.awt.Color(235, 94, 141));
        btnUpdateProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateProfile.setText("Cập nhật thông tin");
        btnUpdateProfile.addActionListener(this::btnUpdateProfileActionPerformed);
        pnRightCard.add(btnUpdateProfile);
        btnUpdateProfile.setBounds(30, 275, 200, 40);

        pnLine.setBackground(new java.awt.Color(224, 224, 224));
        pnRightCard.add(pnLine);
        pnLine.setBounds(30, 340, 600, 1);

        lblSecurityTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSecurityTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblSecurityTitle.setText("BẢO MẬT & MẬT KHẨU");
        pnRightCard.add(lblSecurityTitle);
        lblSecurityTitle.setBounds(30, 360, 300, 30);

        lblOldPass.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblOldPass.setForeground(new java.awt.Color(35, 30, 48));
        lblOldPass.setText("Mật khẩu hiện tại");
        pnRightCard.add(lblOldPass);
        lblOldPass.setBounds(30, 400, 190, 18);

        txtOldPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRightCard.add(txtOldPass);
        txtOldPass.setBounds(30, 420, 190, 35);

        lblNewPass.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNewPass.setForeground(new java.awt.Color(35, 30, 48));
        lblNewPass.setText("Mật khẩu mới");
        pnRightCard.add(lblNewPass);
        lblNewPass.setBounds(235, 400, 190, 18);

        txtNewPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRightCard.add(txtNewPass);
        txtNewPass.setBounds(235, 420, 190, 35);

        lblConfirmPass.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblConfirmPass.setForeground(new java.awt.Color(35, 30, 48));
        lblConfirmPass.setText("Xác nhận mật khẩu");
        pnRightCard.add(lblConfirmPass);
        lblConfirmPass.setBounds(440, 400, 190, 18);

        txtConfirmPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRightCard.add(txtConfirmPass);
        txtConfirmPass.setBounds(440, 420, 190, 35);

        btnChangePass.setBackground(new java.awt.Color(48, 30, 35));
        btnChangePass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.addActionListener(this::btnChangePassActionPerformed);
        pnRightCard.add(btnChangePass);
        btnChangePass.setBounds(30, 465, 200, 40);

        pnMain.add(pnRightCard);
        pnRightCard.setBounds(350, 70, 660, 520);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeAvatarActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "jpeg"));
        if (chooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            try {
                java.io.File file = chooser.getSelectedFile();
                byte[] data = java.nio.file.Files.readAllBytes(file.toPath());
                ImageIcon icon = new ImageIcon(data);
                Image img = icon.getImage().getScaledInstance(lblAvatar.getWidth(), lblAvatar.getHeight(), Image.SCALE_SMOOTH);
                lblAvatar.setIcon(new ImageIcon(img));
                lblAvatar.setText("");
                lblAvatar.putClientProperty("anhData", data);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi đọc ảnh!");
            }
        }
    }

    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            HoiVienDTO dto = new HoiVienDTO();
            dto.setHoTen(txtHoTen.getText().trim());
            dto.setSdt(txtSDT.getText().trim());
            
            LocalDate ngaySinh = com.wms.util.DateInputUtil.parseDate(txtNgaySinh.getText(), "Ngày sinh");
            if (ngaySinh != null && ngaySinh.isAfter(LocalDate.now())) {
                throw new IllegalArgumentException("Ngày sinh không được lớn hơn ngày hiện tại.");
            }
            dto.setNgaySinh(com.wms.util.DateInputUtil.toSqlDate(ngaySinh));
            
            dto.setGioiTinh(cbxGioiTinh.getSelectedItem().toString());
            
            Object data = lblAvatar.getClientProperty("anhData");
            dto.setAnhDaiDien(data instanceof byte[] ? (byte[]) data : null);
            
            if (controller.capNhatThongTin(dto)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                loadData();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thất bại!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            com.wms.util.MessageUtil.showError(this, e.getMessage(), e);
        }
    }

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {
        String mkCu = new String(txtOldPass.getPassword());
        String mkMoi = new String(txtNewPass.getPassword());
        String xacNhan = new String(txtConfirmPass.getPassword());
        
        if (mkCu.isEmpty() || mkMoi.isEmpty() || xacNhan.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin mật khẩu!");
            return;
        }
        
        if (!mkMoi.equals(xacNhan)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không khớp!");
            return;
        }
        
        if (controller.doiMatKhau(mkCu, mkMoi)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
            txtOldPass.setText("");
            txtNewPass.setText("");
            txtConfirmPass.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Mật khẩu hiện tại không đúng!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeAvatar;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JComboBox<String> cbxGioiTinh;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblConfirmPass;
    private javax.swing.JLabel lblDisplayName;
    private javax.swing.JLabel lblDisplayTier;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblJoinDate;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JLabel lblProfileTitle;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSecurityTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnLeftCard;
    private javax.swing.JPanel pnLine;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRightCard;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JPasswordField txtOldPass;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}


