/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wms.view.QuanLyKhongGian;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyKhongGianForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyKhongGianForm.class.getName());

    /**
     * Creates new form QuanLyKhongGian
     */
    public QuanLyKhongGianForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblMaKhongGian = new javax.swing.JLabel();
        txtMaKhongGian = new javax.swing.JTextField();
        lblTenKhongGian = new javax.swing.JLabel();
        txtTenKhongGian = new javax.swing.JTextField();
        lblChiNhanh = new javax.swing.JLabel();
        cbxChiNhanh = new javax.swing.JComboBox<>();
        lblLoaiKhongGian = new javax.swing.JLabel();
        cbxLoaiKhongGian = new javax.swing.JComboBox<>();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnVoHieuHoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhongGian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý Không gian - Không gian làm việc và học tập");
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 550));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ KHÔNG GIAN TẠI CHI NHÁNH");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        lblMaKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblMaKhongGian.setText("Mã không gian (Tự động)");
        pnMain.add(lblMaKhongGian);
        lblMaKhongGian.setBounds(20, 80, 360, 18);

        txtMaKhongGian.setEditable(false);
        txtMaKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaKhongGian.setBackground(new java.awt.Color(240, 240, 240));
        pnMain.add(txtMaKhongGian);
        txtMaKhongGian.setBounds(20, 100, 360, 35);

        lblTenKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblTenKhongGian.setText("Tên không gian (*)");
        pnMain.add(lblTenKhongGian);
        lblTenKhongGian.setBounds(20, 150, 360, 18);

        txtTenKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTenKhongGian);
        txtTenKhongGian.setBounds(20, 170, 360, 35);

        lblChiNhanh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChiNhanh.setForeground(new java.awt.Color(35, 30, 48));
        lblChiNhanh.setText("Thuộc Chi nhánh (*)");
        pnMain.add(lblChiNhanh);
        lblChiNhanh.setBounds(20, 220, 360, 18);

        cbxChiNhanh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxChiNhanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn chi nhánh --", "Chi nhánh Trung tâm" }));
        pnMain.add(cbxChiNhanh);
        cbxChiNhanh.setBounds(20, 240, 360, 35);

        lblLoaiKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoaiKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblLoaiKhongGian.setText("Loại không gian (*)");
        pnMain.add(lblLoaiKhongGian);
        lblLoaiKhongGian.setBounds(20, 290, 360, 18);

        cbxLoaiKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxLoaiKhongGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn loại không gian --", "Chỗ ngồi cá nhân", "Phòng họp" }));
        pnMain.add(cbxLoaiKhongGian);
        cbxLoaiKhongGian.setBounds(20, 310, 360, 35);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnMain.add(btnThemMoi);
        btnThemMoi.setBounds(20, 380, 170, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnMain.add(btnCapNhat);
        btnCapNhat.setBounds(210, 380, 170, 40);

        btnVoHieuHoa.setBackground(new java.awt.Color(220, 53, 69));
        btnVoHieuHoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoHieuHoa.setForeground(new java.awt.Color(255, 255, 255));
        btnVoHieuHoa.setText("Vô hiệu hóa");
        btnVoHieuHoa.addActionListener(this::btnVoHieuHoaActionPerformed);
        pnMain.add(btnVoHieuHoa);
        btnVoHieuHoa.setBounds(20, 440, 170, 40);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnMain.add(btnHuy);
        btnHuy.setBounds(210, 440, 170, 40);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm Tên KG:");
        pnMain.add(lblTimKiem);
        lblTimKiem.setBounds(420, 80, 150, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTimKiem);
        txtTimKiem.setBounds(575, 80, 325, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnMain.add(btnTimKiem);
        btnTimKiem.setBounds(920, 80, 100, 35);

        tblKhongGian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KG", "Tên không gian", "Chi nhánh", "Loại KG", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhongGian.setRowHeight(30);
        tblKhongGian.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblKhongGian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhongGianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhongGian);

        pnMain.add(jScrollPane1);
        jScrollPane1.setBounds(420, 130, 600, 375);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO: Viết logic Thêm mới không gian (Kiểm tra dữ liệu, Insert Database, Sinh QR)
    }                                          

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO: Viết logic Cập nhật không gian
    }                                          

    private void btnVoHieuHoaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO: Viết logic Vô hiệu hóa không gian (kiểm tra điều kiện khách đang đặt chỗ, cập nhật Status = 0)
    }                                        

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO: Xóa trắng form nhập liệu
    }                                      

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO: Viết logic tra cứu theo Tên Không gian
    }                                          

    private void tblKhongGianMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO: Lấy dữ liệu từ dòng được click trên JTable và hiển thị lên các TextBox, ComboBox bên trái
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuanLyKhongGianForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnVoHieuHoa;
    private javax.swing.JComboBox<String> cbxChiNhanh;
    private javax.swing.JComboBox<String> cbxLoaiKhongGian;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChiNhanh;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblLoaiKhongGian;
    private javax.swing.JLabel lblMaKhongGian;
    private javax.swing.JLabel lblTenKhongGian;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblKhongGian;
    private javax.swing.JTextField txtMaKhongGian;
    private javax.swing.JTextField txtTenKhongGian;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
