CREATE TABLE NGUOIDUNG (
    MaND VARCHAR2(50) PRIMARY KEY,
    HoTen VARCHAR2(100),
    TenTaiKhoan VARCHAR2(50),
    MatKhauMaHoa VARCHAR2(255),
    AnhDaiDien BLOB,
    GioiTinh VARCHAR2(10),
    Email VARCHAR2(100),
    SDT VARCHAR2(20),
    NgaySinh DATE,
    ThoiGianTao TIMESTAMP,
    CapNhatLanCuoi TIMESTAMP,
    LanCuoiDangNhap TIMESTAMP,
    TrangThaiND VARCHAR2(50)
);

ALTER TABLE NGUOIDUNG ADD CONSTRAINT UNIQUE_ND_SDT UNIQUE (SDT);
ALTER TABLE NGUOIDUNG ADD CONSTRAINT UNIQUE_ND_Email UNIQUE (Email);
ALTER TABLE NGUOIDUNG ADD CONSTRAINT UNIQUE_ND_TenTaiKhoan UNIQUE (TenTaiKhoan);