/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyDichVuDat;

import com.wms.controller.QuanLyDichVuDatController;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyDichVuDatForm extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyDichVuDatForm
     */
    private com.wms.controller.QuanLyDichVuDatController controller;

    public QuanLyDichVuDatForm() {
        initComponents();
        controller = new com.wms.controller.QuanLyDichVuDatController(this);
        
        // Setup dynamic behavior for ComboBox
        cboLoaiDichVu.addActionListener(e -> updateTenDichVu());
        
        loadDataLoaiDichVu();
        controller.loadData("");
    }

    private void loadDataLoaiDichVu() {
        if (controller == null) return;
        java.util.List<String> dsLoai = controller.getDanhSachLoaiDichVu();
        cboLoaiDichVu.removeAllItems();
        cboLoaiDichVu.addItem("");
        for (String loai : dsLoai) {
            cboLoaiDichVu.addItem(loai);
        }
    }

    private void updateTenDichVu() {
        if (cboLoaiDichVu.getSelectedItem() == null) return;
        String loaiDV = cboLoaiDichVu.getSelectedItem().toString().trim();
        cboTenDichVu.removeAllItems();
        
        if (!loaiDV.isEmpty() && controller != null) {
            java.util.List<String> dsTen = controller.getDanhSachTenDichVu(loaiDV);
            cboTenDichVu.addItem("");
            for (String ten : dsTen) {
                cboTenDichVu.addItem(ten);
            }
        }
    }

    public void hienThiDuLieu(java.util.List<com.wms.model.DichVuDaDatDTO> danhSach) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableDichVu.getModel();
        model.setRowCount(0);
        
        if (danhSach != null) {
            for (com.wms.model.DichVuDaDatDTO dto : danhSach) {
                model.addRow(new Object[]{
                    dto.getMaPhien(),
                    dto.getTenDichVu(),
                    dto.getSoLuong(),
                    dto.getThoiGianDat(),
                    dto.getKhachHang(),
                    dto.getTenKhongGian(),
                    dto.getGhiChu()
                });
            }
        }
    }

    public void hienThiThongBaoLoi(String thongBao) {
        javax.swing.JOptionPane.showMessageDialog(this, thongBao, "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTraCuu = new javax.swing.JButton();
        btnTaiLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDichVu = new javax.swing.JTable();
        pnRight = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaPhien = new javax.swing.JLabel();
        txtMaPhien = new javax.swing.JTextField();
        lblLoaiDichVu = new javax.swing.JLabel();
        cboLoaiDichVu = new javax.swing.JComboBox<>();
        lblTenDichVu = new javax.swing.JLabel();
        cboTenDichVu = new javax.swing.JComboBox<>();
        lblSoLuong = new javax.swing.JLabel();
        spinSoLuong = new javax.swing.JSpinner();
        lblGhiChu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ DỊCH VỤ ĐƯỢC ĐẶT");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH CÁC DỊCH VỤ");
        pnLeft.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 250, 30);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm mã phiên/tên DV:");
        pnLeft.add(lblTimKiem);
        lblTimKiem.setBounds(20, 55, 160, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTimKiem.addActionListener(this::txtTimKiemActionPerformed);
        pnLeft.add(txtTimKiem);
        txtTimKiem.setBounds(180, 55, 220, 35);

        btnTraCuu.setBackground(new java.awt.Color(235, 94, 141));
        btnTraCuu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTraCuu.setForeground(new java.awt.Color(255, 255, 255));
        btnTraCuu.setText("Tìm");
        btnTraCuu.addActionListener(this::btnTraCuuActionPerformed);
        pnLeft.add(btnTraCuu);
        btnTraCuu.setBounds(410, 55, 70, 35);

        btnTaiLai.setBackground(new java.awt.Color(235, 94, 141));
        btnTaiLai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTaiLai.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiLai.setText("Tải lại");
        btnTaiLai.addActionListener(this::btnTaiLaiActionPerformed);
        pnLeft.add(btnTaiLai);
        btnTaiLai.setBounds(490, 55, 80, 35);

        tableDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phiên", "Tên Dịch Vụ", "SL", "Thời Gian Đặt", "Khách Hàng", "Tên Không Gian", "Ghi Chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDichVu.setRowHeight(35);
        tableDichVu.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tableDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDichVu);

        pnLeft.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 550, 410);

        pnMain.add(pnLeft);
        pnLeft.setBounds(20, 80, 590, 540);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("THÊM DỊCH VỤ CHO PHIÊN");
        pnRight.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 300, 30);

        lblMaPhien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhien.setForeground(new java.awt.Color(35, 30, 48));
        lblMaPhien.setText("Mã Phiên (*)");
        pnRight.add(lblMaPhien);
        lblMaPhien.setBounds(20, 70, 360, 20);

        txtMaPhien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtMaPhien);
        txtMaPhien.setBounds(20, 90, 360, 35);

        lblLoaiDichVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLoaiDichVu.setForeground(new java.awt.Color(35, 30, 48));
        lblLoaiDichVu.setText("Loại Dịch Vụ");
        pnRight.add(lblLoaiDichVu);
        lblLoaiDichVu.setBounds(20, 140, 360, 20);

        cboLoaiDichVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(cboLoaiDichVu);
        cboLoaiDichVu.setBounds(20, 160, 360, 35);

        lblTenDichVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenDichVu.setForeground(new java.awt.Color(35, 30, 48));
        lblTenDichVu.setText("Tên Dịch Vụ");
        pnRight.add(lblTenDichVu);
        lblTenDichVu.setBounds(20, 210, 360, 20);

        cboTenDichVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(cboTenDichVu);
        cboTenDichVu.setBounds(20, 230, 360, 35);

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoLuong.setForeground(new java.awt.Color(35, 30, 48));
        lblSoLuong.setText("Số Lượng");
        pnRight.add(lblSoLuong);
        lblSoLuong.setBounds(20, 280, 360, 20);

        spinSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(spinSoLuong);
        spinSoLuong.setBounds(20, 300, 360, 35);

        lblGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(35, 30, 48));
        lblGhiChu.setText("Ghi Chú (Tùy chọn)");
        pnRight.add(lblGhiChu);
        lblGhiChu.setBounds(20, 350, 360, 20);

        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtGhiChu);
        txtGhiChu.setBounds(20, 370, 360, 35);

        btnLuu.setBackground(new java.awt.Color(235, 94, 141));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Thêm Dịch Vụ");
        btnLuu.addActionListener(this::btnLuuActionPerformed);
        pnRight.add(btnLuu);
        btnLuu.setBounds(20, 440, 170, 40);

        btnHuy.setBackground(new java.awt.Color(220, 53, 69));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Làm Mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnRight.add(btnHuy);
        btnHuy.setBounds(210, 440, 170, 40);

        pnMain.add(pnRight);
        pnRight.setBounds(630, 80, 400, 540);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        btnTraCuuActionPerformed(evt);
    }

    private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {
        if (controller != null) {
            controller.loadData(txtTimKiem.getText().trim());
        }
    }

    private void btnTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {
        txtTimKiem.setText("");
        if (controller != null) {
            controller.loadData("");
        }
    }

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {
        String maPhien = txtMaPhien.getText().trim();
        Object loaiSelected = cboLoaiDichVu.getSelectedItem();
        Object tenSelected = cboTenDichVu.getSelectedItem();
        String loaiDV = (loaiSelected != null) ? loaiSelected.toString().trim() : "";
        String tenDV = (tenSelected != null) ? tenSelected.toString().trim() : "";
        int soLuong = (int) spinSoLuong.getValue();
        String ghiChu = txtGhiChu.getText().trim();

        if (maPhien.isEmpty()) {
            hienThiThongBaoLoi("Vui lòng nhập Mã Phiên!");
            return;
        }
        
        if (loaiDV.isEmpty() || tenDV.isEmpty()) {
            hienThiThongBaoLoi("Vui lòng chọn Loại Dịch Vụ và Tên Dịch Vụ!");
            return;
        }

        if (soLuong <= 0) {
            hienThiThongBaoLoi("Số lượng phải lớn hơn 0!");
            return;
        }

        boolean success = controller.themDichVu(maPhien, tenDV, soLuong, ghiChu);
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm dịch vụ thành công!", "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            btnHuyActionPerformed(null);
            controller.loadData("");
        } else {
            hienThiThongBaoLoi("Thêm dịch vụ thất bại. Vui lòng kiểm tra lại Mã Phiên.");
        }
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        txtMaPhien.setText("");
        if (cboLoaiDichVu.getItemCount() > 0) cboLoaiDichVu.setSelectedIndex(0);
        if (cboTenDichVu.getItemCount() > 0) cboTenDichVu.setSelectedIndex(0);
        spinSoLuong.setValue(1);
        txtGhiChu.setText("");
        tableDichVu.clearSelection();
    }

    private void tableDichVuMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tableDichVu.getSelectedRow();
        if (row >= 0) {
            txtMaPhien.setText(tableDichVu.getValueAt(row, 0).toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnTaiLai;
    private javax.swing.JButton btnTraCuu;
    private javax.swing.JComboBox<String> cboLoaiDichVu;
    private javax.swing.JComboBox<String> cboTenDichVu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblLoaiDichVu;
    private javax.swing.JLabel lblMaPhien;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenDichVu;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JSpinner spinSoLuong;
    private javax.swing.JTable tableDichVu;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaPhien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}


