package com.wms.view.TrangChuQuanLy.QuanLyDichVuDat;

import com.wms.controller.TrangChuQuanLy.QuanLyDichVuDat.QuanLyDichVuDatController;
import com.wms.model.TrangChuQuanLy.QuanLyDichVuDat.DichVuDaDatDTO;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.List;

public class QuanLyDichVuDatForm extends javax.swing.JPanel {

    private final QuanLyDichVuDatController controller = new QuanLyDichVuDatController();
    private final SimpleDateFormat sdfHienThi = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    private List<DichVuDaDatDTO> currentDichVuList;

    public QuanLyDichVuDatForm() {
        initComponents();
        cboLoaiDichVu.addActionListener(e -> updateTenDichVu());
        loadDataLoaiDichVu();
        loadData("");
        com.wms.util.TienIchFormQuanLy.apDung(this);
    }

    private void loadData(String keyword) {
        loadDataPhienHoatDong(keyword);
        hienThiDanhSachDichVu(null); // Xóa bảng bên phải khi load lại
    }

    private void loadDataPhienHoatDong(String keyword) {
        List<Object[]> ds = controller.layDanhSachPhienHoatDong(keyword);
        hienThiPhienHoatDong(ds);
    }

    private void loadDataLoaiDichVu() {
        cboLoaiDichVu.removeAllItems();
        cboLoaiDichVu.addItem("--- Chọn loại dịch vụ ---");

        for (String loai : controller.layDanhSachLoaiDichVu()) {
            cboLoaiDichVu.addItem(loai);
        }
    }

    private void updateTenDichVu() {
        Object sel = cboLoaiDichVu.getSelectedItem();
        if (sel == null || sel.toString().contains("---")) {
            cboTenDichVu.removeAllItems();
            cboTenDichVu.addItem("--- Chọn tên dịch vụ ---");
            return;
        }
        String loaiDV = sel.toString().trim();
        cboTenDichVu.removeAllItems();
        cboTenDichVu.addItem("--- Chọn tên dịch vụ ---");
        for (String ten : controller.layDanhSachTenDichVu(loaiDV)) {
            cboTenDichVu.addItem(ten);
        }
    }

    private void hienThiPhienHoatDong(List<Object[]> danhSach) {
        DefaultTableModel model = (DefaultTableModel) tablePhienDangHoatDong.getModel();
        model.setRowCount(0);
        if (danhSach == null)
            return;
        for (Object[] row : danhSach) {
            String batDau = row[3] != null ? sdfHienThi.format(row[3]) : "-";
            String ketThuc = row[4] != null ? sdfHienThi.format(row[4]) : "-";
            model.addRow(new Object[] {
                    row[0], // Mã Phiên
                    row[1], // Khách Hàng
                    row[2], // Không Gian
                    batDau, // Bắt Đầu
                    ketThuc, // Kết Thúc
                    row[5] // Trạng Thái
            });
        }
    }

    private void hienThiDanhSachDichVu(String maPhien) {
        currentDichVuList = controller.layDSDichVuTheoPhien(maPhien);
        DefaultTableModel model = (DefaultTableModel) tableDichVu.getModel();
        model.setRowCount(0);
        if (currentDichVuList == null)
            return;
        for (DichVuDaDatDTO dto : currentDichVuList) {
            model.addRow(new Object[] {
                    dto.getMaPhien(), dto.getTenDichVu(), dto.getSoLuong(), dto.getGhiChu()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTraCuu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePhienDangHoatDong = new javax.swing.JTable();
        pnRight = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaPhien = new javax.swing.JLabel();
        txtMaPhien = new javax.swing.JTextField();
        lblLoaiDichVu = new javax.swing.JLabel();
        cboLoaiDichVu = new javax.swing.JComboBox<>();
        lblTenDichVu = new javax.swing.JLabel();
        cboTenDichVu = new javax.swing.JComboBox<>();
        lblSoLuong = new javax.swing.JLabel();
        spinSoLuong = new javax.swing.JSpinner();
        lblGhiChu = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtKhachHang = new javax.swing.JTextField();
        lblMaPhien1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDichVu = new javax.swing.JTable();
        lblDetailTitle1 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ DỊCH VỤ ĐƯỢC ĐẶT");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("CÁC PHIÊN ĐANG HOẠT ĐỘNG");
        pnLeft.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 250, 30);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm mã phiên/tên DV:");
        pnLeft.add(lblTimKiem);
        lblTimKiem.setBounds(20, 55, 160, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTimKiem.addActionListener(this::txtTimKiemActionPerformed);
        pnLeft.add(txtTimKiem);
        txtTimKiem.setBounds(180, 55, 220, 35);

        btnTraCuu.setBackground(new java.awt.Color(235, 94, 141));
        btnTraCuu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTraCuu.setForeground(new java.awt.Color(255, 255, 255));
        btnTraCuu.setText("Tìm");
        btnTraCuu.addActionListener(this::btnTraCuuActionPerformed);
        pnLeft.add(btnTraCuu);
        btnTraCuu.setBounds(410, 55, 70, 35);

        tablePhienDangHoatDong.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã Phiên", "Khách Hàng", "Không Gian", "Giờ Bắt Đầu", "Giờ Kết Thúc", "Trạng Thái"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tablePhienDangHoatDong.setRowHeight(35);
        tablePhienDangHoatDong.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tablePhienDangHoatDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePhienDangHoatDongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePhienDangHoatDong);

        pnLeft.add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 570, 410);

        pnMain.add(pnLeft);
        pnLeft.setBounds(460, 80, 590, 540);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("DANH SÁCH CÁC DỊCH VỤ");
        pnRight.add(lblDetailTitle);
        lblDetailTitle.setBounds(10, 10, 300, 30);

        lblMaPhien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaPhien.setForeground(new java.awt.Color(35, 30, 48));
        lblMaPhien.setText("Mã Phiên");
        pnRight.add(lblMaPhien);
        lblMaPhien.setBounds(230, 260, 180, 20);

        txtMaPhien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtMaPhien);
        txtMaPhien.setBounds(230, 280, 180, 35);

        lblLoaiDichVu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoaiDichVu.setForeground(new java.awt.Color(35, 30, 48));
        lblLoaiDichVu.setText("Loại Dịch Vụ");
        pnRight.add(lblLoaiDichVu);
        lblLoaiDichVu.setBounds(20, 320, 190, 20);

        cboLoaiDichVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(cboLoaiDichVu);
        cboLoaiDichVu.setBounds(20, 340, 180, 35);

        lblTenDichVu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenDichVu.setForeground(new java.awt.Color(35, 30, 48));
        lblTenDichVu.setText("Tên Dịch Vụ");
        pnRight.add(lblTenDichVu);
        lblTenDichVu.setBounds(230, 320, 180, 20);

        cboTenDichVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(cboTenDichVu);
        cboTenDichVu.setBounds(230, 340, 180, 35);

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSoLuong.setForeground(new java.awt.Color(35, 30, 48));
        lblSoLuong.setText("Số Lượng");
        pnRight.add(lblSoLuong);
        lblSoLuong.setBounds(230, 380, 100, 20);

        spinSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(spinSoLuong);
        spinSoLuong.setBounds(230, 400, 180, 35);

        lblGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(35, 30, 48));
        lblGhiChu.setText("Ghi Chú (Tùy chọn)");
        pnRight.add(lblGhiChu);
        lblGhiChu.setBounds(20, 380, 180, 20);

        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtGhiChu);
        txtGhiChu.setBounds(20, 400, 180, 35);

        btnLuu.setBackground(new java.awt.Color(235, 94, 141));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Thêm Dịch Vụ");
        btnLuu.addActionListener(this::btnLuuActionPerformed);
        pnRight.add(btnLuu);
        btnLuu.setBounds(20, 450, 180, 40);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm Mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnRight.add(btnHuy);
        btnHuy.setBounds(230, 500, 180, 40);

        txtKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKhachHang.addActionListener(this::txtKhachHangActionPerformed);
        pnRight.add(txtKhachHang);
        txtKhachHang.setBounds(20, 280, 180, 35);

        lblMaPhien1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaPhien1.setForeground(new java.awt.Color(35, 30, 48));
        lblMaPhien1.setText("Khách hàng");
        pnRight.add(lblMaPhien1);
        lblMaPhien1.setBounds(20, 260, 190, 20);

        tableDichVu.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã Phiên", "Tên Dịch Vụ", "SL", "Ghi Chú"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tableDichVu.setRowHeight(35);
        tableDichVu.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tableDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDichVu);

        pnRight.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 410, 170);

        lblDetailTitle1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle1.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle1.setText("THÊM DỊCH VỤ CHO PHIÊN");
        pnRight.add(lblDetailTitle1);
        lblDetailTitle1.setBounds(10, 230, 300, 30);

        btnXoa.setBackground(new java.awt.Color(235, 94, 141));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá Dịch Vụ");
        btnXoa.addActionListener(this::btnXoaActionPerformed);
        pnRight.add(btnXoa);
        btnXoa.setBounds(230, 450, 180, 40);

        btnSua.setBackground(new java.awt.Color(235, 94, 141));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText(" Sửa dịch vụ");
        btnSua.addActionListener(this::btnSuaActionPerformed);
        pnRight.add(btnSua);
        btnSua.setBounds(20, 500, 180, 40);

        pnMain.add(pnRight);
        pnRight.setBounds(10, 80, 430, 540);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKhachHangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKhachHangActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtKhachHangActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {
        String maPhien = txtMaPhien.getText().trim();
        String tenDV = cboTenDichVu.getSelectedItem() != null ? cboTenDichVu.getSelectedItem().toString() : "";

        if (maPhien.isEmpty() || tenDV.isEmpty() || tenDV.contains("---")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dịch vụ cần xóa từ danh sách!", "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int xacNhan = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa dịch vụ này khỏi phiên?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (xacNhan == JOptionPane.YES_OPTION) {
            String loi = controller.xoaDichVu(maPhien, tenDV);
            if (loi == null) {
                JOptionPane.showMessageDialog(this, "Xóa dịch vụ thành công!");
                hienThiDanhSachDichVu(maPhien);
                btnHuyActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, com.wms.util.ErrorMessageUtil.toUserMessage(loi), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {
        String maPhien = txtMaPhien.getText().trim();
        String tenDV = cboTenDichVu.getSelectedItem() != null ? cboTenDichVu.getSelectedItem().toString() : "";
        int soLuong = (int) spinSoLuong.getValue();
        String ghiChu = txtGhiChu.getText().trim();

        if (maPhien.isEmpty() || tenDV.isEmpty() || tenDV.contains("---")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dịch vụ cần sửa!", "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String loi = controller.capNhatDichVu(maPhien, tenDV, soLuong, ghiChu);
        if (loi == null) {
            JOptionPane.showMessageDialog(this, "Cập nhật dịch vụ thành công!");
            hienThiDanhSachDichVu(maPhien);
            btnHuyActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, com.wms.util.ErrorMessageUtil.toUserMessage(loi), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tablePhienDangHoatDongMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tablePhienDangHoatDong.getSelectedRow();
        if (row >= 0) {
            String maPhien = tablePhienDangHoatDong.getValueAt(row, 0).toString();
            String khachHang = tablePhienDangHoatDong.getValueAt(row, 1).toString();
            txtMaPhien.setText(maPhien);
            txtKhachHang.setText(khachHang);
            hienThiDanhSachDichVu(maPhien);
        }
    }

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        btnTraCuuActionPerformed(evt);
    }

    private void btnTraCuuActionPerformed(java.awt.event.ActionEvent evt) {
        loadData(txtTimKiem.getText().trim());
    }

    private void btnTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {
        txtTimKiem.setText("");
        loadData("");
    }

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {
        String maPhien = txtMaPhien.getText().trim();
        String loaiDV = cboLoaiDichVu.getSelectedItem() != null ? cboLoaiDichVu.getSelectedItem().toString().trim()
                : "";
        String tenDV = cboTenDichVu.getSelectedItem() != null ? cboTenDichVu.getSelectedItem().toString().trim() : "";
        int soLuong = (int) spinSoLuong.getValue();
        String ghiChu = txtGhiChu.getText().trim();

        if (maPhien.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Phiên!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (loaiDV.isEmpty() || tenDV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Loại và Tên Dịch Vụ!", "Cảnh báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (soLuong <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String loi = controller.themDichVu(maPhien, tenDV, soLuong, ghiChu);
        if (loi == null) {
            JOptionPane.showMessageDialog(this, "Thêm dịch vụ thành công!", "Thành công",
                    JOptionPane.INFORMATION_MESSAGE);
            hienThiDanhSachDichVu(maPhien);
            btnHuyActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, com.wms.util.ErrorMessageUtil.toUserMessage(loi), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        txtMaPhien.setText("");
        if (cboLoaiDichVu.getItemCount() > 0)
            cboLoaiDichVu.setSelectedIndex(0);
        if (cboTenDichVu.getItemCount() > 0)
            cboTenDichVu.setSelectedIndex(0);
        spinSoLuong.setValue(1);
        txtGhiChu.setText("");
        tableDichVu.clearSelection();
    }

    private void tableDichVuMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tableDichVu.getSelectedRow();
        if (row >= 0 && currentDichVuList != null && row < currentDichVuList.size()) {
            DichVuDaDatDTO dto = currentDichVuList.get(row);
            txtMaPhien.setText(dto.getMaPhien());
            txtKhachHang.setText(dto.getKhachHang());
            txtGhiChu.setText(dto.getGhiChu());
            spinSoLuong.setValue(dto.getSoLuong());

            // Tạm thời ngắt listener để tránh loop
            java.awt.event.ActionListener[] listeners = cboLoaiDichVu.getActionListeners();
            for (java.awt.event.ActionListener l : listeners)
                cboLoaiDichVu.removeActionListener(l);

            cboLoaiDichVu.setSelectedItem(dto.getTenLoaiDV());
            updateTenDichVu(); // Cập nhật danh sách tên theo loại
            cboTenDichVu.setSelectedItem(dto.getTenDichVu());

            // Đăng ký lại listener
            for (java.awt.event.ActionListener l : listeners)
                cboLoaiDichVu.addActionListener(l);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTraCuu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiDichVu;
    private javax.swing.JComboBox<String> cboTenDichVu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblDetailTitle1;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblLoaiDichVu;
    private javax.swing.JLabel lblMaPhien;
    private javax.swing.JLabel lblMaPhien1;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenDichVu;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JSpinner spinSoLuong;
    private javax.swing.JTable tableDichVu;
    private javax.swing.JTable tablePhienDangHoatDong;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextField txtMaPhien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
