ALTER TABLE KHONGGIAN ADD CONSTRAINT FK_KHONGGIAN_LOAIKG
    FOREIGN KEY (MaLoaiKG) REFERENCES LOAIKHONGGIAN(MaLoaiKG);

ALTER TABLE KHONGGIAN ADD CONSTRAINT FK_KHONGGIAN_CHINHANH
    FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN);

ALTER TABLE DICHVU ADD CONSTRAINT FK_DICHVU_LOAIDV
    FOREIGN KEY (MaLoaiDV) REFERENCES LOAIDICHVU(MaLoaiDV);

ALTER TABLE DATCHO ADD CONSTRAINT FK_DATCHO_KHACHHANG
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE DATCHO ADD CONSTRAINT FK_DATCHO_KHONGGIAN
    FOREIGN KEY (MaKG) REFERENCES KHONGGIAN(MaKG);

ALTER TABLE PHIENLAMVIEC ADD CONSTRAINT FK_PHIEN_KHONGGIAN
    FOREIGN KEY (MaKG) REFERENCES KHONGGIAN(MaKG);

ALTER TABLE PHIENLAMVIEC ADD CONSTRAINT FK_PHIEN_KHACHHANG
    FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE PHIENLAMVIEC ADD CONSTRAINT FK_PHIEN_DATCHO
    FOREIGN KEY (MaDatCho) REFERENCES DATCHO(MaDatCho);

ALTER TABLE CHITIETDICHVU ADD CONSTRAINT FK_CTDV_DICHVU
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV);

ALTER TABLE CHITIETDICHVU ADD CONSTRAINT FK_CTDV_PHIEN
    FOREIGN KEY (MaPhien) REFERENCES PHIENLAMVIEC(MaPhien);

ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KHACHHANG_NGUOIDUNG
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND);

ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KHACHHANG_HANGTV
    FOREIGN KEY (MaHangThanhVien) REFERENCES HANGTHANHVIEN(MaHangThanhVien);

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_NGUOIDUNG
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND);

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_CHINHANH
    FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN);

ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NHANVIEN_QUANLY
    FOREIGN KEY (MaNQL) REFERENCES NHANVIEN(MaNV);

ALTER TABLE CHITIETVAITRO ADD CONSTRAINT FK_CTVT_NGUOIDUNG
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND);

ALTER TABLE CHITIETVAITRO ADD CONSTRAINT FK_CTVT_VAITRO
    FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro);

ALTER TABLE CHITIETNHOMCHUCNANG ADD CONSTRAINT FK_CTNCN_VAITRO
    FOREIGN KEY (MaVaiTro) REFERENCES VAITRO(MaVaiTro);

ALTER TABLE CHITIETNHOMCHUCNANG ADD CONSTRAINT FK_CTNCN_NHOMCN
    FOREIGN KEY (MaNhomChucNang) REFERENCES NHOMCHUCNANG(MaNhomChucNang);

ALTER TABLE CHITIETCHUCNANG ADD CONSTRAINT FK_CTCN_NHOMCN
    FOREIGN KEY (MaNhomChucNang) REFERENCES NHOMCHUCNANG(MaNhomChucNang);

ALTER TABLE CHITIETCHUCNANG ADD CONSTRAINT FK_CTCN_CHUCNANG
    FOREIGN KEY (MaChucNang) REFERENCES CHUCNANG(MaChucNang);

ALTER TABLE PHIEUGIAMGIA ADD CONSTRAINT FK_PGG_NHANVIEN
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_PHIEN
    FOREIGN KEY (MaPhien) REFERENCES PHIENLAMVIEC(MaPhien);

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_PGG
    FOREIGN KEY (MaPGG) REFERENCES PHIEUGIAMGIA(MaPGG);

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_NHANVIEN
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE CHUNGTUNHAPKHO ADD CONSTRAINT FK_CTNK_DICHVU
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV);

ALTER TABLE CHUNGTUNHAPKHO ADD CONSTRAINT FK_CTNK_NHANVIEN
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE CHUNGTUNHAPKHO ADD CONSTRAINT FK_CTNK_CHINHANH
    FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN);
