ALTER TABLE CHUNGTUNHAPKHO ADD CONSTRAINT FK_ChungTu_DichVu
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV);

ALTER TABLE CHUNGTUNHAPKHO ADD CONSTRAINT FK_ChungTu_NhanVien
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE CHUNGTUNHAPKHO ADD CONSTRAINT FK_ChungTu_ChiNhanh
    FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN);
