/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyDatChoTruoc;

import com.wms.controller.TrangChuQuanLy.QuanLyDatChoTruoc.QuanLyDatChoTruocController;
import com.wms.controller.TrangChuGioiThieu.DangNhapController;
import com.wms.model.TrangChuQuanLy.QuanLyDatChoTruoc.DatChoTruocDTO;
import com.wms.model.TrangChuQuanLy.QuanLyPhien.KetQuaNhanChoDTO;
import com.wms.model.TrangChuQuanLy.QuanLyPhien.ThongTinXacNhanDatChoDTO;
import com.wms.util.QRCodeScannerUtil;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HuyLai
 */
public class QuanLyDatChoTruocForm extends javax.swing.JPanel {
    private final QuanLyDatChoTruocController controller = new QuanLyDatChoTruocController();
    private List<DatChoTruocDTO> currentList = new ArrayList<>();
    private final DecimalFormat moneyFormat = new DecimalFormat("#,###",
            java.text.DecimalFormatSymbols.getInstance(new java.util.Locale("vi", "VN")));

    /**
     * Creates new form QuanLyDatChoTruocForm
     */
    public QuanLyDatChoTruocForm() {
        initComponents();
        initLogic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatCho = new javax.swing.JTable();
        btnLamMoi = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaDatCho = new javax.swing.JLabel();
        txtMaDatCho = new javax.swing.JTextField();
        lblMaKH = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        lblMaKG = new javax.swing.JLabel();
        txtMaKG = new javax.swing.JTextField();
        lblDuKienToi = new javax.swing.JLabel();
        txtDuKienToi = new javax.swing.JTextField();
        lblThoiGianSuDung = new javax.swing.JLabel();
        spnThoiGianSuDung = new javax.swing.JSpinner();
        lblThanhTien = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnCapNhat = new javax.swing.JButton();
        btnNhanCho = new javax.swing.JButton();
        btnChuyenKhoan = new javax.swing.JButton();
        txtThanhTien = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1050, 640));
        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ ĐẶT CHỖ TRƯỚC");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH ĐẶT CHỖ");
        pnLeft.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 250, 30);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm (Mã ĐC/Mã KH):");
        pnLeft.add(lblTimKiem);
        lblTimKiem.setBounds(20, 60, 140, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtTimKiem);
        txtTimKiem.setBounds(160, 60, 220, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnLeft.add(btnTimKiem);
        btnTimKiem.setBounds(390, 60, 76, 35);

        tblDatCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Đặt Chỗ", "Khách Hàng", "Không Gian", "Dự Kiến Tới", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatCho.setRowHeight(35);
        tblDatCho.setSelectionBackground(new java.awt.Color(235, 94, 141));
        jScrollPane1.setViewportView(tblDatCho);

        pnLeft.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 550, 410);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(235, 94, 141));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnLeft.add(btnLamMoi);
        btnLamMoi.setBounds(470, 60, 100, 35);

        pnMain.add(pnLeft);
        pnLeft.setBounds(450, 70, 590, 540);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("THÔNG TIN CHI TIẾT");
        pnRight.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 200, 30);

        lblMaDatCho.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaDatCho.setForeground(new java.awt.Color(35, 30, 48));
        lblMaDatCho.setText("Mã đặt chỗ");
        pnRight.add(lblMaDatCho);
        lblMaDatCho.setBounds(20, 55, 360, 20);

        txtMaDatCho.setEditable(false);
        txtMaDatCho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaDatCho.setBackground(new java.awt.Color(240, 240, 240));
        pnRight.add(txtMaDatCho);
        txtMaDatCho.setBounds(20, 75, 360, 35);

        lblMaKH.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaKH.setForeground(new java.awt.Color(35, 30, 48));
        lblMaKH.setText("Mã Khách Hàng (*)");
        pnRight.add(lblMaKH);
        lblMaKH.setBounds(20, 120, 170, 20);

        txtMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtMaKH);
        txtMaKH.setBounds(20, 140, 170, 35);

        lblMaKG.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaKG.setForeground(new java.awt.Color(35, 30, 48));
        lblMaKG.setText("Mã Không Gian (*)");
        pnRight.add(lblMaKG);
        lblMaKG.setBounds(210, 120, 170, 20);

        txtMaKG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtMaKG);
        txtMaKG.setBounds(210, 140, 170, 35);

        lblDuKienToi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDuKienToi.setForeground(new java.awt.Color(35, 30, 48));
        lblDuKienToi.setText("Dự kiến tới (dd/MM/yyyy HH:mm)");
        pnRight.add(lblDuKienToi);
        lblDuKienToi.setBounds(20, 185, 220, 20);

        txtDuKienToi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtDuKienToi);
        txtDuKienToi.setBounds(20, 205, 220, 35);

        lblThoiGianSuDung.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblThoiGianSuDung.setForeground(new java.awt.Color(35, 30, 48));
        lblThoiGianSuDung.setText("Số giờ SD (*)");
        pnRight.add(lblThoiGianSuDung);
        lblThoiGianSuDung.setBounds(260, 185, 120, 20);

        spnThoiGianSuDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnThoiGianSuDung.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        pnRight.add(spnThoiGianSuDung);
        spnThoiGianSuDung.setBounds(260, 205, 120, 35);

        lblThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblThanhTien.setForeground(new java.awt.Color(35, 30, 48));
        lblThanhTien.setText("Thành tiền (VNĐ)");
        pnRight.add(lblThanhTien);
        lblThanhTien.setBounds(20, 250, 360, 20);

        txtTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTrangThai.setForeground(new java.awt.Color(51, 153, 0));
        pnRight.add(txtTrangThai);
        txtTrangThai.setBounds(20, 340, 360, 35);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái đặt chỗ");
        pnRight.add(lblTrangThai);
        lblTrangThai.setBounds(20, 315, 360, 20);

        lblGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(35, 30, 48));
        lblGhiChu.setText("Ghi chú / Yêu cầu thêm");
        pnRight.add(lblGhiChu);
        lblGhiChu.setBounds(20, 380, 360, 20);

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtGhiChu.setRows(2);
        jScrollPane2.setViewportView(txtGhiChu);

        pnRight.add(jScrollPane2);
        jScrollPane2.setBounds(20, 400, 360, 45);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnRight.add(btnCapNhat);
        btnCapNhat.setBounds(20, 460, 360, 35);

        btnNhanCho.setBackground(new java.awt.Color(235, 94, 141));
        btnNhanCho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhanCho.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanCho.setText("Quét mã QR để nhận chỗ");
        btnNhanCho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhanCho.addActionListener(this::btnNhanChoActionPerformed);
        pnRight.add(btnNhanCho);
        btnNhanCho.setBounds(210, 500, 170, 35);

        btnChuyenKhoan.setBackground(new java.awt.Color(235, 94, 141));
        btnChuyenKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChuyenKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnChuyenKhoan.setText("Đã chuyển khoản");
        btnChuyenKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChuyenKhoan.addActionListener(this::btnChuyenKhoanActionPerformed);
        pnRight.add(btnChuyenKhoan);
        btnChuyenKhoan.setBounds(20, 500, 170, 35);

        txtThanhTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtThanhTien.setForeground(new java.awt.Color(51, 153, 0));
        pnRight.add(txtThanhTien);
        txtThanhTien.setBounds(20, 270, 360, 35);

        pnMain.add(pnRight);
        pnRight.setBounds(20, 70, 400, 540);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanChoActionPerformed
        quetQrNhanCho();
    }//GEN-LAST:event_btnNhanChoActionPerformed

    private void btnChuyenKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenKhoanActionPerformed
        xacNhanChuyenKhoan();
    }//GEN-LAST:event_btnChuyenKhoanActionPerformed

    private void initLogic() {
        txtMaDatCho.setEditable(false);
        txtMaKH.setEditable(false);
        txtMaKG.setEditable(false);
        txtDuKienToi.setEditable(false);
        spnThoiGianSuDung.setEnabled(false);
        txtThanhTien.setEditable(false);
        txtTrangThai.setEditable(false);
        txtGhiChu.setEditable(false);
        txtThanhTien.setBackground(new java.awt.Color(240, 240, 240));
        txtTrangThai.setBackground(new java.awt.Color(240, 240, 240));
        txtMaKG.setBackground(new java.awt.Color(240, 240, 240));
        txtDuKienToi.setBackground(new java.awt.Color(240, 240, 240));
        txtMaKH.setBackground(new java.awt.Color(240, 240, 240));
        txtGhiChu.setBackground(new java.awt.Color(250, 250, 250));
        lblMaKH.setText("Khách hàng");
        lblMaKG.setText("Không gian / Chi nhánh");
        lblGhiChu.setText("Yêu cầu thêm của khách hàng");
        btnNhanCho.setText("Quét mã QR để nhận chỗ");
        btnNhanCho.setBounds(20, 460, 360, 35);
        btnCapNhat.setVisible(false);

        tblDatCho.setModel(new DefaultTableModel(
                new Object[][] {},
                new String[] { "Mã đặt chỗ", "Khách hàng", "Chi nhánh", "Không gian", "Thời gian tới", "Giờ", "Trạng thái", "Thành tiền" }
        ) {
            final boolean[] canEdit = new boolean[] { false, false, false, false, false, false, false, false };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        btnTimKiem.addActionListener(evt -> loadData(txtTimKiem.getText()));
        btnLamMoi.addActionListener(evt -> {
            txtTimKiem.setText("");
            loadData("");
            clearDetail();
        });
        txtTimKiem.addActionListener(evt -> loadData(txtTimKiem.getText()));
        tblDatCho.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                int row = tblDatCho.getSelectedRow();
                if (row >= 0) {
                    int modelRow = tblDatCho.convertRowIndexToModel(row);
                    if (modelRow >= 0 && modelRow < currentList.size()) {
                        fillDetail(currentList.get(modelRow));
                    }
                }
            }
        });
        loadData("");
    }

    private void loadData(String keyword) {
        keyword = layMaDatChoTuQR(keyword);
        currentList = controller.layDanhSach(keyword);
        DefaultTableModel model = (DefaultTableModel) tblDatCho.getModel();
        model.setRowCount(0);
        for (DatChoTruocDTO dto : currentList) {
            model.addRow(new Object[] {
                dto.getMaDatCho(),
                dto.getHoTenKhachHang(),
                dto.getTenChiNhanh(),
                dto.getTenKhongGian(),
                formatDateTime(dto.getThoiGianDuKienToi()),
                dto.getKhoangThoiGianSuDung() == null ? "" : dto.getKhoangThoiGianSuDung(),
                dto.getTrangThaiDatTruoc(),
                dto.getThanhTien() == null ? "0" : moneyFormat.format(dto.getThanhTien())
            });
        }
    }

    private void fillDetail(DatChoTruocDTO dto) {
        txtMaDatCho.setText(dto.getMaDatCho());
        txtMaKH.setText((dto.getHoTenKhachHang() == null ? "" : dto.getHoTenKhachHang())
                + (dto.getSoDienThoaiKhachHang() == null || dto.getSoDienThoaiKhachHang().isBlank()
                ? "" : " · " + dto.getSoDienThoaiKhachHang()));
        txtMaKG.setText((dto.getMaKG() == null ? "" : dto.getMaKG())
                + (dto.getTenKhongGian() == null ? "" : " - " + dto.getTenKhongGian())
                + (dto.getTenChiNhanh() == null ? "" : " · " + dto.getTenChiNhanh()));
        txtDuKienToi.setText(formatDateTime(dto.getThoiGianDuKienToi()));
        spnThoiGianSuDung.setValue(dto.getKhoangThoiGianSuDung() == null ? 1 : dto.getKhoangThoiGianSuDung());
        txtThanhTien.setText(dto.getThanhTien() == null ? "0" : moneyFormat.format(dto.getThanhTien()));
        txtTrangThai.setText(dto.getTrangThaiDatTruoc() == null ? "" : dto.getTrangThaiDatTruoc());
        txtGhiChu.setText(dto.getGhiChu() == null || dto.getGhiChu().isBlank() ? "Không có yêu cầu thêm." : dto.getGhiChu());
        apDungKhoaTheoTrangThai(dto.getTrangThaiDatTruoc());
    }

    private void clearDetail() {
        txtMaDatCho.setText("");
        txtMaKH.setText("");
        txtMaKG.setText("");
        txtDuKienToi.setText("");
        spnThoiGianSuDung.setValue(1);
        txtThanhTien.setText("");
        txtTrangThai.setText("");
        txtGhiChu.setText("");
        btnChuyenKhoan.setEnabled(false);
        btnNhanCho.setEnabled(true);
    }

    private void apDungKhoaTheoTrangThai(String trangThai) {
        boolean choThanhToan = "Đang chờ thanh toán".equals(trangThai);
        btnChuyenKhoan.setEnabled(choThanhToan);
        btnNhanCho.setEnabled(true);
    }

    private void xacNhanChuyenKhoan() {
        if (txtMaDatCho.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một đặt chỗ từ danh sách.",
                    "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!"Đang chờ thanh toán".equals(txtTrangThai.getText())) {
            JOptionPane.showMessageDialog(this,
                    "Chỉ có thể xác nhận chuyển khoản khi đặt chỗ đang chờ thanh toán.",
                    "Không thể thực hiện", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this,
                "Đảm bảo đơn đặt trước đã chuyển khoản thanh toán thành công?",
                "Xác nhận chuyển khoản",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (choice != JOptionPane.YES_OPTION) {
            return;
        }

        String maDatCho = txtMaDatCho.getText().trim();
        ThongTinXacNhanDatChoDTO thongTin = controller.xacNhanThanhToanThuCong(maDatCho);
        if (thongTin != null) {
            JOptionPane.showMessageDialog(this,
                    "Đã xác nhận thanh toán!\nEmail QR nhận chỗ đã gửi tới: " + thongTin.getEmail(),
                    "Xác nhận thành công", JOptionPane.INFORMATION_MESSAGE);
            taiLaiVaChon(maDatCho);
            return;
        }
        JOptionPane.showMessageDialog(this,
                "Không thể xác nhận chuyển khoản.\n"
                        + "Đặt chỗ không ở trạng thái chờ thanh toán, đã có QR, hoặc đã được xác nhận trước đó.",
                "Thông báo", JOptionPane.WARNING_MESSAGE);
    }

    private void xacNhanNhanCho() {
        quetQrNhanCho();
    }

    private void quetQrNhanCho() {
        String qrRaw = QRCodeScannerUtil.quetHoacNhapThuCong(this);
        if (qrRaw == null || qrRaw.isBlank()) {
            return;
        }
        KetQuaNhanChoDTO ketQua = controller.xacNhanNhanChoBangQr(qrRaw, DangNhapController.getCurrentUser());
        if (ketQua.isThanhCong()) {
            JOptionPane.showMessageDialog(this,
                    dinhDangKetQuaNhanCho(ketQua),
                    "Nhận chỗ thành công", JOptionPane.INFORMATION_MESSAGE);
            if (ketQua.getMaDatCho() != null) {
                taiLaiVaChon(ketQua.getMaDatCho());
            } else {
                loadData(txtTimKiem.getText());
            }
            return;
        }
        JOptionPane.showMessageDialog(this,
                "Không thể nhận chỗ.\nLý do: " + ketQua.getThongBao(),
                "Thông báo", JOptionPane.WARNING_MESSAGE);
    }

    private String dinhDangKetQuaNhanCho(KetQuaNhanChoDTO ketQua) {
        StringBuilder builder = new StringBuilder();
        builder.append("Đã mở phiên: ").append(ketQua.getMaPhien() == null ? "" : ketQua.getMaPhien());
        if (ketQua.getTenKhachHang() != null && !ketQua.getTenKhachHang().isBlank()) {
            builder.append("\nKhách hàng: ").append(ketQua.getTenKhachHang());
        }
        if (ketQua.getTenChiNhanh() != null && !ketQua.getTenChiNhanh().isBlank()) {
            builder.append("\nChi nhánh: ").append(ketQua.getTenChiNhanh());
        }
        if (ketQua.getTenKhongGian() != null && !ketQua.getTenKhongGian().isBlank()) {
            builder.append("\nKhông gian: ").append(ketQua.getTenKhongGian());
        }
        if (ketQua.getThoiGianDuKienKetThuc() != null) {
            builder.append("\nDự kiến kết thúc: ").append(formatDateTime(ketQua.getThoiGianDuKienKetThuc()));
        }
        return builder.toString();
    }

    private void taiLaiVaChon(String maDatCho) {
        loadData(txtTimKiem.getText());
        for (int i = 0; i < currentList.size(); i++) {
            if (maDatCho.equals(currentList.get(i).getMaDatCho())) {
                tblDatCho.setRowSelectionInterval(i, i);
                fillDetail(currentList.get(i));
                break;
            }
        }
    }

    private void capNhatDatCho() {
        try {
            if (txtMaDatCho.getText().isBlank()) {
                throw new IllegalArgumentException("Vui lòng chọn một đặt chỗ từ danh sách.");
            }
            if (txtMaKH.getText().isBlank()) {
                throw new IllegalArgumentException("Mã khách hàng không được để trống.");
            }

            DatChoTruocDTO dto = new DatChoTruocDTO();
            dto.setMaDatCho(txtMaDatCho.getText().trim());
            dto.setMaKH(txtMaKH.getText().trim());
            dto.setGhiChu(txtGhiChu.getText().trim());

            if (controller.capNhatThongTinKhach(dto)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin khách thành công!");
                taiLaiVaChon(dto.getMaDatCho());
                return;
            }
            JOptionPane.showMessageDialog(this, "Không thể cập nhật thông tin khách.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, com.wms.util.ErrorMessageUtil.toUserMessage(ex), "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
        }
    }

    private String formatDateTime(Timestamp timestamp) {
        if (timestamp == null) {
            return "";
        }
        return com.wms.util.DateInputUtil.formatDateTime(timestamp.toLocalDateTime());
    }

    private String layMaDatChoTuQR(String value) {
        if (value == null) {
            return "";
        }
        java.util.regex.Matcher matcher = java.util.regex.Pattern
                .compile("\\bDC\\d{6}\\b", java.util.regex.Pattern.CASE_INSENSITIVE)
                .matcher(value);
        return matcher.find() ? matcher.group().toUpperCase() : value.trim();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChuyenKhoan;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnNhanCho;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblDuKienToi;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMaDatCho;
    private javax.swing.JLabel lblMaKG;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JLabel lblThoiGianSuDung;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JSpinner spnThoiGianSuDung;
    private javax.swing.JTable tblDatCho;
    private javax.swing.JTextField txtDuKienToi;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaDatCho;
    private javax.swing.JTextField txtMaKG;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
