/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyDatChoTruoc;

import com.wms.controller.TrangChuQuanLy.QuanLyDatChoTruoc.QuanLyDatChoTruocController;
import com.wms.model.TrangChuQuanLy.QuanLyDatChoTruoc.DatChoTruocDTO;
import com.wms.model.TrangChuQuanLy.QuanLyPhien.KetQuaNhanChoDTO;
import com.wms.model.TrangChuQuanLy.QuanLyPhien.ThongTinXacNhanDatChoDTO;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HuyLai
 */
public class QuanLyDatChoTruocForm extends javax.swing.JPanel {
    private final QuanLyDatChoTruocController controller = new QuanLyDatChoTruocController();
    private List<DatChoTruocDTO> currentList = new ArrayList<>();
    private final DecimalFormat moneyFormat = new DecimalFormat("#,###");
    private final DateTimeFormatter dateTimeFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    /**
     * Creates new form QuanLyDatChoTruocForm
     */
    public QuanLyDatChoTruocForm() {
        initComponents();
        initLogic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatCho = new javax.swing.JTable();
        btnLamMoi = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaDatCho = new javax.swing.JLabel();
        txtMaDatCho = new javax.swing.JTextField();
        lblMaKH = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        lblMaKG = new javax.swing.JLabel();
        txtMaKG = new javax.swing.JTextField();
        lblDuKienToi = new javax.swing.JLabel();
        txtDuKienToi = new javax.swing.JTextField();
        lblThoiGianSuDung = new javax.swing.JLabel();
        spnThoiGianSuDung = new javax.swing.JSpinner();
        lblThanhTien = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        lblGhiChu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnCapNhat = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1050, 640));
        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ ĐẶT CHỖ TRƯỚC");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH ĐẶT CHỖ");
        pnLeft.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 250, 30);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm (Mã ĐC/Mã KH):");
        pnLeft.add(lblTimKiem);
        lblTimKiem.setBounds(20, 60, 140, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtTimKiem);
        txtTimKiem.setBounds(160, 60, 220, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnLeft.add(btnTimKiem);
        btnTimKiem.setBounds(390, 60, 76, 35);

        tblDatCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Đặt Chỗ", "Khách Hàng", "Không Gian", "Dự Kiến Tới", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatCho.setRowHeight(35);
        tblDatCho.setSelectionBackground(new java.awt.Color(235, 94, 141));
        jScrollPane1.setViewportView(tblDatCho);

        pnLeft.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 550, 410);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(235, 94, 141));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnLeft.add(btnLamMoi);
        btnLamMoi.setBounds(470, 60, 100, 35);

        pnMain.add(pnLeft);
        pnLeft.setBounds(450, 70, 590, 540);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("THÔNG TIN CHI TIẾT");
        pnRight.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 200, 30);

        lblMaDatCho.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaDatCho.setForeground(new java.awt.Color(35, 30, 48));
        lblMaDatCho.setText("Mã đặt chỗ");
        pnRight.add(lblMaDatCho);
        lblMaDatCho.setBounds(20, 55, 360, 20);

        txtMaDatCho.setEditable(false);
        txtMaDatCho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaDatCho.setBackground(new java.awt.Color(240, 240, 240));
        pnRight.add(txtMaDatCho);
        txtMaDatCho.setBounds(20, 75, 360, 35);

        lblMaKH.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaKH.setForeground(new java.awt.Color(35, 30, 48));
        lblMaKH.setText("Mã Khách Hàng (*)");
        pnRight.add(lblMaKH);
        lblMaKH.setBounds(20, 120, 170, 20);

        txtMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtMaKH);
        txtMaKH.setBounds(20, 140, 170, 35);

        lblMaKG.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaKG.setForeground(new java.awt.Color(35, 30, 48));
        lblMaKG.setText("Mã Không Gian (*)");
        pnRight.add(lblMaKG);
        lblMaKG.setBounds(210, 120, 170, 20);

        txtMaKG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtMaKG);
        txtMaKG.setBounds(210, 140, 170, 35);

        lblDuKienToi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDuKienToi.setForeground(new java.awt.Color(35, 30, 48));
        lblDuKienToi.setText("Dự kiến tới (YYYY-MM-DD HH:mm)");
        pnRight.add(lblDuKienToi);
        lblDuKienToi.setBounds(20, 185, 220, 20);

        txtDuKienToi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtDuKienToi);
        txtDuKienToi.setBounds(20, 205, 220, 35);

        lblThoiGianSuDung.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblThoiGianSuDung.setForeground(new java.awt.Color(35, 30, 48));
        lblThoiGianSuDung.setText("Số giờ SD (*)");
        pnRight.add(lblThoiGianSuDung);
        lblThoiGianSuDung.setBounds(260, 185, 120, 20);

        spnThoiGianSuDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnThoiGianSuDung.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        pnRight.add(spnThoiGianSuDung);
        spnThoiGianSuDung.setBounds(260, 205, 120, 35);

        lblThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblThanhTien.setForeground(new java.awt.Color(35, 30, 48));
        lblThanhTien.setText("Thành tiền (VNĐ)");
        pnRight.add(lblThanhTien);
        lblThanhTien.setBounds(20, 250, 360, 20);

        txtThanhTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtThanhTien.setForeground(new java.awt.Color(51, 153, 0));
        pnRight.add(txtThanhTien);
        txtThanhTien.setBounds(20, 270, 360, 35);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái đặt chỗ");
        pnRight.add(lblTrangThai);
        lblTrangThai.setBounds(20, 315, 360, 20);

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang chờ thanh toán", "Đã thanh toán thành công", "Thanh toán không thành công", "Đã sử dụng" }));
        pnRight.add(cbxTrangThai);
        cbxTrangThai.setBounds(20, 335, 360, 35);

        lblGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(35, 30, 48));
        lblGhiChu.setText("Ghi chú / Yêu cầu thêm");
        pnRight.add(lblGhiChu);
        lblGhiChu.setBounds(20, 380, 360, 20);

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtGhiChu.setRows(2);
        jScrollPane2.setViewportView(txtGhiChu);

        pnRight.add(jScrollPane2);
        jScrollPane2.setBounds(20, 400, 360, 45);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnRight.add(btnCapNhat);
        btnCapNhat.setBounds(20, 460, 360, 35);

        pnMain.add(pnRight);
        pnRight.setBounds(20, 70, 400, 540);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void initLogic() {
        txtMaDatCho.setEditable(false);
        btnTimKiem.addActionListener(evt -> loadData(txtTimKiem.getText()));
        btnLamMoi.addActionListener(evt -> {
            txtTimKiem.setText("");
            loadData("");
            clearDetail();
        });
        btnCapNhat.addActionListener(evt -> capNhatDatCho());
        txtTimKiem.addActionListener(evt -> loadData(txtTimKiem.getText()));
        tblDatCho.getSelectionModel().addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                int row = tblDatCho.getSelectedRow();
                if (row >= 0) {
                    int modelRow = tblDatCho.convertRowIndexToModel(row);
                    if (modelRow >= 0 && modelRow < currentList.size()) {
                        fillDetail(currentList.get(modelRow));
                    }
                }
            }
        });
        loadData("");
    }

    private void loadData(String keyword) {
        keyword = layMaDatChoTuQR(keyword);
        currentList = controller.layDanhSach(keyword);
        DefaultTableModel model = (DefaultTableModel) tblDatCho.getModel();
        model.setRowCount(0);
        for (DatChoTruocDTO dto : currentList) {
            model.addRow(new Object[] {
                dto.getMaDatCho(),
                dto.getHoTenKhachHang(),
                dto.getTenKhongGian(),
                formatDateTime(dto.getThoiGianDuKienToi()),
                dto.getTrangThaiDatTruoc()
            });
        }
    }

    private void fillDetail(DatChoTruocDTO dto) {
        txtMaDatCho.setText(dto.getMaDatCho());
        txtMaKH.setText(dto.getMaKH());
        txtMaKG.setText(dto.getMaKG());
        txtDuKienToi.setText(formatDateTime(dto.getThoiGianDuKienToi()));
        spnThoiGianSuDung.setValue(dto.getKhoangThoiGianSuDung() == null ? 1 : dto.getKhoangThoiGianSuDung());
        txtThanhTien.setText(dto.getThanhTien() == null ? "0" : moneyFormat.format(dto.getThanhTien()));
        cbxTrangThai.setSelectedItem(dto.getTrangThaiDatTruoc());
        txtGhiChu.setText(dto.getGhiChu() == null ? "" : dto.getGhiChu());
    }

    private void clearDetail() {
        txtMaDatCho.setText("");
        txtMaKH.setText("");
        txtMaKG.setText("");
        txtDuKienToi.setText("");
        spnThoiGianSuDung.setValue(1);
        txtThanhTien.setText("");
        cbxTrangThai.setSelectedIndex(0);
        txtGhiChu.setText("");
    }

    private void capNhatDatCho() {
        try {
            DatChoTruocDTO dto = readForm();
            String trangThaiMoi = String.valueOf(cbxTrangThai.getSelectedItem());

            if ("Đã sử dụng".equals(trangThaiMoi)) {
                KetQuaNhanChoDTO ketQua = controller.moPhienTuDatChoThuCong(dto);
                if (ketQua.isThanhCong()) {
                    JOptionPane.showMessageDialog(this,
                            "Đã tạo phiên mới: " + ketQua.getMaPhien() + "\nKhách có thể sử dụng ngay.",
                            "Tạo phiên thành công", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Không thể tạo phiên thủ công.\nLưu ý: " + ketQua.getThongBao(),
                            "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
                loadData(txtTimKiem.getText());
                return;
            }

            if ("Đã thanh toán thành công".equals(trangThaiMoi)) {
                ThongTinXacNhanDatChoDTO thongTin = controller.xacNhanThanhToanThuCong(dto.getMaDatCho());
                if (thongTin != null) {
                    JOptionPane.showMessageDialog(this,
                            "Đã xác nhận thanh toán!\nEmail QR nhận chỗ đã gửi tới: " + thongTin.getEmail(),
                            "Xác nhận thành công", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Không thể xác nhận thanh toán thủ công.\n"
                                    + "Đặt chỗ không ở trạng thái chờ thanh toán, đã có QR, hoặc đã được xác nhận trước đó.",
                            "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
                loadData(txtTimKiem.getText());
                return;
            }

            if (controller.capNhat(dto)) {
                JOptionPane.showMessageDialog(this, "Cập nhật đặt chỗ thành công!");
                loadData(txtTimKiem.getText());
                return;
            }
            JOptionPane.showMessageDialog(this, "Không thể cập nhật đặt chỗ.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
        }
    }

    private DatChoTruocDTO readForm() {
        if (txtMaDatCho.getText().isBlank()) {
            throw new IllegalArgumentException("Vui lòng chọn một đặt chỗ từ danh sách.");
        }
        if (txtMaKH.getText().isBlank() || txtMaKG.getText().isBlank()) {
            throw new IllegalArgumentException("Mã khách hàng và mã không gian không được để trống.");
        }
        DatChoTruocDTO dto = new DatChoTruocDTO();
        dto.setMaDatCho(txtMaDatCho.getText().trim());
        dto.setMaKH(txtMaKH.getText().trim());
        dto.setMaKG(txtMaKG.getText().trim());
        dto.setThoiGianDuKienToi(parseTimestamp(txtDuKienToi.getText()));
        dto.setKhoangThoiGianSuDung((Integer) spnThoiGianSuDung.getValue());
        dto.setThanhTien(parseMoney(txtThanhTien.getText()));
        dto.setTrangThaiDatTruoc(String.valueOf(cbxTrangThai.getSelectedItem()));
        dto.setGhiChu(txtGhiChu.getText().trim());
        return dto;
    }

    private Timestamp parseTimestamp(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        String normalized = value.trim();
        try {
            return Timestamp.valueOf(LocalDateTime.parse(normalized, dateTimeFormat));
        } catch (DateTimeParseException ignored) {
            try {
                return Timestamp.valueOf(normalized);
            } catch (IllegalArgumentException ex) {
                throw new IllegalArgumentException("Thời gian dự kiến phải theo dạng YYYY-MM-DD HH:mm.");
            }
        }
    }

    private BigDecimal parseMoney(String value) {
        if (value == null || value.isBlank()) {
            return BigDecimal.ZERO;
        }
        String normalized = value.replace(",", "").replace(".", "").replace("VNĐ", "").trim();
        try {
            return new BigDecimal(normalized);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Thành tiền phải là số hợp lệ.");
        }
    }

    private String formatDateTime(Timestamp timestamp) {
        if (timestamp == null) {
            return "";
        }
        return dateTimeFormat.format(timestamp.toLocalDateTime());
    }

    private String layMaDatChoTuQR(String value) {
        if (value == null) {
            return "";
        }
        java.util.regex.Matcher matcher = java.util.regex.Pattern
                .compile("\\bDC\\d{6}\\b", java.util.regex.Pattern.CASE_INSENSITIVE)
                .matcher(value);
        return matcher.find() ? matcher.group().toUpperCase() : value.trim();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblDuKienToi;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMaDatCho;
    private javax.swing.JLabel lblMaKG;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JLabel lblThoiGianSuDung;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JSpinner spnThoiGianSuDung;
    private javax.swing.JTable tblDatCho;
    private javax.swing.JTextField txtDuKienToi;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaDatCho;
    private javax.swing.JTextField txtMaKG;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
