CREATE TABLE KHONGGIAN (
    MaKG VARCHAR2(50) PRIMARY KEY,
    TenKG VARCHAR2(100),
    TrangThaiKG VARCHAR2(50),
    ViTri VARCHAR2(100),
    MaLoaiKG VARCHAR2(50),
    MaCN VARCHAR2(50)
    ToaDoX NUMBER DEFAULT 0,
    ToaDoY NUMBER DEFAULT 0,
    ChieuDai NUMBER DEFAULT 0,
    ChieuRong NUMBER DEFAULT 0
);
