CREATE TABLE Spaces (
    space_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    branch_id NUMBER NOT NULL,
    type_id NUMBER NOT NULL,   
    current_status VARCHAR2(20) DEFAULT 'AVAILABLE', 
    qr_code_token VARCHAR2(255) UNIQUE, 
    is_active NUMBER(1) DEFAULT 1, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);