package com.wms.view.TrangChuQuanLy.QuanLyNhanVien;

import com.wms.controller.TrangChuQuanLy.QuanLyNhanVien.QuanLyHangTVController;
import com.wms.model.TrangChuQuanLy.QuanLyNhanVien.HangThanhVienDTO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class QuanLyHangTVForm extends javax.swing.JDialog {
    
    private final QuanLyHangTVController controller = new QuanLyHangTVController();
    private List<HangThanhVienDTO> hangList;
    private HangThanhVienDTO selectedHang;

    public QuanLyHangTVForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadDataToTable();
        pack();
        setLocationRelativeTo(parent);
        com.wms.util.TienIchFormQuanLy.apDung(this);
    }

    private void loadDataToTable() {
        hangList = controller.layDanhSachHang();
        fillTable();
    }

    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblHangTV.getModel();
        model.setRowCount(0);
        if (hangList != null) {
            for (HangThanhVienDTO dto : hangList) {
                model.addRow(new Object[]{
                    dto.getMaHangThanhVien(), 
                    dto.getTenHangThanhVien(), 
                    dto.getPhanTramTienGiam() + "%", 
                    String.format("%,.0f", dto.getTongChiTieuToiThieu())
                });
            }
        }
    }

    private void lamMoiForm() {
        txtMaHang.setText("");
        cbxTenHang.setSelectedIndex(0);
        spnPhanTram.setValue(0.0);
        txtChiTieu.setText("");
        selectedHang = null;
        tblHangTV.clearSelection();
    }

    private HangThanhVienDTO getFormData() throws Exception {
        HangThanhVienDTO dto = (selectedHang != null) ? selectedHang : new HangThanhVienDTO();
        dto.setMaHangThanhVien(txtMaHang.getText().trim());
        dto.setTenHangThanhVien(cbxTenHang.getSelectedItem().toString());
        dto.setPhanTramTienGiam(Double.valueOf(spnPhanTram.getValue().toString()));
        dto.setTongChiTieuToiThieu(Double.parseDouble(txtChiTieu.getText().trim().replace(",", "")));
        return dto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaHang = new javax.swing.JLabel();
        txtMaHang = new javax.swing.JTextField();
        lblTenHang = new javax.swing.JLabel();
        cbxTenHang = new javax.swing.JComboBox<>();
        lblPhanTram = new javax.swing.JLabel();
        spnPhanTram = new javax.swing.JSpinner();
        lblChiTieu = new javax.swing.JLabel();
        txtChiTieu = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHangTV = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý Hạng Thành Viên");
        setModal(true);
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(850, 550));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ HẠNG THÀNH VIÊN");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 850, 50);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 850, 50);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("THÔNG TIN HẠNG");
        pnLeft.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 260, 30);

        lblMaHang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaHang.setForeground(new java.awt.Color(35, 30, 48));
        lblMaHang.setText("Mã Hạng (*)");
        pnLeft.add(lblMaHang);
        lblMaHang.setBounds(20, 60, 260, 20);

        txtMaHang.setEditable(false);
        txtMaHang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtMaHang);
        txtMaHang.setBounds(20, 80, 260, 35);

        lblTenHang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenHang.setForeground(new java.awt.Color(35, 30, 48));
        lblTenHang.setText("Tên Hạng (*)");
        pnLeft.add(lblTenHang);
        lblTenHang.setBounds(20, 130, 260, 20);

        cbxTenHang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTenHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không có", "Đồng", "Bạc", "Vàng", "Kim cương" }));
        cbxTenHang.addActionListener(this::cbxTenHangActionPerformed);
        pnLeft.add(cbxTenHang);
        cbxTenHang.setBounds(20, 150, 260, 35);

        lblPhanTram.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPhanTram.setForeground(new java.awt.Color(35, 30, 48));
        lblPhanTram.setText("% Giảm Giá (0 - 100)");
        pnLeft.add(lblPhanTram);
        lblPhanTram.setBounds(20, 200, 260, 20);

        spnPhanTram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnPhanTram.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.5d));
        pnLeft.add(spnPhanTram);
        spnPhanTram.setBounds(20, 220, 260, 35);

        lblChiTieu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChiTieu.setForeground(new java.awt.Color(35, 30, 48));
        lblChiTieu.setText("Chi Tiêu Tối Thiểu (VNĐ)");
        pnLeft.add(lblChiTieu);
        lblChiTieu.setBounds(20, 270, 260, 20);

        txtChiTieu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtChiTieu);
        txtChiTieu.setBounds(20, 290, 260, 35);

        btnSua.setBackground(new java.awt.Color(235, 94, 141));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Cập Nhật");
        btnSua.addActionListener(this::btnSuaActionPerformed);
        pnLeft.add(btnSua);
        btnSua.setBounds(20, 340, 125, 35);

        btnLamMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);
        pnLeft.add(btnLamMoi);
        btnLamMoi.setBounds(155, 340, 125, 35);

        pnMain.add(pnLeft);
        pnLeft.setBounds(20, 70, 300, 450);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH HẠNG THÀNH VIÊN");
        pnRight.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 300, 30);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(txtTimKiem);
        txtTimKiem.setBounds(20, 60, 350, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnRight.add(btnTimKiem);
        btnTimKiem.setBounds(380, 60, 90, 35);

        tblHangTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hạng", "Tên Hạng", "% Giảm Giá", "Chi Tiêu Tối Thiểu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHangTV.setRowHeight(30);
        tblHangTV.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblHangTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangTVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHangTV);

        pnRight.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 450, 320);

        pnMain.add(pnRight);
        pnRight.setBounds(340, 70, 490, 450);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedHang == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hạng thành viên từ danh sách!");
            return;
        }
        try {
            double discount = Double.parseDouble(spnPhanTram.getValue().toString());
            controller.capNhatChinhSachGiamGia(selectedHang.getMaHangThanhVien(), discount);
            JOptionPane.showMessageDialog(this, "Cập nhật % giảm giá thành công!");
            loadDataToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {
        lamMoiForm();
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void cbxTenHangActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void tblHangTVMouseClicked(java.awt.event.MouseEvent evt) {
        int idx = tblHangTV.getSelectedRow();
        if (idx >= 0 && idx < hangList.size()) {
            selectedHang = hangList.get(idx);
            txtMaHang.setText(selectedHang.getMaHangThanhVien());
            cbxTenHang.setSelectedItem(selectedHang.getTenHangThanhVien());
            spnPhanTram.setValue(selectedHang.getPhanTramTienGiam() != null ? selectedHang.getPhanTramTienGiam() : 0.0);
            txtChiTieu.setText(String.format("%.0f", selectedHang.getTongChiTieuToiThieu()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxTenHang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChiTieu;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMaHang;
    private javax.swing.JLabel lblPhanTram;
    private javax.swing.JLabel lblTenHang;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JSpinner spnPhanTram;
    private javax.swing.JTable tblHangTV;
    private javax.swing.JTextField txtChiTieu;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
