CREATE OR REPLACE TRIGGER TRG_CapNhatSLDaDungPhieuGiamGia
AFTER INSERT ON HOADON
FOR EACH ROW
WHEN (NEW.MaPGG IS NOT NULL AND NEW.TrangThaiThanhToan = 'Đã thanh toán thành công')
BEGIN
    UPDATE PHIEUGIAMGIA
    SET SLDaDung = NVL(SLDaDung, 0) + 1
    WHERE MaPGG = :NEW.MaPGG;
END TRG_CapNhatSLDaDungPhieuGiamGia;
/
