/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyHoiVien;

/**
 *
 * @author HuyLai
 */
public class QuanLyHoiVienForm extends javax.swing.JPanel {
    private com.wms.controller.QuanLyHoiVienController controller = new com.wms.controller.QuanLyHoiVienController();
    private java.util.List<com.wms.model.HoiVienDTO> hoiVienList;
    private com.wms.model.HoiVienDTO selectedHoiVien;
    private String currentAvatarPath = null;

    /**
     * Creates new form QuanLyHoiVienForm
     */
    public QuanLyHoiVienForm() {
        initComponents();
        loadDataToTable();
    }

    private void loadDataToTable() {
        hoiVienList = controller.layDanhSachHoiVien();
        fillTable();
    }

    private void fillTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblHoiVien.getModel();
        model.setRowCount(0);
        for (com.wms.model.HoiVienDTO dto : hoiVienList) {
            if (dto.getNgaySinh() != null) {
                new java.text.SimpleDateFormat("dd/MM/yyyy").format(dto.getNgaySinh());
            }
            model.addRow(new Object[] {
                    dto.getMaKH(), dto.getHoTen(), dto.getSdt(), dto.getEmail(), dto.getTongChiTieu(),
                    dto.getHangThanhVien(), dto.getTrangThai()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblAnhDaiDien = new javax.swing.JLabel();
        btnDoiAnh = new javax.swing.JButton();
        lblMaHV = new javax.swing.JLabel();
        txtMaHV = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        cbxGioiTinh = new javax.swing.JComboBox<>();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lblTongChiTieu = new javax.swing.JLabel();
        txtTongChiTieu = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        lblHangTV = new javax.swing.JLabel();
        cbxHangTV = new javax.swing.JComboBox<>();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnQuanLyHang = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoiVien = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ HỘI VIÊN (KHÁCH HÀNG)");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        lblAnhDaiDien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhDaiDien.setText("[Ảnh 3x4]");
        lblAnhDaiDien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnMain.add(lblAnhDaiDien);
        lblAnhDaiDien.setBounds(20, 70, 130, 160);

        btnDoiAnh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoiAnh.setForeground(new java.awt.Color(235, 94, 141));
        btnDoiAnh.setText("Đổi ảnh");
        btnDoiAnh.addActionListener(this::btnDoiAnhActionPerformed);
        pnMain.add(btnDoiAnh);
        btnDoiAnh.setBounds(20, 240, 130, 30);

        lblMaHV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaHV.setForeground(new java.awt.Color(35, 30, 48));
        lblMaHV.setText("Mã Hội viên");
        pnMain.add(lblMaHV);
        lblMaHV.setBounds(170, 70, 100, 18);

        txtMaHV.setEditable(false);
        txtMaHV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaHV.setBackground(new java.awt.Color(240, 240, 240));
        pnMain.add(txtMaHV);
        txtMaHV.setBounds(170, 90, 100, 30);

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(35, 30, 48));
        lblGioiTinh.setText("Giới tính");
        pnMain.add(lblGioiTinh);
        lblGioiTinh.setBounds(290, 70, 100, 18);

        cbxGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        pnMain.add(cbxGioiTinh);
        cbxGioiTinh.setBounds(290, 90, 100, 30);

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(35, 30, 48));
        lblHoTen.setText("Họ và tên (*)");
        pnMain.add(lblHoTen);
        lblHoTen.setBounds(170, 130, 220, 18);

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtHoTen);
        txtHoTen.setBounds(170, 150, 220, 30);

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(35, 30, 48));
        lblSDT.setText("Số điện thoại (*)");
        pnMain.add(lblSDT);
        lblSDT.setBounds(170, 190, 220, 18);

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtSDT);
        txtSDT.setBounds(170, 210, 220, 30);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(35, 30, 48));
        lblEmail.setText("Email (*)");
        pnMain.add(lblEmail);
        lblEmail.setBounds(20, 280, 170, 18);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtEmail);
        txtEmail.setBounds(20, 300, 170, 30);

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(35, 30, 48));
        lblNgaySinh.setText("Ngày sinh (dd/MM/yyyy)");
        pnMain.add(lblNgaySinh);
        lblNgaySinh.setBounds(220, 280, 170, 18);

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtNgaySinh);
        txtNgaySinh.setBounds(220, 300, 170, 30);

        lblTongChiTieu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTongChiTieu.setForeground(new java.awt.Color(35, 30, 48));
        lblTongChiTieu.setText("Tổng chi tiêu (VNĐ)");
        pnMain.add(lblTongChiTieu);
        lblTongChiTieu.setBounds(20, 340, 170, 18);

        txtTongChiTieu.setEditable(false);
        txtTongChiTieu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTongChiTieu.setBackground(new java.awt.Color(240, 240, 240));
        pnMain.add(txtTongChiTieu);
        txtTongChiTieu.setBounds(20, 360, 170, 30);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái hoạt động");
        pnMain.add(lblTrangThai);
        lblTrangThai.setBounds(220, 340, 170, 18);

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Bị khóa" }));
        pnMain.add(cbxTrangThai);
        cbxTrangThai.setBounds(220, 360, 170, 30);

        lblHangTV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHangTV.setForeground(new java.awt.Color(35, 30, 48));
        lblHangTV.setText("Hạng thành viên hiện tại (*)");
        pnMain.add(lblHangTV);
        lblHangTV.setBounds(20, 400, 370, 18);

        cbxHangTV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxHangTV.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Không có", "Đồng", "Bạc", "Vàng", "Kim cương" }));
        pnMain.add(cbxHangTV);
        cbxHangTV.setBounds(20, 420, 170, 40);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnMain.add(btnThemMoi);
        btnThemMoi.setBounds(220, 420, 170, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnMain.add(btnCapNhat);
        btnCapNhat.setBounds(220, 470, 170, 40);

        btnQuanLyHang.setBackground(new java.awt.Color(35, 30, 48));
        btnQuanLyHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyHang.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyHang.setText("Q.lý Hạng TV");
        btnQuanLyHang.addActionListener(this::btnQuanLyHangActionPerformed);
        pnMain.add(btnQuanLyHang);
        btnQuanLyHang.setBounds(20, 520, 170, 40);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnMain.add(btnHuy);
        btnHuy.setBounds(220, 520, 170, 40);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm (Tên/SĐT):");
        pnMain.add(lblTimKiem);
        lblTimKiem.setBounds(420, 80, 150, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTimKiem);
        txtTimKiem.setBounds(575, 80, 325, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnMain.add(btnTimKiem);
        btnTimKiem.setBounds(920, 80, 100, 35);

        tblHoiVien.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã HV", "Họ và tên", "SĐT", "Email", "Tổng chi tiêu", "Hạng TV", "Trạng thái"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblHoiVien.setRowHeight(30);
        tblHoiVien.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblHoiVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoiVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoiVien);

        pnMain.add(jScrollPane1);
        jScrollPane1.setBounds(420, 130, 600, 480);

        btnXoa.setBackground(new java.awt.Color(235, 94, 141));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(this::btnXoaActionPerformed);
        pnMain.add(btnXoa);
        btnXoa.setBounds(20, 470, 170, 40);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyHangActionPerformed(java.awt.event.ActionEvent evt) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        com.wms.view.TrangChuQuanLy.QuanLyHoiVien.QuanLyHangThanhVien.QuanLyHangTVForm form = new com.wms.view.TrangChuQuanLy.QuanLyHoiVien.QuanLyHangThanhVien.QuanLyHangTVForm(
                (java.awt.Frame) parentWindow, true);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }

    private void btnDoiAnhActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "jpeg"));
        if (fileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            currentAvatarPath = file.getAbsolutePath();
            lblAnhDaiDien.setIcon(
                    new javax.swing.ImageIcon(new javax.swing.ImageIcon(currentAvatarPath).getImage().getScaledInstance(
                            lblAnhDaiDien.getWidth(), lblAnhDaiDien.getHeight(), java.awt.Image.SCALE_SMOOTH)));
            lblAnhDaiDien.setText("");
        }
    }

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtEmailActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtSDTActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtHoTenActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtTimKiemActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {
        com.wms.model.HoiVienDTO newHoiVien = new com.wms.model.HoiVienDTO();
        newHoiVien.setHoTen(txtHoTen.getText().trim());
        newHoiVien.setSdt(txtSDT.getText().trim());
        newHoiVien.setEmail(txtEmail.getText().trim());
        newHoiVien.setAnhDaiDien(currentAvatarPath);
        newHoiVien.setGioiTinh((String) cbxGioiTinh.getSelectedItem());
        newHoiVien.setTrangThai((String) cbxTrangThai.getSelectedItem());
        newHoiVien.setHangThanhVien((String) cbxHangTV.getSelectedItem());

        try {
            String dateStr = txtNgaySinh.getText().trim();
            if (!dateStr.isEmpty()) {
                java.util.Date parsed = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(dateStr);
                newHoiVien.setNgaySinh(new java.sql.Date(parsed.getTime()));
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ (dd/MM/yyyy)!", "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            controller.themMoiHoiVien(newHoiVien);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Thêm mới thành công!\nTài khoản đăng nhập: SĐT hoặc Email\nMật khẩu mặc định: 123456");
            loadDataToTable();
            btnHuyActionPerformed(null);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm mới thất bại!\nChi tiết: " + ex.getMessage(), "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedHoiVien == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một hội viên để cập nhật!", "Thông báo",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        selectedHoiVien.setHoTen(txtHoTen.getText().trim());
        selectedHoiVien.setSdt(txtSDT.getText().trim());
        selectedHoiVien.setEmail(txtEmail.getText().trim());
        selectedHoiVien.setAnhDaiDien(currentAvatarPath);
        selectedHoiVien.setGioiTinh((String) cbxGioiTinh.getSelectedItem());
        selectedHoiVien.setTrangThai((String) cbxTrangThai.getSelectedItem());
        selectedHoiVien.setHangThanhVien((String) cbxHangTV.getSelectedItem());
        try {
            String dateStr = txtNgaySinh.getText().trim();
            if (!dateStr.isEmpty()) {
                java.util.Date parsed = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(dateStr);
                selectedHoiVien.setNgaySinh(new java.sql.Date(parsed.getTime()));
            } else {
                selectedHoiVien.setNgaySinh(null);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ (dd/MM/yyyy)!", "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            controller.capNhatHoiVien(selectedHoiVien);
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadDataToTable();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thất bại!\nChi tiết: " + ex.getMessage(), "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedHoiVien == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một hội viên để xóa!", "Thông báo",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa hội viên này?",
                "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                controller.xoaHoiVien(selectedHoiVien.getMaKH(), selectedHoiVien.getMaND());
                javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
                btnHuyActionPerformed(null);
                loadDataToTable();
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!\nChi tiết: " + ex.getMessage(), "Lỗi",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        selectedHoiVien = null;
        txtHoTen.setText("");
        txtSDT.setText("");
        txtEmail.setText("");
        txtNgaySinh.setText("");
        cbxGioiTinh.setSelectedIndex(0);
        cbxTrangThai.setSelectedIndex(0);
        cbxHangTV.setSelectedIndex(0);
        tblHoiVien.clearSelection();
        currentAvatarPath = null;
        lblAnhDaiDien.setIcon(null);
        lblAnhDaiDien.setText("[Ảnh 3x4]");
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        hoiVienList = controller.timKiemHoiVien(txtTimKiem.getText().trim());
        fillTable();
    }

    private void tblHoiVienMouseClicked(java.awt.event.MouseEvent evt) {
        int index = tblHoiVien.getSelectedRow();
        if (index >= 0 && index < hoiVienList.size()) {
            selectedHoiVien = hoiVienList.get(index);
            txtHoTen.setText(selectedHoiVien.getHoTen());
            txtSDT.setText(selectedHoiVien.getSdt());
            txtEmail.setText(selectedHoiVien.getEmail());
            if (selectedHoiVien.getNgaySinh() != null) {
                txtNgaySinh.setText(new java.text.SimpleDateFormat("dd/MM/yyyy").format(selectedHoiVien.getNgaySinh()));
            } else {
                txtNgaySinh.setText("");
            }
            if (selectedHoiVien.getHangThanhVien() != null) {
                cbxHangTV.setSelectedItem(selectedHoiVien.getHangThanhVien());
            }
            if (selectedHoiVien.getGioiTinh() != null) {
                cbxGioiTinh.setSelectedItem(selectedHoiVien.getGioiTinh());
            }
            if (selectedHoiVien.getTrangThai() != null) {
                cbxTrangThai.setSelectedItem(selectedHoiVien.getTrangThai());
            }
            txtTongChiTieu.setText(
                    selectedHoiVien.getTongChiTieu() != null ? String.valueOf(selectedHoiVien.getTongChiTieu()) : "0");
            txtMaHV.setText(selectedHoiVien.getMaKH());

            if (selectedHoiVien.getAnhDaiDien() != null && !selectedHoiVien.getAnhDaiDien().isEmpty()) {
                currentAvatarPath = selectedHoiVien.getAnhDaiDien();
                try {
                    lblAnhDaiDien.setIcon(new javax.swing.ImageIcon(
                            new javax.swing.ImageIcon(currentAvatarPath).getImage().getScaledInstance(
                                    lblAnhDaiDien.getWidth(), lblAnhDaiDien.getHeight(), java.awt.Image.SCALE_SMOOTH)));
                    lblAnhDaiDien.setText("");
                } catch (Exception e) {
                    lblAnhDaiDien.setIcon(null);
                    lblAnhDaiDien.setText("[Lỗi ảnh]");
                }
            } else {
                currentAvatarPath = null;
                lblAnhDaiDien.setIcon(null);
                lblAnhDaiDien.setText("[Ảnh 3x4]");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDoiAnh;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnQuanLyHang;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxGioiTinh;
    private javax.swing.JComboBox<String> cbxHangTV;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnhDaiDien;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHangTV;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMaHV;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTongChiTieu;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblHoiVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaHV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTongChiTieu;
    // End of variables declaration//GEN-END:variables
}
