/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyHoiVien;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyHoiVienForm extends javax.swing.JPanel {
    private com.wms.controller.QuanLyHoiVienController controller = new com.wms.controller.QuanLyHoiVienController();
    private java.util.List<com.wms.model.NhanSu_KhachHang.HoiVienDTO> hoiVienList;
    private com.wms.model.NhanSu_KhachHang.HoiVienDTO selectedHoiVien;
    /**
     * Creates new form QuanLyHoiVienForm
     */
    public QuanLyHoiVienForm() {
        initComponents();
    }
     private void loadDataToTable() {
        hoiVienList = controller.layDanhSachHoiVien();
        fillTable();
    }

    private void fillTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblHoiVien.getModel();
        model.setRowCount(0);
        for (com.wms.model.NhanSu_KhachHang.HoiVienDTO dto : hoiVienList) {
            if (dto.getNgaySinh() != null) {
                new java.text.SimpleDateFormat("dd/MM/yyyy").format(dto.getNgaySinh());
            }
            model.addRow(new Object[]{
                dto.getMaKH(), dto.getHoTen(), dto.getSdt(), dto.getEmail(), dto.getHangThanhVien()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lblHang = new javax.swing.JLabel();
        cbxHangThanhVien = new javax.swing.JComboBox<>();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoiVien = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 550));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ HỘI VIÊN");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(35, 30, 48));
        lblHoTen.setText("Họ và tên (*)");
        pnMain.add(lblHoTen);
        lblHoTen.setBounds(30, 80, 280, 18);

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtHoTen.addActionListener(this::txtHoTenActionPerformed);
        pnMain.add(txtHoTen);
        txtHoTen.setBounds(30, 100, 280, 35);

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(35, 30, 48));
        lblSDT.setText("Số điện thoại (*)");
        pnMain.add(lblSDT);
        lblSDT.setBounds(30, 150, 280, 18);

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSDT.addActionListener(this::txtSDTActionPerformed);
        pnMain.add(txtSDT);
        txtSDT.setBounds(30, 170, 280, 35);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(35, 30, 48));
        lblEmail.setText("Email (*)");
        pnMain.add(lblEmail);
        lblEmail.setBounds(30, 220, 280, 18);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.addActionListener(this::txtEmailActionPerformed);
        pnMain.add(txtEmail);
        txtEmail.setBounds(30, 240, 280, 35);

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(35, 30, 48));
        lblNgaySinh.setText("Ngày sinh (dd/MM/yyyy)");
        pnMain.add(lblNgaySinh);
        lblNgaySinh.setBounds(30, 290, 280, 18);

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNgaySinh.addActionListener(this::txtNgaySinhActionPerformed);
        pnMain.add(txtNgaySinh);
        txtNgaySinh.setBounds(30, 310, 280, 35);

        lblHang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHang.setForeground(new java.awt.Color(35, 30, 48));
        lblHang.setText("Hạng thành viên");
        pnMain.add(lblHang);
        lblHang.setBounds(30, 360, 280, 18);

        cbxHangThanhVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxHangThanhVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thành viên mới", "Thành viên Bạc", "Thành viên Vàng", "Thành viên Kim Cương" }));
        pnMain.add(cbxHangThanhVien);
        cbxHangThanhVien.setBounds(30, 380, 280, 35);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnMain.add(btnThemMoi);
        btnThemMoi.setBounds(30, 440, 135, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnMain.add(btnCapNhat);
        btnCapNhat.setBounds(175, 440, 135, 40);

        btnXoa.setBackground(new java.awt.Color(220, 53, 69));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);
        pnMain.add(btnXoa);
        btnXoa.setBounds(30, 490, 135, 40);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnMain.add(btnHuy);
        btnHuy.setBounds(175, 490, 135, 40);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm (Mã/SĐT):");
        pnMain.add(lblTimKiem);
        lblTimKiem.setBounds(340, 80, 130, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTimKiem.addActionListener(this::txtTimKiemActionPerformed);
        pnMain.add(txtTimKiem);
        txtTimKiem.setBounds(480, 80, 280, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnMain.add(btnTimKiem);
        btnTimKiem.setBounds(770, 80, 100, 35);

        tblHoiVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HV", "Họ tên", "SĐT", "Email", "Hạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoiVien.setRowHeight(30);
        tblHoiVien.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblHoiVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoiVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoiVien);

        pnMain.add(jScrollPane1);
        jScrollPane1.setBounds(340, 130, 600, 390);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed
        private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        com.wms.model.NhanSu_KhachHang.HoiVienDTO newHoiVien = new com.wms.model.NhanSu_KhachHang.HoiVienDTO();
        newHoiVien.setHoTen(txtHoTen.getText().trim());
        newHoiVien.setSdt(txtSDT.getText().trim());
        newHoiVien.setEmail(txtEmail.getText().trim());
        
        try {
            String dateStr = txtNgaySinh.getText().trim();
            if (!dateStr.isEmpty()) {
                java.util.Date parsed = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(dateStr);
                newHoiVien.setNgaySinh(new java.sql.Date(parsed.getTime()));
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ (dd/MM/yyyy)!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            controller.themMoiHoiVien(newHoiVien);
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm mới thành công!\nTài khoản đăng nhập: SĐT hoặc Email\nMật khẩu mặc định: 123456");
            loadDataToTable();
            btnHuyActionPerformed(null);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm mới thất bại!\nChi tiết: " + ex.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (selectedHoiVien == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một hội viên để cập nhật!", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        selectedHoiVien.setHoTen(txtHoTen.getText().trim());
        selectedHoiVien.setSdt(txtSDT.getText().trim());
        selectedHoiVien.setEmail(txtEmail.getText().trim());
        try {
            String dateStr = txtNgaySinh.getText().trim();
            if (!dateStr.isEmpty()) {
                java.util.Date parsed = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(dateStr);
                selectedHoiVien.setNgaySinh(new java.sql.Date(parsed.getTime()));
            } else {
                selectedHoiVien.setNgaySinh(null);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ (dd/MM/yyyy)!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            controller.capNhatHoiVien(selectedHoiVien);
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadDataToTable();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thất bại!\nChi tiết: " + ex.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if (selectedHoiVien == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một hội viên để xóa!", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa hội viên này?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                controller.xoaHoiVien(selectedHoiVien.getMaKH(), selectedHoiVien.getMaND());
                javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
                btnHuyActionPerformed(null);
                loadDataToTable();
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!\nChi tiết: " + ex.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }                                      

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {                                       
        selectedHoiVien = null;
        txtHoTen.setText("");
        txtSDT.setText("");
        txtEmail.setText("");
        txtNgaySinh.setText("");
        cbxHangThanhVien.setSelectedIndex(0);
        tblHoiVien.clearSelection();
    }                                      

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {                                           
        hoiVienList = controller.timKiemHoiVien(txtTimKiem.getText().trim());
        fillTable();
    }                                          

    private void tblHoiVienMouseClicked(java.awt.event.MouseEvent evt) {                                         
        int index = tblHoiVien.getSelectedRow();
        if (index >= 0 && index < hoiVienList.size()) {
            selectedHoiVien = hoiVienList.get(index);
            txtHoTen.setText(selectedHoiVien.getHoTen());
            txtSDT.setText(selectedHoiVien.getSdt());
            txtEmail.setText(selectedHoiVien.getEmail());
            if (selectedHoiVien.getNgaySinh() != null) {
                txtNgaySinh.setText(new java.text.SimpleDateFormat("dd/MM/yyyy").format(selectedHoiVien.getNgaySinh()));
            } else {
                txtNgaySinh.setText("");
            }
            if (selectedHoiVien.getHangThanhVien() != null) {
                cbxHangThanhVien.setSelectedItem(selectedHoiVien.getHangThanhVien());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxHangThanhVien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHang;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblHoiVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
