package com.wms.view.TrangChu.TrangChuQuanLy.QuanLyKhongGian;

import com.wms.dao.ChiNhanhDAO;
import com.wms.dao.KhongGianDAO;
import com.wms.dao.LoaiKhongGianDAO;
import com.wms.model.CoSoVatChat.ChiNhanhDTO;
import com.wms.model.CoSoVatChat.KhongGianDTO;
import com.wms.model.CoSoVatChat.LoaiKhongGianDTO;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class QuanLyKhongGianForm extends javax.swing.JPanel {

    private final KhongGianDAO khongGianDAO = new KhongGianDAO();
    private final LoaiKhongGianDAO loaiKhongGianDAO = new LoaiKhongGianDAO();
    private final ChiNhanhDAO chiNhanhDAO = new ChiNhanhDAO();

    /**
     * Creates new form QuanLyKhongGianForm
     */
    public QuanLyKhongGianForm() {
        initComponents();
        napComboBoxChiNhanh();
        napComboBoxLoaiKhongGian();
        taiDanhSach(null);
        txtMaKhongGian.setText(generateMaKG());
    }

    private String generateMaKG() {
        return "KG" + (System.currentTimeMillis() % 1000000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblMaKhongGian = new javax.swing.JLabel();
        txtMaKhongGian = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        lblTenKhongGian = new javax.swing.JLabel();
        txtTenKhongGian = new javax.swing.JTextField();
        lblChiNhanh = new javax.swing.JLabel();
        cbxChiNhanh = new javax.swing.JComboBox<>();
        lblLoaiKhongGian = new javax.swing.JLabel();
        cbxLoaiKhongGian = new javax.swing.JComboBox<>();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnLoaiKGian = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhongGian = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ KHÔNG GIAN LÀM VIỆC");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        lblMaKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblMaKhongGian.setText("Mã không gian (Tự động)");
        pnMain.add(lblMaKhongGian);
        lblMaKhongGian.setBounds(20, 110, 170, 18);

        txtMaKhongGian.setEditable(false);
        txtMaKhongGian.setBackground(new java.awt.Color(240, 240, 240));
        txtMaKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtMaKhongGian);
        txtMaKhongGian.setBounds(20, 130, 170, 35);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái (*)");
        pnMain.add(lblTrangThai);
        lblTrangThai.setBounds(210, 110, 170, 18);

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Trống", "Đã đặt trước", "Đang hoạt động", "Bảo trì" }));
        pnMain.add(cbxTrangThai);
        cbxTrangThai.setBounds(210, 130, 170, 35);

        lblTenKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblTenKhongGian.setText("Tên không gian (*)");
        pnMain.add(lblTenKhongGian);
        lblTenKhongGian.setBounds(20, 180, 360, 18);

        txtTenKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTenKhongGian);
        txtTenKhongGian.setBounds(20, 200, 360, 35);

        lblChiNhanh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChiNhanh.setForeground(new java.awt.Color(35, 30, 48));
        lblChiNhanh.setText("Thuộc Chi nhánh (*)");
        pnMain.add(lblChiNhanh);
        lblChiNhanh.setBounds(20, 250, 170, 18);

        cbxChiNhanh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxChiNhanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CN001 - Q.1", "CN002 - Thủ Đức" }));
        pnMain.add(cbxChiNhanh);
        cbxChiNhanh.setBounds(20, 270, 170, 35);

        lblLoaiKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoaiKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblLoaiKhongGian.setText("Loại không gian (*)");
        pnMain.add(lblLoaiKhongGian);
        lblLoaiKhongGian.setBounds(210, 250, 170, 18);

        cbxLoaiKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxLoaiKhongGian.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "-- Chọn loại --", "Chỗ ngồi cá nhân", "Phòng họp" }));
        pnMain.add(cbxLoaiKhongGian);
        cbxLoaiKhongGian.setBounds(210, 270, 170, 35);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnMain.add(btnThemMoi);
        btnThemMoi.setBounds(20, 340, 170, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnMain.add(btnCapNhat);
        btnCapNhat.setBounds(210, 340, 170, 40);

        btnLoaiKGian.setBackground(new java.awt.Color(220, 53, 69));
        btnLoaiKGian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoaiKGian.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiKGian.setText("Q.Lý loại K.Gian");
        btnLoaiKGian.addActionListener(this::btnLoaiKGianActionPerformed);
        pnMain.add(btnLoaiKGian);
        btnLoaiKGian.setBounds(20, 390, 170, 40);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnMain.add(btnHuy);
        btnHuy.setBounds(210, 390, 170, 40);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm (Tên/Mã):");
        pnMain.add(lblTimKiem);
        lblTimKiem.setBounds(420, 80, 150, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTimKiem);
        txtTimKiem.setBounds(550, 80, 350, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnMain.add(btnTimKiem);
        btnTimKiem.setBounds(920, 80, 100, 35);

        tblKhongGian.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã KG", "Tên không gian", "Chi nhánh", "Loại", "Tỏa độ", "Trạng thái"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblKhongGian.setRowHeight(30);
        tblKhongGian.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblKhongGian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhongGianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhongGian);

        pnMain.add(jScrollPane1);
        jScrollPane1.setBounds(420, 130, 600, 480);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void napComboBoxChiNhanh() {
        cbxChiNhanh.removeAllItems();
        cbxChiNhanh.addItem("-- Chọn chi nhánh --");
        List<ChiNhanhDTO> dsCN = chiNhanhDAO.layDanhSachChiNhanh();
        for (ChiNhanhDTO cn : dsCN) {
            cbxChiNhanh.addItem(cn.getMaCN() + " - " + cn.getTenCN());
        }
    }

    private void napComboBoxLoaiKhongGian() {
        cbxLoaiKhongGian.removeAllItems();
        cbxLoaiKhongGian.addItem("-- Chọn loại --");
        List<LoaiKhongGianDTO> dsLoai = loaiKhongGianDAO.layTatCaLoaiKhongGian();
        for (LoaiKhongGianDTO loai : dsLoai) {
            cbxLoaiKhongGian.addItem(loai.getMaLoaiKG() + " - " + loai.getTenLoaiKG());
        }
    }

    private void taiDanhSach(String tuKhoa) {
        DefaultTableModel model = (DefaultTableModel) tblKhongGian.getModel();
        model.setRowCount(0);
        List<KhongGianDTO> list = khongGianDAO.timKiem(tuKhoa, null, null);
        for (KhongGianDTO dto : list) {
            String viTriHienThi = String.format("%d,%d,%d,%d",
                    dto.getToaDoX(), dto.getToaDoY(), dto.getChieuDai(), dto.getChieuRong());
            model.addRow(new Object[] {
                    dto.getMaKG(),
                    dto.getTenKG(),
                    dto.getMaCN(),
                    dto.getMaLoaiKG(),
                    viTriHienThi,
                    dto.getTrangThaiKG()
            });
        }
    }

    private String getMaFromCombo(javax.swing.JComboBox<String> cbx) {
        Object item = cbx.getSelectedItem();
        if (item == null)
            return null;
        String str = item.toString();
        if (str.startsWith("--"))
            return null;
        return str.split(" - ")[0].trim();
    }

    private void parseViTriToDTO(String viTri, KhongGianDTO dto) {
        dto.setViTri(viTri);
        try {
            String[] parts = viTri.split(",");
            if (parts.length >= 4) {
                dto.setToaDoX(Integer.parseInt(parts[0].trim()));
                dto.setToaDoY(Integer.parseInt(parts[1].trim()));
                dto.setChieuDai(Integer.parseInt(parts[2].trim()));
                dto.setChieuRong(Integer.parseInt(parts[3].trim()));
            }
        } catch (Exception e) {
        }
    }

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {
        String tenKG = txtTenKhongGian.getText().trim();
        if (tenKG.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên không gian!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            txtTenKhongGian.requestFocus();
            return;
        }

        String maCN = getMaFromCombo(cbxChiNhanh);
        if (maCN == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Chi nhánh!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String maLoaiKG = getMaFromCombo(cbxLoaiKhongGian);
        if (maLoaiKG == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Loại không gian!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        KhongGianDTO dto = new KhongGianDTO();
        dto.setMaKG(txtMaKhongGian.getText().trim());
        dto.setTenKG(tenKG);
        dto.setTrangThaiKG(cbxTrangThai.getSelectedItem().toString());
        dto.setMaLoaiKG(maLoaiKG);
        dto.setMaCN(maCN);
        dto.setToaDoX(1); dto.setToaDoY(1); dto.setChieuDai(1); dto.setChieuRong(1);

        if (khongGianDAO.them(dto)) {
            JOptionPane.showMessageDialog(this, "Thêm không gian thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            taiDanhSach(null);
            laMoiForm();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm không gian thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        String maKG = txtMaKhongGian.getText().trim();
        if (maKG.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 không gian từ bảng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String tenKG = txtTenKhongGian.getText().trim();
        if (tenKG.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên không gian!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            txtTenKhongGian.requestFocus();
            return;
        }

        String maCN = getMaFromCombo(cbxChiNhanh);
        String maLoaiKG = getMaFromCombo(cbxLoaiKhongGian);

        if (maCN == null || maLoaiKG == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Chi nhánh và Loại không gian!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật không gian \"" + maKG + "\"?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        KhongGianDTO dto = khongGianDAO.layTheoMa(maKG);
        if (dto == null) dto = new KhongGianDTO();
        
        dto.setMaKG(maKG);
        dto.setTenKG(tenKG);
        dto.setTrangThaiKG(cbxTrangThai.getSelectedItem().toString());
        dto.setMaLoaiKG(maLoaiKG);
        dto.setMaCN(maCN);

        if (khongGianDAO.capNhat(dto)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            taiDanhSach(null);
            laMoiForm();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnLoaiKGianActionPerformed(java.awt.event.ActionEvent evt) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        QuanLyLoaiKhongGianForm dialog;
        if (parentWindow instanceof java.awt.Frame) {
            dialog = new QuanLyLoaiKhongGianForm((java.awt.Frame) parentWindow, true);
        } else {
            dialog = new QuanLyLoaiKhongGianForm(null, true);
        }
        dialog.setVisible(true);
        napComboBoxLoaiKhongGian();
        taiDanhSach(null);
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        laMoiForm();
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = txtTimKiem.getText().trim();
        taiDanhSach(keyword.isEmpty() ? null : keyword);
    }

    private void tblKhongGianMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblKhongGian.getSelectedRow();
        if (row < 0) return;

        String maKG      = tblKhongGian.getValueAt(row, 0).toString();
        String tenKG     = tblKhongGian.getValueAt(row, 1).toString();
        String maCN      = tblKhongGian.getValueAt(row, 2).toString();
        String maLoaiKG  = tblKhongGian.getValueAt(row, 3).toString();
        String trangThai = tblKhongGian.getValueAt(row, 5).toString();

        txtMaKhongGian.setText(maKG);
        txtTenKhongGian.setText(tenKG);

        for (int i = 0; i < cbxTrangThai.getItemCount(); i++) {
            if (cbxTrangThai.getItemAt(i).equalsIgnoreCase(trangThai)) {
                cbxTrangThai.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < cbxChiNhanh.getItemCount(); i++) {
            String item = cbxChiNhanh.getItemAt(i);
            if (item.startsWith(maCN + " ") || item.equals(maCN)) {
                cbxChiNhanh.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < cbxLoaiKhongGian.getItemCount(); i++) {
            String item = cbxLoaiKhongGian.getItemAt(i);
            if (item.startsWith(maLoaiKG + " ") || item.equals(maLoaiKG)) {
                cbxLoaiKhongGian.setSelectedIndex(i);
                break;
            }
        }
    }

    private void laMoiForm() {
        txtMaKhongGian.setText(generateMaKG());
        txtTenKhongGian.setText("");
        txtTimKiem.setText("");
        cbxTrangThai.setSelectedIndex(0);
        if (cbxChiNhanh.getItemCount() > 0) cbxChiNhanh.setSelectedIndex(0);
        if (cbxLoaiKhongGian.getItemCount() > 0) cbxLoaiKhongGian.setSelectedIndex(0);
        tblKhongGian.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLoaiKGian;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxChiNhanh;
    private javax.swing.JComboBox<String> cbxLoaiKhongGian;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChiNhanh;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblLoaiKhongGian;
    private javax.swing.JLabel lblMaKhongGian;
    private javax.swing.JLabel lblTenKhongGian;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblKhongGian;
    private javax.swing.JTextField txtMaKhongGian;
    private javax.swing.JTextField txtTenKhongGian;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
