/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wms.view.QuanLyChiNhanh;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyChiNhanhForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyChiNhanhForm.class.getName());

    /**
     * Creates new form QuanLyChiNhanhForm
     */
    public QuanLyChiNhanhForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblTenChiNhanh = new javax.swing.JLabel();
        txtTenChiNhanh = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lblBanDo = new javax.swing.JLabel();
        txtBanDo = new javax.swing.JTextField();
        lblHotline = new javax.swing.JLabel();
        txtHotline = new javax.swing.JTextField();
        lblNguoiQuanLy = new javax.swing.JLabel();
        cbxNguoiQuanLy = new javax.swing.JComboBox<>();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnVoHieuHoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiNhanh = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý Chi nhánh - Không gian làm việc và học tập");
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 550));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ CHI NHÁNH");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        lblTenChiNhanh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenChiNhanh.setForeground(new java.awt.Color(35, 30, 48));
        lblTenChiNhanh.setText("Tên chi nhánh (*)");
        pnMain.add(lblTenChiNhanh);
        lblTenChiNhanh.setBounds(20, 70, 360, 18);

        txtTenChiNhanh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTenChiNhanh);
        txtTenChiNhanh.setBounds(20, 90, 360, 35);

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(35, 30, 48));
        lblDiaChi.setText("Địa chỉ (*)");
        pnMain.add(lblDiaChi);
        lblDiaChi.setBounds(20, 135, 360, 18);

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtDiaChi);
        txtDiaChi.setBounds(20, 155, 360, 35);

        lblBanDo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblBanDo.setForeground(new java.awt.Color(35, 30, 48));
        lblBanDo.setText("Đường dẫn bản đồ");
        pnMain.add(lblBanDo);
        lblBanDo.setBounds(20, 200, 360, 18);

        txtBanDo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtBanDo);
        txtBanDo.setBounds(20, 220, 360, 35);

        lblHotline.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHotline.setForeground(new java.awt.Color(35, 30, 48));
        lblHotline.setText("Số đường dây nóng (*)");
        pnMain.add(lblHotline);
        lblHotline.setBounds(20, 265, 170, 18);

        txtHotline.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtHotline);
        txtHotline.setBounds(20, 285, 170, 35);

        lblNguoiQuanLy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNguoiQuanLy.setForeground(new java.awt.Color(35, 30, 48));
        lblNguoiQuanLy.setText("Người quản lý phụ trách (*)");
        pnMain.add(lblNguoiQuanLy);
        lblNguoiQuanLy.setBounds(210, 265, 170, 18);

        cbxNguoiQuanLy.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxNguoiQuanLy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn người quản lý --" }));
        cbxNguoiQuanLy.addActionListener(this::cbxNguoiQuanLyActionPerformed);
        pnMain.add(cbxNguoiQuanLy);
        cbxNguoiQuanLy.setBounds(210, 285, 170, 35);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnMain.add(btnThemMoi);
        btnThemMoi.setBounds(20, 410, 170, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnMain.add(btnCapNhat);
        btnCapNhat.setBounds(210, 410, 170, 40);

        btnVoHieuHoa.setBackground(new java.awt.Color(220, 53, 69));
        btnVoHieuHoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoHieuHoa.setForeground(new java.awt.Color(255, 255, 255));
        btnVoHieuHoa.setText("Vô hiệu hóa");
        btnVoHieuHoa.addActionListener(this::btnVoHieuHoaActionPerformed);
        pnMain.add(btnVoHieuHoa);
        btnVoHieuHoa.setBounds(20, 465, 170, 40);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnMain.add(btnHuy);
        btnHuy.setBounds(210, 465, 170, 40);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm (Tên/Địa chỉ):");
        pnMain.add(lblTimKiem);
        lblTimKiem.setBounds(420, 80, 150, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTimKiem);
        txtTimKiem.setBounds(575, 80, 325, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnMain.add(btnTimKiem);
        btnTimKiem.setBounds(920, 80, 100, 35);

        tblChiNhanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã CN", "Tên chi nhánh", "Địa chỉ", "Bản đồ", "Hotline", "Quản lý", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiNhanh.setRowHeight(30);
        tblChiNhanh.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblChiNhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiNhanhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChiNhanh);

        pnMain.add(jScrollPane1);
        jScrollPane1.setBounds(420, 130, 600, 375);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxNguoiQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNguoiQuanLyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNguoiQuanLyActionPerformed

private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO: Viết logic Thêm mới chi nhánh
    }                                          

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO: Viết logic Cập nhật thông tin chi nhánh
    }                                          

    private void btnVoHieuHoaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO: Viết logic Vô hiệu hóa chi nhánh (Chuyển trạng thái sang ngưng hoạt động)
    }                                        

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO: Xóa trắng form để nhập liệu mới
    }                                      

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO: Viết logic tra cứu theo Tên hoặc Địa chỉ
    }                                          

    private void tblChiNhanhMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO: Lấy dữ liệu dòng được click và hiển thị ngược lên các text field
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuanLyChiNhanhForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnVoHieuHoa;
    private javax.swing.JComboBox<String> cbxNguoiQuanLy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanDo;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblHotline;
    private javax.swing.JLabel lblNguoiQuanLy;
    private javax.swing.JLabel lblTenChiNhanh;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblChiNhanh;
    private javax.swing.JTextField txtBanDo;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHotline;
    private javax.swing.JTextField txtTenChiNhanh;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
