package com.wms.view.DatChoTruoc;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Thinkapd T14s
 */
public class DatChoTruocForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatChoTruocForm.class.getName());

    /**
     * Creates new form DatChoTruocForm
     */
    public DatChoTruocForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblChiNhanh = new javax.swing.JLabel();
        cbxChiNhanh = new javax.swing.JComboBox<>();
        lblLoaiKhongGian = new javax.swing.JLabel();
        cbxLoaiKhongGian = new javax.swing.JComboBox<>();
        lblNgayDat = new javax.swing.JLabel();
        txtNgayDat = new javax.swing.JTextField();
        lblGioBatDau = new javax.swing.JLabel();
        cbxGioBatDau = new javax.swing.JComboBox<>();
        lblGioKetThuc = new javax.swing.JLabel();
        cbxGioKetThuc = new javax.swing.JComboBox<>();
        btnTimChoTrong = new javax.swing.JButton();
        lblDanhSach = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhongGianTrong = new javax.swing.JTable();
        lblThongTinChon = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        btnDatCho = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đặt chỗ trước - Không gian làm việc và học tập");
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 550));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("ĐẶT CHỖ KHÔNG GIAN");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        lblChiNhanh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChiNhanh.setForeground(new java.awt.Color(35, 30, 48));
        lblChiNhanh.setText("Chọn Chi nhánh");
        pnMain.add(lblChiNhanh);
        lblChiNhanh.setBounds(20, 80, 300, 18);

        cbxChiNhanh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxChiNhanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Tất cả chi nhánh --", "Chi nhánh Trung tâm" }));
        pnMain.add(cbxChiNhanh);
        cbxChiNhanh.setBounds(20, 100, 300, 35);

        lblLoaiKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoaiKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblLoaiKhongGian.setText("Loại không gian");
        pnMain.add(lblLoaiKhongGian);
        lblLoaiKhongGian.setBounds(20, 150, 300, 18);

        cbxLoaiKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxLoaiKhongGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Tất cả loại --", "Chỗ ngồi cá nhân", "Phòng họp" }));
        pnMain.add(cbxLoaiKhongGian);
        cbxLoaiKhongGian.setBounds(20, 170, 300, 35);

        lblNgayDat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNgayDat.setForeground(new java.awt.Color(35, 30, 48));
        lblNgayDat.setText("Ngày sử dụng (dd/MM/yyyy) (*)");
        pnMain.add(lblNgayDat);
        lblNgayDat.setBounds(20, 220, 300, 18);

        txtNgayDat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtNgayDat);
        txtNgayDat.setBounds(20, 240, 300, 35);

        lblGioBatDau.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGioBatDau.setForeground(new java.awt.Color(35, 30, 48));
        lblGioBatDau.setText("Từ giờ (*)");
        pnMain.add(lblGioBatDau);
        lblGioBatDau.setBounds(20, 290, 140, 18);

        cbxGioBatDau.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxGioBatDau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00" }));
        pnMain.add(cbxGioBatDau);
        cbxGioBatDau.setBounds(20, 310, 140, 35);

        lblGioKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGioKetThuc.setForeground(new java.awt.Color(35, 30, 48));
        lblGioKetThuc.setText("Đến giờ (*)");
        pnMain.add(lblGioKetThuc);
        lblGioKetThuc.setBounds(180, 290, 140, 18);

        cbxGioKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxGioKetThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00" }));
        pnMain.add(cbxGioKetThuc);
        cbxGioKetThuc.setBounds(180, 310, 140, 35);

        btnTimChoTrong.setBackground(new java.awt.Color(235, 94, 141));
        btnTimChoTrong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimChoTrong.setForeground(new java.awt.Color(255, 255, 255));
        btnTimChoTrong.setText("Tìm chỗ trống hợp lệ");
        btnTimChoTrong.addActionListener(this::btnTimChoTrongActionPerformed);
        pnMain.add(btnTimChoTrong);
        btnTimChoTrong.setBounds(20, 380, 300, 45);

        lblDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDanhSach.setForeground(new java.awt.Color(35, 30, 48));
        lblDanhSach.setText("Danh sách không gian đang sẵn sàng vào khung giờ này:");
        pnMain.add(lblDanhSach);
        lblDanhSach.setBounds(350, 80, 400, 20);

        tblKhongGianTrong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KG", "Tên không gian", "Loại", "Đơn giá (VNĐ/Giờ)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhongGianTrong.setRowHeight(30);
        tblKhongGianTrong.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblKhongGianTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhongGianTrongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhongGianTrong);

        pnMain.add(jScrollPane1);
        jScrollPane1.setBounds(350, 110, 670, 260);

        lblThongTinChon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblThongTinChon.setForeground(new java.awt.Color(35, 30, 48));
        lblThongTinChon.setText("Không gian đã chọn: Chưa chọn");
        pnMain.add(lblThongTinChon);
        lblThongTinChon.setBounds(350, 390, 400, 22);

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(220, 53, 69));
        lblTongTien.setText("Tổng tiền dự kiến: 0 VNĐ");
        pnMain.add(lblTongTien);
        lblTongTien.setBounds(350, 420, 400, 22);

        btnDatCho.setBackground(new java.awt.Color(235, 94, 141));
        btnDatCho.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDatCho.setForeground(new java.awt.Color(255, 255, 255));
        btnDatCho.setText("Đặt chỗ và Thanh toán");
        btnDatCho.addActionListener(this::btnDatChoActionPerformed);
        pnMain.add(btnDatCho);
        btnDatCho.setBounds(800, 400, 220, 45);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(235, 94, 141));
        btnLamMoi.setText("Hủy / Làm mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);
        pnMain.add(btnLamMoi);
        btnLamMoi.setBounds(800, 460, 220, 35);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimChoTrongActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO: Viết logic lọc và tìm Không gian trống chưa bị ai đặt trong Ngày và Giờ đã chọn. Sau đó đổ list vào tblKhongGianTrong
    }                                          

    private void tblKhongGianTrongMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO: Khi User click vào 1 dòng trong bảng -> Lấy Tên Không gian và Tính tổng tiền (Giá * Số giờ) hiển thị lên 2 Lables: lblThongTinChon và lblTongTien
    }

    private void btnDatChoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO: (Bước 4 & 5 Use Case) Khóa chỗ tạm thời -> Chuyển sang màn hình Thanh toán (Mở Dialog hoặc Frame khác). Nếu thanh toán OK -> Insert DATCHO vào DB
    }                                          

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO: (Bước 4a Use Case) Hủy tiến trình đặt chỗ, clear toàn bộ form và giải phóng khóa chỗ tạm thời (nếu có)
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DatChoTruocForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatCho;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimChoTrong;
    private javax.swing.JComboBox<String> cbxChiNhanh;
    private javax.swing.JComboBox<String> cbxGioBatDau;
    private javax.swing.JComboBox<String> cbxGioKetThuc;
    private javax.swing.JComboBox<String> cbxLoaiKhongGian;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChiNhanh;
    private javax.swing.JLabel lblDanhSach;
    private javax.swing.JLabel lblGioBatDau;
    private javax.swing.JLabel lblGioKetThuc;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblLoaiKhongGian;
    private javax.swing.JLabel lblNgayDat;
    private javax.swing.JLabel lblThongTinChon;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblKhongGianTrong;
    private javax.swing.JTextField txtNgayDat;
    // End of variables declaration//GEN-END:variables
}
