ALTER TABLE LOAIKHONGGIAN
ADD TRANGTHAI VARCHAR2(100)

ALTER TABLE PHIEUGIAMGIA
ADD TRANGTHAI VARCHAR2(100)

COMMIT

ALTER TABLE PHIENLAMVIEC ADD CONSTRAINT CHK_PLV_TrangThai
    CHECK (TrangThaiPhien IN ('Đang chờ thanh toán','Đang hoạt động', 'Đã đặt trước', 'Đã kết thúc'));
