CREATE OR REPLACE TRIGGER TRG_HOADON_NV_CUNG_CHINHANH
BEFORE INSERT OR UPDATE OF MaNV, MaPhien ON HOADON
FOR EACH ROW
WHEN (NEW.MaNV IS NOT NULL AND NEW.MaPhien IS NOT NULL)
DECLARE
    v_MaCN_KG KHONGGIAN.MaCN%TYPE;
    v_MaCN_NV NHANVIEN.MaCN%TYPE;
BEGIN
    SELECT kg.MaCN
    INTO v_MaCN_KG
    FROM PHIENLAMVIEC plv
    JOIN KHONGGIAN kg ON kg.MaKG = plv.MaKG
    WHERE plv.MaPhien = :NEW.MaPhien;

    SELECT MaCN
    INTO v_MaCN_NV
    FROM NHANVIEN
    WHERE MaNV = :NEW.MaNV;

    IF v_MaCN_KG <> v_MaCN_NV THEN
        RAISE_APPLICATION_ERROR(-20202, 'Nhân viên thu ngân phải cùng chi nhánh với không gian sử dụng.');
    END IF;
END;
/