package com.wms.view.TrangChuQuanLy.QuanLyKhongGian;

import com.wms.controller.TrangChuQuanLy.QuanLyKhongGian.KhongGianController;
import com.wms.model.TrangChuQuanLy.QuanLyChiNhanh.ChiNhanhDTO;
import com.wms.model.TrangChuQuanLy.QuanLyKhongGian.KhongGianDTO;
import com.wms.model.TrangChuQuanLy.QuanLyKhongGian.LoaiKhongGianDTO;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class QuanLyKhongGianForm extends javax.swing.JPanel {

    private final KhongGianController controller = new KhongGianController();

    public QuanLyKhongGianForm() {
        initComponents();
        setupTable();
        napComboBoxChiNhanh();
        napComboBoxLoaiKhongGian();
        apDungPhanQuyen();
        taiDanhSach(null);
        txtMaKhongGian.setText(controller.sinhMaKG());
        com.wms.util.TienIchFormQuanLy.apDung(this);
    }

    private String maCNFilter = null;

    private void apDungPhanQuyen() {
        com.wms.model.TrangChuQuanLy.QuanLyNguoiDung.NguoiDungDTO user = com.wms.controller.TrangChuGioiThieu.DangNhapController
                .getCurrentUser();
        if (user == null)
            return;
        if (!user.hasRole(com.wms.config.AppConstants.ROLE_ADMIN_CODE)) {
            maCNFilter = new com.wms.dao.TrangChuQuanLy.QuanLyNhanVien.NhanVienDAO().layMaCNTuMaND(user.getMaND());
            if (maCNFilter != null) {
                for (int i = 0; i < cbxChiNhanh.getItemCount(); i++) {
                    String item = cbxChiNhanh.getItemAt(i);
                    if (item != null && item.startsWith(maCNFilter + " - ")) {
                        cbxChiNhanh.setSelectedIndex(i);
                        break;
                    }
                }
                cbxChiNhanh.setEnabled(false);
            }
        }
    }

    private void setupTable() {
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < tblKhongGian.getColumnCount(); i++) {
            if (i == 0 || i >= 4) { // Mã, Tọa độ, Trạng thái
                tblKhongGian.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
        }
    }

    private void napComboBoxChiNhanh() {
        cbxChiNhanh.removeAllItems();
        cbxChiNhanh.addItem("-- Chọn chi nhánh --");
        List<ChiNhanhDTO> dsCN = controller.layDanhSachChiNhanh();
        for (ChiNhanhDTO cn : dsCN) {
            cbxChiNhanh.addItem(cn.getMaCN() + " - " + cn.getTenCN());
        }
    }

    private void napComboBoxLoaiKhongGian() {
        cbxLoaiKhongGian.removeAllItems();
        cbxLoaiKhongGian.addItem("-- Chọn loại --");
        List<LoaiKhongGianDTO> dsLoai = controller.layTatCaLoai();
        for (LoaiKhongGianDTO loai : dsLoai) {
            cbxLoaiKhongGian.addItem(loai.getMaLoaiKG() + " - " + loai.getTenLoaiKG());
        }
    }

    private void taiDanhSach(String tuKhoa) {
        DefaultTableModel model = (DefaultTableModel) tblKhongGian.getModel();
        model.setRowCount(0);
        String maCN = getMaFromCombo(cbxChiNhanh);
        String maLoai = getMaFromCombo(cbxLoaiKhongGian);
        List<KhongGianDTO> list = controller.timKiemKhongGian(tuKhoa, maCN, maLoai);
        for (KhongGianDTO dto : list) {
            String viTriHienThi = String.format("%d,%d,%d,%d",
                    dto.getToaDoX(), dto.getToaDoY(), dto.getChieuDai(), dto.getChieuRong());

            String tenCN = (dto.getTenCN() != null) ? dto.getTenCN() : dto.getMaCN();
            String tenLoai = (dto.getTenLoaiKG() != null) ? dto.getTenLoaiKG() : dto.getMaLoaiKG();

            model.addRow(new Object[] {
                    dto.getMaKG(),
                    dto.getTenKG(),
                    tenCN,
                    tenLoai,
                    viTriHienThi,
                    dto.getTrangThaiKG()
            });
        }
    }

    private String getMaFromCombo(javax.swing.JComboBox<String> cbx) {
        Object item = cbx.getSelectedItem();
        if (item == null)
            return null;
        String str = item.toString();
        if (str.startsWith("--"))
            return null;
        return str.split(" - ")[0].trim();
    }

    private void laMoiForm() {
        txtMaKhongGian.setText(controller.sinhMaKG());
        txtTenKhongGian.setText("");
        txtTimKiem.setText("");
        cbxTrangThai.setSelectedIndex(0);
        if (cbxChiNhanh.isEnabled() && cbxChiNhanh.getItemCount() > 0)
            cbxChiNhanh.setSelectedIndex(0);
        if (cbxLoaiKhongGian.getItemCount() > 0)
            cbxLoaiKhongGian.setSelectedIndex(0);
        tblKhongGian.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblMaKhongGian = new javax.swing.JLabel();
        txtMaKhongGian = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        lblTenKhongGian = new javax.swing.JLabel();
        txtTenKhongGian = new javax.swing.JTextField();
        lblChiNhanh = new javax.swing.JLabel();
        cbxChiNhanh = new javax.swing.JComboBox<>();
        lblLoaiKhongGian = new javax.swing.JLabel();
        cbxLoaiKhongGian = new javax.swing.JComboBox<>();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnLoaiKGian = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhongGian = new javax.swing.JTable();
        btnSoDo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ KHÔNG GIAN LÀM VIỆC");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        lblMaKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblMaKhongGian.setText("Mã không gian");
        pnMain.add(lblMaKhongGian);
        lblMaKhongGian.setBounds(20, 110, 170, 18);

        txtMaKhongGian.setEditable(false);
        txtMaKhongGian.setBackground(new java.awt.Color(240, 240, 240));
        txtMaKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtMaKhongGian);
        txtMaKhongGian.setBounds(20, 130, 170, 35);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái (*)");
        pnMain.add(lblTrangThai);
        lblTrangThai.setBounds(210, 110, 170, 18);

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Bảo trì" }));
        pnMain.add(cbxTrangThai);
        cbxTrangThai.setBounds(210, 130, 170, 35);

        lblTenKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblTenKhongGian.setText("Tên không gian (*)");
        pnMain.add(lblTenKhongGian);
        lblTenKhongGian.setBounds(20, 180, 360, 18);

        txtTenKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTenKhongGian);
        txtTenKhongGian.setBounds(20, 200, 360, 35);

        lblChiNhanh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChiNhanh.setForeground(new java.awt.Color(35, 30, 48));
        lblChiNhanh.setText("Thuộc Chi nhánh (*)");
        pnMain.add(lblChiNhanh);
        lblChiNhanh.setBounds(20, 250, 360, 18);

        cbxChiNhanh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxChiNhanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CN001 - Q.1", "CN002 - Thủ Đức" }));
        pnMain.add(cbxChiNhanh);
        cbxChiNhanh.setBounds(20, 270, 360, 35);

        lblLoaiKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoaiKhongGian.setForeground(new java.awt.Color(35, 30, 48));
        lblLoaiKhongGian.setText("Loại không gian (*)");
        pnMain.add(lblLoaiKhongGian);
        lblLoaiKhongGian.setBounds(20, 320, 360, 18);

        cbxLoaiKhongGian.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxLoaiKhongGian.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "-- Chọn loại --", "Chỗ ngồi cá nhân", "Phòng họp" }));
        pnMain.add(cbxLoaiKhongGian);
        cbxLoaiKhongGian.setBounds(20, 340, 360, 35);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnMain.add(btnThemMoi);
        btnThemMoi.setBounds(20, 390, 120, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnMain.add(btnCapNhat);
        btnCapNhat.setBounds(150, 390, 110, 40);

        btnLoaiKGian.setBackground(new java.awt.Color(35, 30, 48));
        btnLoaiKGian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoaiKGian.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiKGian.setText("Quản lý Loại không gian");
        btnLoaiKGian.addActionListener(this::btnLoaiKGianActionPerformed);
        pnMain.add(btnLoaiKGian);
        btnLoaiKGian.setBounds(20, 440, 360, 40);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnMain.add(btnHuy);
        btnHuy.setBounds(270, 390, 110, 40);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm (Tên/Mã):");
        pnMain.add(lblTimKiem);
        lblTimKiem.setBounds(420, 80, 150, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTimKiem);
        txtTimKiem.setBounds(550, 80, 350, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnMain.add(btnTimKiem);
        btnTimKiem.setBounds(920, 80, 100, 35);

        tblKhongGian.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã KG", "Tên không gian", "Chi nhánh", "Loại", "Tọa độ", "Trạng thái"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblKhongGian.setRowHeight(30);
        tblKhongGian.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblKhongGian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhongGianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhongGian);

        pnMain.add(jScrollPane1);
        jScrollPane1.setBounds(420, 130, 600, 480);

        btnSoDo.setBackground(new java.awt.Color(35, 30, 48));
        btnSoDo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSoDo.setForeground(new java.awt.Color(255, 255, 255));
        btnSoDo.setText("Quản lý sơ đồ chi nhánh");
        btnSoDo.addActionListener(this::btnSoDoActionPerformed);
        pnMain.add(btnSoDo);
        btnSoDo.setBounds(20, 490, 360, 40);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoDoActionPerformed(java.awt.event.ActionEvent evt) {
        String maCN = getMaFromCombo(cbxChiNhanh);
        if (maCN == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn chi nhánh cần xem sơ đồ từ danh sách chọn!");
            return;
        }

        String tenCN = "";
        Object item = cbxChiNhanh.getSelectedItem();
        if (item != null) {
            String[] parts = item.toString().split(" - ", 2);
            if (parts.length > 1) {
                tenCN = parts[1].trim();
            }
        }

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = null;
        if (parentWindow instanceof java.awt.Frame) {
            parentFrame = (java.awt.Frame) parentWindow;
        }

        QuanLySoDoKhongGianForm dialog = new QuanLySoDoKhongGianForm(parentFrame, true, maCN, tenCN);
        dialog.setVisible(true);
    }

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {
        String tenKG = txtTenKhongGian.getText().trim();
        if (tenKG.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên không gian!", "Cảnh báo",
                    JOptionPane.WARNING_MESSAGE);
            txtTenKhongGian.requestFocus();
            return;
        }

        String maCN = getMaFromCombo(cbxChiNhanh);
        String maLoaiKG = getMaFromCombo(cbxLoaiKhongGian);

        if (maCN == null || maLoaiKG == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Chi nhánh và Loại không gian!", "Cảnh báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        KhongGianDTO dto = new KhongGianDTO();
        dto.setMaKG(txtMaKhongGian.getText().trim());
        dto.setTenKG(tenKG);
        dto.setTrangThaiKG(cbxTrangThai.getSelectedItem().toString());
        dto.setMaLoaiKG(maLoaiKG);
        dto.setMaCN(maCN);
        // Default coordinates
        dto.setToaDoX(1);
        dto.setToaDoY(1);
        dto.setChieuDai(1);
        dto.setChieuRong(1);

        if (controller.themKhongGian(dto)) {
            JOptionPane.showMessageDialog(this, "Thêm không gian thành công!", "Thành công",
                    JOptionPane.INFORMATION_MESSAGE);
            taiDanhSach(null);
            laMoiForm();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm không gian thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        String maKG = txtMaKhongGian.getText().trim();
        if (maKG.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 không gian từ bảng!", "Thông báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String tenKG = txtTenKhongGian.getText().trim();
        if (tenKG.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên không gian!", "Cảnh báo",
                    JOptionPane.WARNING_MESSAGE);
            txtTenKhongGian.requestFocus();
            return;
        }

        String maCN = getMaFromCombo(cbxChiNhanh);
        String maLoaiKG = getMaFromCombo(cbxLoaiKhongGian);

        if (maCN == null || maLoaiKG == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn Chi nhánh và Loại không gian!", "Cảnh báo",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int xacNhan = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật không gian \"" + maKG + "\"?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (xacNhan != JOptionPane.YES_OPTION)
            return;

        KhongGianDTO dto = controller.layKhongGianTheoMa(maKG);
        if (dto == null)
            dto = new KhongGianDTO();

        dto.setMaKG(maKG);
        dto.setTenKG(tenKG);
        dto.setTrangThaiKG(cbxTrangThai.getSelectedItem().toString());
        dto.setMaLoaiKG(maLoaiKG);
        dto.setMaCN(maCN);

        if (controller.capNhatKhongGian(dto)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            taiDanhSach(null);
            laMoiForm();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnLoaiKGianActionPerformed(java.awt.event.ActionEvent evt) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        QuanLyLoaiKhongGianForm dialog = new QuanLyLoaiKhongGianForm(
                parentWindow instanceof java.awt.Frame ? (java.awt.Frame) parentWindow : null, true);
        dialog.setVisible(true);
        napComboBoxLoaiKhongGian();
        taiDanhSach(null);
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        laMoiForm();
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = txtTimKiem.getText().trim();
        taiDanhSach(keyword.isEmpty() ? null : keyword);
    }

    private void tblKhongGianMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblKhongGian.getSelectedRow();
        if (row < 0)
            return;

        String maKG = tblKhongGian.getValueAt(row, 0).toString();
        String tenKG = tblKhongGian.getValueAt(row, 1).toString();
        String maCN = tblKhongGian.getValueAt(row, 2).toString();
        String maLoaiKG = tblKhongGian.getValueAt(row, 3).toString();
        String trangThai = tblKhongGian.getValueAt(row, 5).toString();

        txtMaKhongGian.setText(maKG);
        txtTenKhongGian.setText(tenKG);

        cbxTrangThai.setSelectedItem(trangThai);

        for (int i = 0; i < cbxChiNhanh.getItemCount(); i++) {
            String item = cbxChiNhanh.getItemAt(i);
            if (item != null && item.contains(" - ")) {
                String tenCN = item.split(" - ", 2)[1].trim();
                if (tenCN.equalsIgnoreCase(maCN)) {
                    cbxChiNhanh.setSelectedIndex(i);
                    break;
                }
            }
        }
        for (int i = 0; i < cbxLoaiKhongGian.getItemCount(); i++) {
            String item = cbxLoaiKhongGian.getItemAt(i);
            if (item != null && item.contains(" - ")) {
                String tenLoai = item.split(" - ", 2)[1].trim();
                if (tenLoai.equalsIgnoreCase(maLoaiKG)) {
                    cbxLoaiKhongGian.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLoaiKGian;
    private javax.swing.JButton btnSoDo;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxChiNhanh;
    private javax.swing.JComboBox<String> cbxLoaiKhongGian;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChiNhanh;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblLoaiKhongGian;
    private javax.swing.JLabel lblMaKhongGian;
    private javax.swing.JLabel lblTenKhongGian;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblKhongGian;
    private javax.swing.JTextField txtMaKhongGian;
    private javax.swing.JTextField txtTenKhongGian;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
