package com.wms.view.TrangChuQuanLy.QuanLyKhongGian;

import com.wms.controller.TrangChuQuanLy.QuanLyKhongGian.KhongGianController;
import com.wms.model.TrangChuQuanLy.QuanLyKhongGian.LoaiKhongGianDTO;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.util.List;

public class QuanLyLoaiKhongGianForm extends javax.swing.JDialog {

    private final KhongGianController controller = new KhongGianController();
    private static final DecimalFormat FORMAT_TIEN = new DecimalFormat("#,###");

    public QuanLyLoaiKhongGianForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        taiDanhSach(null);
        txtMaLoaiKG.setText(controller.sinhMaLoaiKG());
        
        txtDonGia.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { formatDonGia(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { formatDonGia(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { formatDonGia(); }
        });

        pack();
        setLocationRelativeTo(parent);
        com.wms.util.TienIchFormQuanLy.apDung(this);
    }

    private boolean isFormatting = false;

    private void formatDonGia() {
        if (isFormatting) return;
        javax.swing.SwingUtilities.invokeLater(() -> {
            isFormatting = true;
            try {
                String text = txtDonGia.getText().replace(",", "").replace(".", "");
                if (!text.isEmpty()) {
                    long value = Long.parseLong(text);
                    String formatted = FORMAT_TIEN.format(value);
                    if (!txtDonGia.getText().equals(formatted)) {
                        txtDonGia.setText(formatted);
                    }
                }
            } catch (NumberFormatException ex) {
                // Ignore invalid input
            } finally {
                isFormatting = false;
            }
        });
    }

    private void taiDanhSach(String tuKhoa) {
        DefaultTableModel model = (DefaultTableModel) tblLoaiKhongGian.getModel();
        model.setRowCount(0);
        List<LoaiKhongGianDTO> list = controller.timKiemLoai(tuKhoa);
        for (LoaiKhongGianDTO dto : list) {
            String sucChua = dto.getSucChua() != null ? String.valueOf(dto.getSucChua()) : "-";
            String donGia = dto.getDonGiaTheoGio() != null ? FORMAT_TIEN.format(dto.getDonGiaTheoGio()) : "-";
            String trangThai = dto.getTrangThai() != null ? dto.getTrangThai() : "Đang hoạt động";
            model.addRow(new Object[]{dto.getMaLoaiKG(), dto.getTenLoaiKG(), sucChua, donGia, trangThai});
        }
    }

    private void laMoiForm() {
        txtMaLoaiKG.setText(controller.sinhMaLoaiKG());
        txtTenLoaiKG.setText("");
        txtSucChua.setText("");
        txtDonGia.setText("");
        txtTimKiem.setText("");
        cbxTrangThai.setSelectedIndex(0);
        tblLoaiKhongGian.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaLoaiKG = new javax.swing.JLabel();
        txtMaLoaiKG = new javax.swing.JTextField();
        lblTenLoaiKG = new javax.swing.JLabel();
        txtTenLoaiKG = new javax.swing.JTextField();
        lblSucChua = new javax.swing.JLabel();
        txtSucChua = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        cbxTrangThai = new javax.swing.JComboBox<>();
        lblTrangThai = new javax.swing.JLabel();
        pnRight = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiKhongGian = new javax.swing.JTable();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý Loại Không Gian");
        setModal(true);
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(850, 550));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(35, 30, 48));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ LOẠI KHÔNG GIAN");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 850, 50);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 850, 50);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("THÔNG TIN CHI TIẾT");
        pnLeft.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 260, 30);

        lblMaLoaiKG.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaLoaiKG.setForeground(new java.awt.Color(35, 30, 48));
        lblMaLoaiKG.setText("Mã loại Không gian");
        pnLeft.add(lblMaLoaiKG);
        lblMaLoaiKG.setBounds(20, 60, 260, 20);

        txtMaLoaiKG.setEditable(false);
        txtMaLoaiKG.setBackground(new java.awt.Color(240, 240, 240));
        txtMaLoaiKG.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtMaLoaiKG);
        txtMaLoaiKG.setBounds(20, 80, 260, 30);

        lblTenLoaiKG.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenLoaiKG.setForeground(new java.awt.Color(35, 30, 48));
        lblTenLoaiKG.setText("Tên loại không gian (*)");
        pnLeft.add(lblTenLoaiKG);
        lblTenLoaiKG.setBounds(20, 120, 260, 20);

        txtTenLoaiKG.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtTenLoaiKG);
        txtTenLoaiKG.setBounds(20, 140, 260, 30);

        lblSucChua.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSucChua.setForeground(new java.awt.Color(35, 30, 48));
        lblSucChua.setText("Sức chứa (Người)");
        pnLeft.add(lblSucChua);
        lblSucChua.setBounds(20, 180, 260, 20);

        txtSucChua.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtSucChua);
        txtSucChua.setBounds(20, 200, 260, 30);

        lblDonGia.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDonGia.setForeground(new java.awt.Color(35, 30, 48));
        lblDonGia.setText("Đơn giá (VNĐ/Giờ) (*)");
        pnLeft.add(lblDonGia);
        lblDonGia.setBounds(20, 240, 260, 20);

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtDonGia);
        txtDonGia.setBounds(20, 260, 260, 30);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnLeft.add(btnThemMoi);
        btnThemMoi.setBounds(20, 370, 125, 35);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnLeft.add(btnCapNhat);
        btnCapNhat.setBounds(150, 370, 125, 35);

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Ngừng hoạt động" }));
        cbxTrangThai.setToolTipText("");
        cbxTrangThai.addActionListener(this::cbxTrangThaiActionPerformed);
        pnLeft.add(cbxTrangThai);
        cbxTrangThai.setBounds(20, 320, 260, 30);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái (*)");
        pnLeft.add(lblTrangThai);
        lblTrangThai.setBounds(20, 300, 260, 18);

        pnMain.add(pnLeft);
        pnLeft.setBounds(20, 70, 300, 450);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH LOẠI KHÔNG GIAN");
        pnRight.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 260, 30);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(txtTimKiem);
        txtTimKiem.setBounds(20, 60, 250, 30);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnRight.add(btnTimKiem);
        btnTimKiem.setBounds(280, 60, 90, 30);

        tblLoaiKhongGian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại", "Tên loại", "Sức chứa", "Đơn giá/Giờ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiKhongGian.setRowHeight(30);
        tblLoaiKhongGian.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblLoaiKhongGian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiKhongGianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiKhongGian);

        pnRight.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 450, 330);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnRight.add(btnHuy);
        btnHuy.setBounds(380, 60, 90, 30);

        pnMain.add(pnRight);
        pnRight.setBounds(340, 70, 490, 450);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTrangThaiActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {
        String tenLoai = txtTenLoaiKG.getText().trim();
        String donGiaStr = txtDonGia.getText().trim().replace(",", "");

        if (tenLoai.isEmpty() || donGiaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin bắt buộc!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double donGia = Double.parseDouble(donGiaStr);
            Integer sucChua = txtSucChua.getText().trim().isEmpty() ? null : Integer.parseInt(txtSucChua.getText().trim());

            LoaiKhongGianDTO dto = new LoaiKhongGianDTO();
            dto.setMaLoaiKG(txtMaLoaiKG.getText().trim());
            dto.setTenLoaiKG(tenLoai);
            dto.setSucChua(sucChua);
            dto.setDonGiaTheoGio(donGia);
            dto.setTrangThai(cbxTrangThai.getSelectedItem() != null ? cbxTrangThai.getSelectedItem().toString() : "Đang hoạt động");

            if (controller.themLoai(dto)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                taiDanhSach(null);
                laMoiForm();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Định dạng số không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        String maLoai = txtMaLoaiKG.getText().trim();
        if (maLoai.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại từ bảng!");
            return;
        }

        try {
            LoaiKhongGianDTO dto = new LoaiKhongGianDTO();
            dto.setMaLoaiKG(maLoai);
            dto.setTenLoaiKG(txtTenLoaiKG.getText().trim());
            dto.setSucChua(txtSucChua.getText().trim().isEmpty() ? null : Integer.parseInt(txtSucChua.getText().trim()));
            dto.setDonGiaTheoGio(Double.parseDouble(txtDonGia.getText().trim().replace(",", "")));
            dto.setTrangThai(cbxTrangThai.getSelectedItem() != null ? cbxTrangThai.getSelectedItem().toString() : "Đang hoạt động");

            if (controller.capNhatLoai(dto)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                taiDanhSach(null);
                laMoiForm();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Định dạng số không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        laMoiForm();
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        taiDanhSach(txtTimKiem.getText().trim());
    }

    private void tblLoaiKhongGianMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblLoaiKhongGian.getSelectedRow();
        if (row >= 0) {
            txtMaLoaiKG.setText(tblLoaiKhongGian.getValueAt(row, 0).toString());
            txtTenLoaiKG.setText(tblLoaiKhongGian.getValueAt(row, 1).toString());
            txtSucChua.setText(tblLoaiKhongGian.getValueAt(row, 2).toString().replace("-", ""));
            txtDonGia.setText(tblLoaiKhongGian.getValueAt(row, 3).toString().replace(",", "").replace("-", ""));
            
            Object val = tblLoaiKhongGian.getValueAt(row, 4);
            cbxTrangThai.setSelectedItem(val != null ? val.toString() : "Đang hoạt động");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMaLoaiKG;
    private javax.swing.JLabel lblSucChua;
    private javax.swing.JLabel lblTenLoaiKG;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTable tblLoaiKhongGian;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaLoaiKG;
    private javax.swing.JTextField txtSucChua;
    private javax.swing.JTextField txtTenLoaiKG;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
