/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.wms.view.TrangChu.TrangChuGioiThieu;

/**
 *
 * @author Thinkapd T14s
 */
public class TrangGioiThieuForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(TrangGioiThieuForm.class.getName());

    /**
     * Creates new form TrangGioiThieuForm
     */
    public TrangGioiThieuForm() {
        initComponents();
        showLoginForm(); // Mặc định mở form đăng nhập
    }

    public void showLoginForm() {
        com.wms.view.TrangChu.TrangChuGioiThieu.DangNhap.DangNhapForm loginForm = new com.wms.view.TrangChu.TrangChuGioiThieu.DangNhap.DangNhapForm();
        pnAuthContainer.removeAll();
        pnAuthContainer.add(loginForm, java.awt.BorderLayout.CENTER);
        pnAuthContainer.revalidate();
        pnAuthContainer.repaint();
    }

    public void showRegisterForm() {
        com.wms.view.TrangChu.TrangChuGioiThieu.DangKy.DangKyForm registerForm = new com.wms.view.TrangChu.TrangChuGioiThieu.DangKy.DangKyForm();
        pnAuthContainer.removeAll();
        pnAuthContainer.add(registerForm, java.awt.BorderLayout.CENTER);
        pnAuthContainer.revalidate();
        pnAuthContainer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollMain = new javax.swing.JScrollPane();
        pnContainer = new javax.swing.JPanel();
        pnAuthSection = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        pnAuthContainer = new javax.swing.JPanel();
        pnInfoSection = new javax.swing.JPanel();
        lblInfoMainTitle = new javax.swing.JLabel();
        pnInfoCard = new javax.swing.JPanel();
        lblRichText = new javax.swing.JLabel();
        pnTeamSection = new javax.swing.JPanel();
        lblTeamTitle = new javax.swing.JLabel();
        lblTeamSub = new javax.swing.JLabel();
        pnMember1 = new javax.swing.JPanel();
        lblAva1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblRole1 = new javax.swing.JLabel();
        pnMember2 = new javax.swing.JPanel();
        lblAva2 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblRole2 = new javax.swing.JLabel();
        pnMember3 = new javax.swing.JPanel();
        lblAva3 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblRole3 = new javax.swing.JLabel();
        pnMember4 = new javax.swing.JPanel();
        lblAva4 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        lblRole4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống Quản lý Không gian Spring");
        getContentPane().setLayout(new java.awt.BorderLayout());

        scrollMain.setBorder(null);
        scrollMain.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnContainer.setPreferredSize(new java.awt.Dimension(1200, 1800));
        pnContainer.setLayout(null);

        pnAuthSection.setBackground(new java.awt.Color(245, 246, 250));
        pnAuthSection.setLayout(null);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(235, 94, 141));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("KHÔNG GIAN LÀM VIỆC VÀ HỌC TẬP");
        pnAuthSection.add(lblWelcome);
        lblWelcome.setBounds(0, 40, 1280, 48);

        pnAuthContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnAuthContainer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnAuthContainer.setLayout(new java.awt.BorderLayout());
        pnAuthSection.add(pnAuthContainer);
        pnAuthContainer.setBounds(240, 110, 800, 450);

        pnContainer.add(pnAuthSection);
        pnAuthSection.setBounds(0, 0, 1280, 600);

        pnInfoSection.setBackground(new java.awt.Color(245, 246, 250));
        pnInfoSection.setLayout(null);

        lblInfoMainTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblInfoMainTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblInfoMainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoMainTitle.setText("GIỚI THIỆU HỆ THỐNG");
        pnInfoSection.add(lblInfoMainTitle);
        lblInfoMainTitle.setBounds(0, 40, 1280, 38);

        pnInfoCard.setBackground(new java.awt.Color(255, 255, 255));
        pnInfoCard.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        pnInfoCard.setLayout(null);

        lblRichText.setText(
                "<html><body style='font-family: Segoe UI; padding: 20px; color: #301e23;'><h2 style='color: #eb5e8d; margin-top: 0;'>Hệ thống Quản lý Không gian Làm việc và Học tập (Spring System)</h2><p style='font-size: 14px; line-height: 1.5;'><b>Spring System</b> là giải pháp phần mềm toàn diện giúp số hóa và tự động hóa quy trình vận hành các mô hình Không gian làm việc chung. Hệ thống giải quyết triệt để các hạn chế của quản lý thủ công, mang lại trải nghiệm liền mạch cho khách hàng từ lúc đặt chỗ đến khi thanh toán.</p><h3 style='color: #eb5e8d;'>Các tính năng nổi bật:</h3><ul style='font-size: 14px; line-height: 1.5;'><li><b>Tối ưu Đặt chỗ & Không gian:</b> Trực quan hóa sơ đồ chỗ ngồi, đặt chỗ trực tuyến, cập nhật trạng thái theo thời gian thực.</li><li><b>Trải nghiệm Tiện ích Liền mạch:</b> Gọi đồ uống (F&B), thuê thiết bị và gia hạn thời gian sử dụng ngay tại bàn.</li><li><b>Quản lý Tài chính & Hội viên:</b> Thanh toán tập trung một lần khi ra về, quản lý hạng thành viên, tích điểm và tự động áp dụng mã giảm giá.</li><li><b>Vận hành Chuỗi & Tự động hóa:</b> Báo cáo doanh thu chi tiết, lưu vết giao dịch và sẵn sàng tích hợp kiểm soát cửa bằng mã QR.</li></ul><p style='font-size: 13px; font-style: italic; color: #888888; margin-top: 15px;'>Đề tài được thực hiện bởi nhóm sinh viên lớp HTTT2024.1 - Trường Đại học Công nghệ Thông tin (UIT).<br>Công cụ phát triển: Java Swing, Oracle Database, DataGrip, Netbeans, Lucidchart.</p></body></html>");
        lblRichText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnInfoCard.add(lblRichText);
        lblRichText.setBounds(0, 0, 800, 420);

        pnInfoSection.add(pnInfoCard);
        pnInfoCard.setBounds(240, 100, 800, 420);

        pnContainer.add(pnInfoSection);
        pnInfoSection.setBounds(0, 600, 1280, 600);

        pnTeamSection.setBackground(new java.awt.Color(255, 255, 255));
        pnTeamSection.setLayout(null);

        lblTeamTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTeamTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblTeamTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeamTitle.setText("ĐỘI HÌNH SPRING");
        pnTeamSection.add(lblTeamTitle);
        lblTeamTitle.setBounds(0, 30, 1280, 38);

        lblTeamSub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTeamSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeamSub.setText("Tìm hiểu chi tiết về vai trò, thế mạnh và nhiệm vụ của từng thành viên.");
        pnTeamSection.add(lblTeamSub);
        lblTeamSub.setBounds(0, 70, 1280, 20);

        pnMember1.setBackground(new java.awt.Color(255, 255, 255));
        pnMember1.setLayout(null);

        lblAva1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAva1.setText("[Ảnh Huy]");
        lblAva1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        pnMember1.add(lblAva1);
        lblAva1.setBounds(10, 10, 200, 250);

        lblName1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName1.setText("Lai Mộc Huy");
        pnMember1.add(lblName1);
        lblName1.setBounds(0, 270, 220, 22);

        lblRole1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblRole1.setForeground(new java.awt.Color(235, 94, 141));
        lblRole1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole1.setText("Nhóm trưởng");
        pnMember1.add(lblRole1);
        lblRole1.setBounds(0, 295, 220, 18);

        pnTeamSection.add(pnMember1);
        pnMember1.setBounds(170, 150, 220, 350);

        pnMember2.setBackground(new java.awt.Color(255, 255, 255));
        pnMember2.setLayout(null);

        lblAva2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAva2.setText("[Ảnh Dũng]");
        lblAva2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        pnMember2.add(lblAva2);
        lblAva2.setBounds(10, 10, 200, 250);

        lblName2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName2.setText("Huỳnh Đức Dũng");
        pnMember2.add(lblName2);
        lblName2.setBounds(0, 270, 220, 22);

        lblRole2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblRole2.setForeground(new java.awt.Color(235, 94, 141));
        lblRole2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole2.setText("Nhóm phó");
        pnMember2.add(lblRole2);
        lblRole2.setBounds(0, 295, 220, 18);

        pnTeamSection.add(pnMember2);
        pnMember2.setBounds(410, 150, 220, 350);

        pnMember3.setBackground(new java.awt.Color(255, 255, 255));
        pnMember3.setLayout(null);

        lblAva3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAva3.setText("[Ảnh Duyên]");
        lblAva3.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        pnMember3.add(lblAva3);
        lblAva3.setBounds(10, 10, 200, 250);

        lblName3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName3.setText("Sơn Nguyễn Kỳ Duyên");
        pnMember3.add(lblName3);
        lblName3.setBounds(0, 270, 220, 22);

        lblRole3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblRole3.setForeground(new java.awt.Color(235, 94, 141));
        lblRole3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole3.setText("Thư ký");
        pnMember3.add(lblRole3);
        lblRole3.setBounds(0, 295, 220, 18);

        pnTeamSection.add(pnMember3);
        pnMember3.setBounds(650, 150, 220, 350);

        pnMember4.setBackground(new java.awt.Color(255, 255, 255));
        pnMember4.setLayout(null);

        lblAva4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAva4.setText("[Ảnh Thành Đức]");
        lblAva4.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        pnMember4.add(lblAva4);
        lblAva4.setBounds(10, 10, 200, 250);

        lblName4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName4.setText("Nguyễn Thành Đức");
        pnMember4.add(lblName4);
        lblName4.setBounds(0, 270, 220, 22);

        lblRole4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblRole4.setForeground(new java.awt.Color(235, 94, 141));
        lblRole4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole4.setText("Thành viên");
        pnMember4.add(lblRole4);
        lblRole4.setBounds(0, 295, 220, 18);

        pnTeamSection.add(pnMember4);
        pnMember4.setBounds(890, 150, 220, 350);

        pnContainer.add(pnTeamSection);
        pnTeamSection.setBounds(0, 1200, 1280, 600);

        scrollMain.setViewportView(pnContainer);

        getContentPane().add(scrollMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TrangGioiThieuForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAva1;
    private javax.swing.JLabel lblAva2;
    private javax.swing.JLabel lblAva3;
    private javax.swing.JLabel lblAva4;
    private javax.swing.JLabel lblInfoMainTitle;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblRichText;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblRole2;
    private javax.swing.JLabel lblRole3;
    private javax.swing.JLabel lblRole4;
    private javax.swing.JLabel lblTeamSub;
    private javax.swing.JLabel lblTeamTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnAuthContainer;
    private javax.swing.JPanel pnAuthSection;
    private javax.swing.JPanel pnContainer;
    private javax.swing.JPanel pnInfoCard;
    private javax.swing.JPanel pnInfoSection;
    private javax.swing.JPanel pnMember1;
    private javax.swing.JPanel pnMember2;
    private javax.swing.JPanel pnMember3;
    private javax.swing.JPanel pnMember4;
    private javax.swing.JPanel pnTeamSection;
    private javax.swing.JScrollPane scrollMain;
    // End of variables declaration//GEN-END:variables
}
