/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChu.TrangChuQuanLy.QuanLyThongTinDichVu;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyThongTinDichVuForm extends javax.swing.JPanel {

    private final com.wms.controller.DichVuController controller;
    private javax.swing.table.DefaultTableModel tableModel;
    private java.util.List<com.wms.model.VanHanh_DichVu.LoaiDichVuDTO> dsLoai;

    public QuanLyThongTinDichVuForm() {
        initComponents();
        controller = new com.wms.controller.DichVuController();
        initTable();
        loadLoaiDV();
        loadData(null);
        txtMaDV.setText(generateMaDV());
    }

    private void initTable() {
        tableModel = (javax.swing.table.DefaultTableModel) tblDichVu.getModel();
    }

    private void loadLoaiDV() {
        cbxLoaiDV.removeAllItems();
        cbxLoaiDV.addItem("-- Chọn loại DV --");
        dsLoai = controller.layDanhSachLoai();
        for (com.wms.model.VanHanh_DichVu.LoaiDichVuDTO l : dsLoai) {
            cbxLoaiDV.addItem(l.getTenLoaiDV());
        }
    }

    private void loadData(String tuKhoa) {
        tableModel.setRowCount(0);
        java.util.List<com.wms.model.VanHanh_DichVu.DichVuDTO> list = controller.layDanhSach(null, null, tuKhoa);
        for (com.wms.model.VanHanh_DichVu.DichVuDTO dv : list) {
            tableModel.addRow(new Object[]{
                dv.getMaDV(),
                dv.getTenDV(),
                getTenLoai(dv.getMaLoaiDV()),
                String.format("%,.0f", dv.getDonGia()),
                dv.getTrangThaiDV()
            });
        }
    }

    private String getTenLoai(String maLoai) {
        for (com.wms.model.VanHanh_DichVu.LoaiDichVuDTO l : dsLoai) {
            if (l.getMaLoaiDV().equals(maLoai)) return l.getTenLoaiDV();
        }
        return maLoai;
    }

    private String getMaLoai(String tenLoai) {
        for (com.wms.model.VanHanh_DichVu.LoaiDichVuDTO l : dsLoai) {
            if (l.getTenLoaiDV().equals(tenLoai)) return l.getMaLoaiDV();
        }
        return null;
    }

    private String generateMaDV() {
        return "DV" + System.currentTimeMillis() % 1000000;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        lblAnhDichVu = new javax.swing.JLabel();
        btnDoiAnh = new javax.swing.JButton();
        lblMaDV = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        lblTenDV = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        lblLoaiDV = new javax.swing.JLabel();
        cbxLoaiDV = new javax.swing.JComboBox<>();
        lblDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnQuanLyLoaiDV = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ THÔNG TIN DỊCH VỤ");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        lblAnhDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhDichVu.setText("[Ảnh dịch vụ]");
        lblAnhDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnMain.add(lblAnhDichVu);
        lblAnhDichVu.setBounds(20, 70, 140, 140);

        btnDoiAnh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoiAnh.setForeground(new java.awt.Color(235, 94, 141));
        btnDoiAnh.setText("Chọn ảnh");
        btnDoiAnh.addActionListener(this::btnDoiAnhActionPerformed);
        pnMain.add(btnDoiAnh);
        btnDoiAnh.setBounds(20, 220, 140, 30);

        lblMaDV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaDV.setForeground(new java.awt.Color(35, 30, 48));
        lblMaDV.setText("Mã DV (Tự động)");
        pnMain.add(lblMaDV);
        lblMaDV.setBounds(180, 70, 100, 18);

        txtMaDV.setEditable(false);
        txtMaDV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaDV.setBackground(new java.awt.Color(240, 240, 240));
        pnMain.add(txtMaDV);
        txtMaDV.setBounds(180, 90, 100, 35);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái (*)");
        pnMain.add(lblTrangThai);
        lblTrangThai.setBounds(290, 70, 100, 18);

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Ngừng kinh doanh" }));
        pnMain.add(cbxTrangThai);
        cbxTrangThai.setBounds(290, 90, 100, 35);

        lblTenDV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenDV.setForeground(new java.awt.Color(35, 30, 48));
        lblTenDV.setText("Tên dịch vụ (*)");
        pnMain.add(lblTenDV);
        lblTenDV.setBounds(180, 140, 210, 18);

        txtTenDV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTenDV);
        txtTenDV.setBounds(180, 160, 210, 35);

        lblLoaiDV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoaiDV.setForeground(new java.awt.Color(35, 30, 48));
        lblLoaiDV.setText("Loại dịch vụ (*)");
        pnMain.add(lblLoaiDV);
        lblLoaiDV.setBounds(180, 210, 210, 18);

        cbxLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxLoaiDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Chọn loại DV --", "Nước uống", "Thức ăn nhẹ" }));
        pnMain.add(cbxLoaiDV);
        cbxLoaiDV.setBounds(180, 230, 210, 35);

        lblDonGia.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDonGia.setForeground(new java.awt.Color(35, 30, 48));
        lblDonGia.setText("Đơn giá (VNĐ) (*)");
        pnMain.add(lblDonGia);
        lblDonGia.setBounds(20, 280, 370, 18);

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtDonGia);
        txtDonGia.setBounds(20, 300, 370, 35);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnMain.add(btnThemMoi);
        btnThemMoi.setBounds(20, 360, 180, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnMain.add(btnCapNhat);
        btnCapNhat.setBounds(210, 360, 180, 40);

        btnQuanLyLoaiDV.setBackground(new java.awt.Color(35, 30, 48));
        btnQuanLyLoaiDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyLoaiDV.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyLoaiDV.setText("Q.Lý Loại Dịch vụ");
        btnQuanLyLoaiDV.addActionListener(this::btnQuanLyLoaiDVActionPerformed);
        pnMain.add(btnQuanLyLoaiDV);
        btnQuanLyLoaiDV.setBounds(20, 415, 180, 40);

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(235, 94, 141));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnMain.add(btnHuy);
        btnHuy.setBounds(210, 415, 180, 40);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm Tên/Mã:");
        pnMain.add(lblTimKiem);
        lblTimKiem.setBounds(420, 80, 130, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnMain.add(txtTimKiem);
        txtTimKiem.setBounds(550, 80, 350, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnMain.add(btnTimKiem);
        btnTimKiem.setBounds(920, 80, 100, 35);

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã DV", "Tên dịch vụ", "Loại dịch vụ", "Đơn giá", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichVu.setRowHeight(30);
        tblDichVu.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDichVu);

        pnMain.add(jScrollPane1);
        jScrollPane1.setBounds(420, 130, 600, 480);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiAnhActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        if (chooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            String path = chooser.getSelectedFile().getAbsolutePath();
            lblAnhDichVu.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(path).getImage().getScaledInstance(140, 140, java.awt.Image.SCALE_SMOOTH)));
            lblAnhDichVu.setText("");
            lblAnhDichVu.putClientProperty("path", path);
        }
    }

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (txtTenDV.getText().isEmpty() || txtDonGia.getText().isEmpty() || cbxLoaiDV.getSelectedIndex() <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                return;
            }
            com.wms.model.VanHanh_DichVu.DichVuDTO dv = new com.wms.model.VanHanh_DichVu.DichVuDTO();
            dv.setMaDV(txtMaDV.getText());
            dv.setTenDV(txtTenDV.getText());
            dv.setMaLoaiDV(getMaLoai(cbxLoaiDV.getSelectedItem().toString()));
            dv.setDonGia(Double.parseDouble(txtDonGia.getText().replace(",", "")));
            dv.setTrangThaiDV(cbxTrangThai.getSelectedItem().toString());
            Object path = lblAnhDichVu.getClientProperty("path");
            dv.setHinhAnh(path != null ? path.toString() : null);

            if (controller.themMoi(dv)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Thêm dịch vụ thành công!");
                loadData(null);
                btnHuyActionPerformed(null);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            com.wms.model.VanHanh_DichVu.DichVuDTO dv = new com.wms.model.VanHanh_DichVu.DichVuDTO();
            dv.setMaDV(txtMaDV.getText());
            dv.setTenDV(txtTenDV.getText());
            dv.setDonGia(Double.parseDouble(txtDonGia.getText().replace(",", "")));
            dv.setTrangThaiDV(cbxTrangThai.getSelectedItem().toString());

            if (controller.capNhat(dv)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                loadData(null);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }

    private void btnQuanLyLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof java.awt.Frame) {
            QuanLyLoaiDichVuForm dialog = new QuanLyLoaiDichVuForm((java.awt.Frame) parentWindow, true);
            dialog.setVisible(true);
            loadLoaiDV(); // Refresh combobox after dialog close
        }
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        txtMaDV.setText(generateMaDV());
        txtTenDV.setText("");
        txtDonGia.setText("");
        cbxLoaiDV.setSelectedIndex(0);
        cbxTrangThai.setSelectedIndex(0);
        lblAnhDichVu.setIcon(null);
        lblAnhDichVu.setText("[Ảnh dịch vụ]");
        tblDichVu.clearSelection();
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        loadData(txtTimKiem.getText());
    }

    private void tblDichVuMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblDichVu.getSelectedRow();
        if (row >= 0) {
            txtMaDV.setText(tableModel.getValueAt(row, 0).toString());
            txtTenDV.setText(tableModel.getValueAt(row, 1).toString());
            cbxLoaiDV.setSelectedItem(tableModel.getValueAt(row, 2).toString());
            txtDonGia.setText(tableModel.getValueAt(row, 3).toString().replace(".", ""));
            cbxTrangThai.setSelectedItem(tableModel.getValueAt(row, 4).toString());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDoiAnh;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnQuanLyLoaiDV;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxLoaiDV;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnhDichVu;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblLoaiDV;
    private javax.swing.JLabel lblMaDV;
    private javax.swing.JLabel lblTenDV;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
