package com.wms.view.TrangChuHoiVien.DatChoKhongGian.XacNhan;

import com.wms.controller.TrangChuGioiThieu.DangNhapController;

import com.wms.dao.TrangChuQuanLy.QuanLyPhien.PhienLamViecDAO;
import com.wms.model.TrangChuQuanLy.QuanLyNguoiDung.NguoiDungDTO;

import com.wms.dao.TrangChuQuanLy.QuanLyHoaDon.HoaDonDAO;

import com.wms.dao.TrangChuQuanLy.QuanLyHoiVien.KhachHangDAO;
import com.wms.dao.TrangChuQuanLy.QuanLyPhien.DatChoDAO;
import com.wms.model.TrangChuQuanLy.QuanLyPhien.PhienLamViecDTO;
import com.wms.model.TrangChuHoiVien.DatChoDTO;
import com.wms.model.TrangChuQuanLy.QuanLyHoaDon.HoaDonDTO;

import java.text.DecimalFormat;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author kyduy
 */
public class ChuyenKhoanDatTruoc extends javax.swing.JPanel {
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(ChuyenKhoanDatTruoc.class.getName());

    private double tongTienBanDau = 0;
    private double thanhTien = 0;
    private String maKG_Booking;
    private final DecimalFormat df = new DecimalFormat("#,### VNĐ",
            java.text.DecimalFormatSymbols.getInstance(new java.util.Locale("vi", "VN")));

    public ChuyenKhoanDatTruoc() {
        initComponents();
        loadThongTinKhachHang();
    }

    public ChuyenKhoanDatTruoc(String maCN, String tenCN, String maKG, String tenKG, String ngayDat, String gioBD, String gioKT, double tongTien) {
        initComponents();
        this.maKG_Booking = maKG;
        this.tongTienBanDau = tongTien;
        this.thanhTien = tongTien;

        txtChiNhanh.setText(tenCN);
        txtKhongGian.setText(tenKG);
        txtNgay.setText(ngayDat);
        txtBatDau.setText(gioBD);
        txtKetThuc.setText(gioKT);

        capNhatHienThiTien();
        loadThongTinKhachHang();
    }

    private void loadThongTinKhachHang() {
        NguoiDungDTO user = DangNhapController.getCurrentUser();
        if (user != null) {
            txtTenKH.setText(user.getTenTaiKhoan()); // Hoặc lấy Họ tên nếu có mapping
            txtSDT.setText(user.getSdt());
        }
    }

    private void capNhatHienThiTien() {
        txtTienTruocGiam.setText(df.format(tongTienBanDau));
        txtThanhTien.setText(df.format(thanhTien));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeaderTitle = new javax.swing.JLabel();
        pnLeftInfo = new javax.swing.JPanel();
        lblInfoTitle = new javax.swing.JLabel();
        lblTenKH = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblChiNhanh = new javax.swing.JLabel();
        txtChiNhanh = new javax.swing.JTextField();
        lblKhongGian = new javax.swing.JLabel();
        txtKhongGian = new javax.swing.JTextField();
        lblNgay = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        lblGio = new javax.swing.JLabel();
        txtBatDau = new javax.swing.JTextField();
        lblGhiChu = new javax.swing.JLabel();
        scrollGhiChu = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnQuayLai = new javax.swing.JButton();
        lblGio1 = new javax.swing.JLabel();
        txtKetThuc = new javax.swing.JTextField();
        pnRightPayment = new javax.swing.JPanel();
        lblPayTitle = new javax.swing.JLabel();
        lblTienTruocGiam = new javax.swing.JLabel();
        txtTienTruocGiam = new javax.swing.JLabel();
        lblMaGiamGia = new javax.swing.JLabel();
        txtMaGiamGia = new javax.swing.JTextField();
        btnApDung = new javax.swing.JButton();
        lblTienGiam = new javax.swing.JLabel();
        txtTienGiam = new javax.swing.JLabel();
        pnLine = new javax.swing.JPanel();
        lblThanhTien = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JLabel();
        lblQRTitle = new javax.swing.JLabel();
        lblQRCode = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 240, 245));
        setPreferredSize(new java.awt.Dimension(1050, 640));
        setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(232, 85, 136));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("XÁC NHẬN THÔNG TIN & THANH TOÁN");
        add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 20, 1050, 40);

        pnLeftInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnLeftInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 205, 224), 2));
        pnLeftInfo.setLayout(null);

        lblInfoTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInfoTitle.setForeground(new java.awt.Color(0, 0, 58));
        lblInfoTitle.setText("THÔNG TIN KHÁCH HÀNG & ĐẶT CHỖ");
        pnLeftInfo.add(lblInfoTitle);
        lblInfoTitle.setBounds(30, 20, 400, 30);

        lblTenKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenKH.setForeground(new java.awt.Color(0, 0, 58));
        lblTenKH.setText("Họ và tên khách hàng");
        pnLeftInfo.add(lblTenKH);
        lblTenKH.setBounds(30, 70, 230, 20);

        txtTenKH.setEditable(false);
        txtTenKH.setBackground(new java.awt.Color(255, 240, 245));
        txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnLeftInfo.add(txtTenKH);
        txtTenKH.setBounds(30, 95, 230, 35);

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(0, 0, 58));
        lblSDT.setText("Số điện thoại");
        pnLeftInfo.add(lblSDT);
        lblSDT.setBounds(290, 70, 230, 20);

        txtSDT.setEditable(false);
        txtSDT.setBackground(new java.awt.Color(255, 240, 245));
        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnLeftInfo.add(txtSDT);
        txtSDT.setBounds(290, 95, 230, 35);

        lblChiNhanh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChiNhanh.setForeground(new java.awt.Color(0, 0, 58));
        lblChiNhanh.setText("Tại Chi nhánh");
        pnLeftInfo.add(lblChiNhanh);
        lblChiNhanh.setBounds(30, 145, 490, 20);

        txtChiNhanh.setEditable(false);
        txtChiNhanh.setBackground(new java.awt.Color(255, 240, 245));
        txtChiNhanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnLeftInfo.add(txtChiNhanh);
        txtChiNhanh.setBounds(30, 170, 490, 35);

        lblKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhongGian.setForeground(new java.awt.Color(0, 0, 58));
        lblKhongGian.setText("Không gian sử dụng");
        pnLeftInfo.add(lblKhongGian);
        lblKhongGian.setBounds(30, 220, 210, 20);

        txtKhongGian.setEditable(false);
        txtKhongGian.setBackground(new java.awt.Color(255, 240, 245));
        txtKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtKhongGian.setForeground(new java.awt.Color(232, 85, 136));
        pnLeftInfo.add(txtKhongGian);
        txtKhongGian.setBounds(30, 250, 230, 35);

        lblNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(0, 0, 58));
        lblNgay.setText("Ngày sử dụng");
        pnLeftInfo.add(lblNgay);
        lblNgay.setBounds(290, 220, 230, 20);

        txtNgay.setEditable(false);
        txtNgay.setBackground(new java.awt.Color(255, 240, 245));
        txtNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnLeftInfo.add(txtNgay);
        txtNgay.setBounds(290, 250, 230, 35);

        lblGio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGio.setForeground(new java.awt.Color(0, 0, 58));
        lblGio.setText("Đến khung giờ");
        pnLeftInfo.add(lblGio);
        lblGio.setBounds(290, 295, 230, 20);

        txtBatDau.setEditable(false);
        txtBatDau.setBackground(new java.awt.Color(255, 240, 245));
        txtBatDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnLeftInfo.add(txtBatDau);
        txtBatDau.setBounds(30, 320, 230, 35);

        lblGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(0, 0, 58));
        lblGhiChu.setText("Ghi chú bổ sung (Tùy chọn)");
        pnLeftInfo.add(lblGhiChu);
        lblGhiChu.setBounds(30, 370, 490, 20);

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGhiChu.setRows(3);
        scrollGhiChu.setViewportView(txtGhiChu);

        pnLeftInfo.add(scrollGhiChu);
        scrollGhiChu.setBounds(30, 395, 490, 55);

        btnQuayLai.setBackground(new java.awt.Color(232, 85, 136));
        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        btnQuayLai.setText("<< Quay lại tùy chỉnh Sơ đỒ");
        btnQuayLai.addActionListener(this::btnQuayLaiActionPerformed);
        pnLeftInfo.add(btnQuayLai);
        btnQuayLai.setBounds(30, 465, 490, 40);

        lblGio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGio1.setForeground(new java.awt.Color(0, 0, 58));
        lblGio1.setText("Từ khung giờ");
        lblGio1.setMaximumSize(new java.awt.Dimension(97, 20));
        lblGio1.setMinimumSize(new java.awt.Dimension(97, 20));
        lblGio1.setPreferredSize(new java.awt.Dimension(97, 20));
        pnLeftInfo.add(lblGio1);
        lblGio1.setBounds(30, 295, 230, 20);

        txtKetThuc.setEditable(false);
        txtKetThuc.setBackground(new java.awt.Color(255, 240, 245));
        txtKetThuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnLeftInfo.add(txtKetThuc);
        txtKetThuc.setBounds(290, 320, 230, 35);

        add(pnLeftInfo);
        pnLeftInfo.setBounds(40, 80, 550, 520);

        pnRightPayment.setBackground(new java.awt.Color(255, 255, 255));
        pnRightPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 205, 224), 2));
        pnRightPayment.setLayout(null);

        lblPayTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPayTitle.setForeground(new java.awt.Color(0, 0, 58));
        lblPayTitle.setText("CHI TIẾT THANH TOÁN");
        pnRightPayment.add(lblPayTitle);
        lblPayTitle.setBounds(30, 20, 330, 30);

        lblTienTruocGiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTienTruocGiam.setForeground(new java.awt.Color(0, 0, 58));
        lblTienTruocGiam.setText("Tổng tiền dịch vụ:");
        pnRightPayment.add(lblTienTruocGiam);
        lblTienTruocGiam.setBounds(30, 70, 140, 20);

        txtTienTruocGiam.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTienTruocGiam.setForeground(new java.awt.Color(0, 0, 58));
        txtTienTruocGiam.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtTienTruocGiam.setText("0 VNĐ");
        pnRightPayment.add(txtTienTruocGiam);
        txtTienTruocGiam.setBounds(180, 70, 180, 21);

        lblMaGiamGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaGiamGia.setForeground(new java.awt.Color(0, 0, 58));
        lblMaGiamGia.setText("Mã giảm giá (nếu có):");
        pnRightPayment.add(lblMaGiamGia);
        lblMaGiamGia.setBounds(30, 110, 330, 20);

        txtMaGiamGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRightPayment.add(txtMaGiamGia);
        txtMaGiamGia.setBounds(30, 135, 200, 35);

        btnApDung.setBackground(new java.awt.Color(0, 0, 58));
        btnApDung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApDung.setForeground(new java.awt.Color(255, 255, 255));
        btnApDung.setText("Áp dụng");
        btnApDung.addActionListener(this::btnApDungActionPerformed);
        pnRightPayment.add(btnApDung);
        btnApDung.setBounds(240, 135, 120, 35);

        lblTienGiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTienGiam.setForeground(new java.awt.Color(0, 0, 58));
        lblTienGiam.setText("Khuyến mãi:");
        pnRightPayment.add(lblTienGiam);
        lblTienGiam.setBounds(30, 195, 140, 20);

        txtTienGiam.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTienGiam.setForeground(new java.awt.Color(232, 85, 136));
        txtTienGiam.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtTienGiam.setText("- 0 VNĐ");
        pnRightPayment.add(txtTienGiam);
        txtTienGiam.setBounds(180, 195, 180, 21);

        pnLine.setBackground(new java.awt.Color(252, 205, 224));
        pnRightPayment.add(pnLine);
        pnLine.setBounds(30, 235, 330, 2);

        lblThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblThanhTien.setForeground(new java.awt.Color(0, 0, 58));
        lblThanhTien.setText("THÀNH TIỀN:");
        pnRightPayment.add(lblThanhTien);
        lblThanhTien.setBounds(30, 260, 140, 30);

        txtThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtThanhTien.setForeground(new java.awt.Color(232, 85, 136));
        txtThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtThanhTien.setText("0 VNĐ");
        pnRightPayment.add(txtThanhTien);
        txtThanhTien.setBounds(160, 255, 200, 40);

        lblQRTitle.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblQRTitle.setForeground(new java.awt.Color(0, 0, 58));
        lblQRTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQRTitle.setText("Quét mã QR đỂ thanh toán trước");
        pnRightPayment.add(lblQRTitle);
        lblQRTitle.setBounds(30, 305, 330, 16);

        lblQRCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQRCode.setText("[QR Code Placeholder]");
        lblQRCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 205, 224)));
        pnRightPayment.add(lblQRCode);
        lblQRCode.setBounds(125, 325, 140, 130);

        btnXacNhan.setBackground(new java.awt.Color(232, 85, 136));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận & Hoàn tất");
        btnXacNhan.addActionListener(this::btnXacNhanActionPerformed);
        pnRightPayment.add(btnXacNhan);
        btnXacNhan.setBounds(30, 465, 330, 40);

        add(pnRightPayment);
        pnRightPayment.setBounds(620, 80, 390, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void btnApDungActionPerformed(java.awt.event.ActionEvent evt) {
        String code = txtMaGiamGia.getText().trim();
        if (code.isEmpty()) return;
        
        // Logic áp dụng mã giảm giá có thể thêm ở đây
        JOptionPane.showMessageDialog(this, "Tính năng đang được phát triển!");
    }

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window instanceof com.wms.view.TrangChuHoiVien.TrangChuHoiVienForm) {
            ((com.wms.view.TrangChuHoiVien.TrangChuHoiVienForm) window).showPanel(new com.wms.view.TrangChuHoiVien.DatChoKhongGian.XemChiNhanh.XemChiNhanhForm()
            );
        }
    }

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {
        NguoiDungDTO user = DangNhapController.getCurrentUser();
        if (user == null) {
            JOptionPane.showMessageDialog(this, "Bạn cần đăng nhập để thực hiện đặt chỗ!");
            return;
        }

        KhachHangDAO khDAO = new KhachHangDAO();
        String maKH = khDAO.timMaKHTheoMaND(user.getMaND());
        if (maKH == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin hội viên của bạn!");
            return;
        }

        int res = JOptionPane.showConfirmDialog(this, "Xác nhận đặt chỗ và thanh toán?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (res != JOptionPane.YES_OPTION) return;

        try {
            // 1. Tạo Đơn đặt chỗ (DATCHO)
            DatChoDTO dc = new DatChoDTO();
            dc.setMaKH(maKH);
            dc.setMaKG(maKG_Booking);
            dc.setThanhTien(thanhTien);
            dc.setGhiChu(txtGhiChu.getText());
            dc.setTrangThaiDatTruoc("Đang chờ thanh toán");
            dc.setThoiGianDat(new Timestamp(System.currentTimeMillis()));
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
            LocalDateTime batDau = LocalDateTime.parse(txtNgay.getText() + " " + txtBatDau.getText(), dtf);
            dc.setThoiGianDuKienToi(Timestamp.valueOf(batDau));

            DatChoDAO dcDAO = new DatChoDAO();
            if (!dcDAO.taoDatChoMoi(dc)) {
                JOptionPane.showMessageDialog(this, "Lỗi khi lưu đơn đặt chỗ!");
                return;
            }
            String maDatCho = dc.getMaDatCho();

            // 2. Tạo Phiên làm việc (Liên kết với MaDatCho)
            PhienLamViecDTO phien = new PhienLamViecDTO();
            phien.setMaKH(maKH);
            phien.setMaKG(maKG_Booking);
            phien.setMaDatCho(maDatCho); // QUAN TRỌNG: Gán mã đặt chỗ vào đây
            phien.setTrangThaiPhien("Đã đặt trước");
            
            phien.setThoiGianBatDau(Timestamp.valueOf(batDau));
            LocalDateTime ketThuc = LocalDateTime.parse(txtNgay.getText() + " " + txtKetThuc.getText(), dtf);
            phien.setThoiGianDuKienKetThuc(Timestamp.valueOf(ketThuc));

            PhienLamViecDAO pDAO = new PhienLamViecDAO();
            if (pDAO.taoPhienLamViecMoi(phien)) {
                String maPhien = phien.getMaPhien();
                // 3. Tạo Hóa đơn
                HoaDonDTO hd = new HoaDonDTO();
                hd.setMaPhien(maPhien);
                hd.setTongTien(tongTienBanDau);
                hd.setThanhTien(thanhTien);
                hd.setTrangThaiThanhToan("Đang chờ thanh toán");

                HoaDonDAO hDAO = new HoaDonDAO();
                HoaDonDTO hoaDonDaTao = hDAO.capNhatHoaDonDatTruocTheoPhien(maPhien, tongTienBanDau, thanhTien);
                if (hoaDonDaTao == null && hDAO.taoHoaDonMoi(hd)) {
                    hoaDonDaTao = hd;
                }
                if (hoaDonDaTao != null) {
                    hd = hoaDonDaTao;
                    String maHD = hd.getMaHoaDon();
                    // 3. Chuyển sang màn hình thành công
                    String htmlDetails = String.format("<html>" +
                        "<b>Mã hóa đơn:</b> %s<br/>" +
                        "<b>Không gian:</b> %s<br/>" +
                        "<b>Thời gian:</b> %s - %s<br/>" +
                        "<b>Ngày:</b> %s<br/>" +
                        "<b>Tổng tiền:</b> %s</html>",
                        maHD, txtKhongGian.getText(), txtBatDau.getText(), txtKetThuc.getText(), txtNgay.getText(), df.format(thanhTien));
                    
                    java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
                    if (window instanceof com.wms.view.TrangChuHoiVien.TrangChuHoiVienForm) {
                        ((com.wms.view.TrangChuHoiVien.TrangChuHoiVienForm) window).showPanel(
                            new ThongTinSauThanhToan(htmlDetails, hd)
                        );
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi khi tạo phiên đặt chỗ!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            com.wms.util.MessageUtil.showError(this, "Lỗi xử lý đặt chỗ.", e);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChuyenKhoanDatTruoc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApDung;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel lblChiNhanh;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblGio1;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblInfoTitle;
    private javax.swing.JLabel lblKhongGian;
    private javax.swing.JLabel lblMaGiamGia;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblPayTitle;
    private javax.swing.JLabel lblQRCode;
    private javax.swing.JLabel lblQRTitle;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblThanhTien;
    private javax.swing.JLabel lblTienGiam;
    private javax.swing.JLabel lblTienTruocGiam;
    private javax.swing.JPanel pnLeftInfo;
    private javax.swing.JPanel pnLine;
    private javax.swing.JPanel pnRightPayment;
    private javax.swing.JScrollPane scrollGhiChu;
    private javax.swing.JTextField txtBatDau;
    private javax.swing.JTextField txtChiNhanh;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtKetThuc;
    private javax.swing.JTextField txtKhongGian;
    private javax.swing.JTextField txtMaGiamGia;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JLabel txtThanhTien;
    private javax.swing.JLabel txtTienGiam;
    private javax.swing.JLabel txtTienTruocGiam;
    // End of variables declaration//GEN-END:variables

}






