/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyNguoiDung;

import com.wms.view.TrangChuQuanLy.TrangChuQuanLyForm;
import com.wms.view.TrangChuQuanLy.QuanLyVaiTro.QuanLyVaiTroForm;
import javax.swing.SwingUtilities;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyNguoiDungForm extends javax.swing.JPanel {
    private com.wms.controller.TrangChuQuanLy.QuanLyNguoiDung.NguoiDungController controller;

    /**
     * Creates new form QuanLyNguoiDungForm
     */
    public QuanLyNguoiDungForm() {
        initComponents();
        controller = new com.wms.controller.TrangChuQuanLy.QuanLyNguoiDung.NguoiDungController(this);
        setupEvents();
        customInit();
        com.wms.util.TienIchFormQuanLy.apDung(this);
    }

    private void customInit() {
        txtMaND.setEditable(false);
        // Mở khóa để nhập khi tạo mới
        txtTaiKhoan.setEditable(true);
        com.wms.util.DateInputUtil.attachDatePicker(txtNgaySinh);
    }

    private void setupEvents() {
        btnThem.addActionListener(e -> controller.handleAdd());
        btnCapNhat.addActionListener(e -> controller.handleUpdate());
        btnLamMoi.addActionListener(e -> {
            controller.clearForm();
            controller.search(txtTimKiem.getText().trim());
        });
        btnTimKiem.addActionListener(e -> controller.search(txtTimKiem.getText()));
        txtTimKiem.addActionListener(e -> controller.search(txtTimKiem.getText()));

        tblNguoiDung.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                controller.displaySelectedUser();
            }
        });

        btnDoiAnh.addActionListener(e -> controller.handleChangeImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiDung = new javax.swing.JTable();
        pnRight = new javax.swing.JPanel();
        lblMaND = new javax.swing.JLabel();
        txtMaND = new javax.swing.JTextField();
        lblTaiKhoan = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        cbxGioiTinh = new javax.swing.JComboBox<>();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        lblAnhDaiDien = new javax.swing.JLabel();
        btnDoiAnh = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JTextField();
        lblNgaySinh1 = new javax.swing.JLabel();
        cbxNhomQuyen = new javax.swing.JComboBox<>();
        lblNhomQuyen = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ NGƯỜI DÙNG HỆ THỐNG");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH TÀI KHOẢN");
        pnLeft.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 250, 30);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm (Tên/Tài khoản):");
        pnLeft.add(lblTimKiem);
        lblTimKiem.setBounds(20, 55, 180, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtTimKiem);
        txtTimKiem.setBounds(200, 55, 270, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        pnLeft.add(btnTimKiem);
        btnTimKiem.setBounds(480, 55, 90, 35);

        tblNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã ND", "Họ tên", "Tài khoản", "Giới tính", "SĐT", "Email", "Trạng thái"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblNguoiDung.setRowHeight(35);
        tblNguoiDung.setSelectionBackground(new java.awt.Color(235, 94, 141));
        jScrollPane1.setViewportView(tblNguoiDung);

        pnLeft.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 550, 410);

        pnMain.add(pnLeft);
        pnLeft.setBounds(440, 70, 590, 540);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblMaND.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaND.setForeground(new java.awt.Color(35, 30, 48));
        lblMaND.setText("Mã người dùng");
        pnRight.add(lblMaND);
        lblMaND.setBounds(150, 20, 110, 20);

        txtMaND.setEditable(false);
        txtMaND.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaND.setBackground(new java.awt.Color(240, 240, 240));
        pnRight.add(txtMaND);
        txtMaND.setBounds(150, 40, 110, 30);

        lblTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(35, 30, 48));
        lblTaiKhoan.setText("Tên tài khoản");
        pnRight.add(lblTaiKhoan);
        lblTaiKhoan.setBounds(20, 260, 170, 20);

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(txtTaiKhoan);
        txtTaiKhoan.setBounds(20, 280, 170, 30);

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHoTen.setForeground(new java.awt.Color(35, 30, 48));
        lblHoTen.setText("Họ và tên (*)");
        pnRight.add(lblHoTen);
        lblHoTen.setBounds(150, 80, 230, 20);

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(txtHoTen);
        txtHoTen.setBounds(150, 100, 230, 30);

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(35, 30, 48));
        lblGioiTinh.setText("Giới tính");
        pnRight.add(lblGioiTinh);
        lblGioiTinh.setBounds(270, 20, 110, 20);

        cbxGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        pnRight.add(cbxGioiTinh);
        cbxGioiTinh.setBounds(270, 40, 110, 30);

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(35, 30, 48));
        lblNgaySinh.setText("Ngày sinh");
        pnRight.add(lblNgaySinh);
        lblNgaySinh.setBounds(210, 320, 170, 20);

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNgaySinh.setToolTipText("dd/MM/yyyy");
        pnRight.add(txtNgaySinh);
        txtNgaySinh.setBounds(210, 340, 170, 30);

        lblSDT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSDT.setForeground(new java.awt.Color(35, 30, 48));
        lblSDT.setText("Số điện thoại (*)");
        pnRight.add(lblSDT);
        lblSDT.setBounds(150, 140, 230, 20);

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(txtSDT);
        txtSDT.setBounds(150, 160, 230, 30);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(35, 30, 48));
        lblEmail.setText("Email (*)");
        pnRight.add(lblEmail);
        lblEmail.setBounds(150, 200, 230, 20);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(txtEmail);
        txtEmail.setBounds(150, 220, 230, 30);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái tài khoản");
        pnRight.add(lblTrangThai);
        lblTrangThai.setBounds(20, 320, 170, 20);

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Đã khóa" }));
        pnRight.add(cbxTrangThai);
        cbxTrangThai.setBounds(20, 340, 170, 30);

        lblNhomQuyen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNhomQuyen.setForeground(new java.awt.Color(35, 30, 48));
        lblNhomQuyen.setText("Nhóm quyền / Vai trò");
        pnRight.add(lblNhomQuyen);
        lblNhomQuyen.setBounds(20, 380, 170, 20);

        cbxNhomQuyen.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(cbxNhomQuyen);
        cbxNhomQuyen.setBounds(20, 400, 360, 30);

        btnThem.setBackground(new java.awt.Color(235, 94, 141));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm mới");
        pnRight.add(btnThem);
        btnThem.setBounds(20, 440, 170, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        pnRight.add(btnCapNhat);
        btnCapNhat.setBounds(210, 440, 170, 40);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(235, 94, 141));
        btnLamMoi.setText("Làm mới form");
        pnRight.add(btnLamMoi);
        btnLamMoi.setBounds(20, 490, 360, 40);

        lblAnhDaiDien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhDaiDien.setText("[Ảnh 3x4]");
        lblAnhDaiDien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnRight.add(lblAnhDaiDien);
        lblAnhDaiDien.setBounds(10, 40, 130, 160);

        btnDoiAnh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoiAnh.setForeground(new java.awt.Color(235, 94, 141));
        btnDoiAnh.setText("Đổi ảnh");
        btnDoiAnh.addActionListener(this::btnDoiAnhActionPerformed);
        pnRight.add(btnDoiAnh);
        btnDoiAnh.setBounds(10, 210, 130, 30);

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMatKhau.setToolTipText("dd/MM/yyyy");
        txtMatKhau.addActionListener(this::txtMatKhauActionPerformed);
        pnRight.add(txtMatKhau);
        txtMatKhau.setBounds(210, 280, 170, 30);

        lblNgaySinh1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNgaySinh1.setForeground(new java.awt.Color(35, 30, 48));
        lblNgaySinh1.setText("Mật khẩu");
        pnRight.add(lblNgaySinh1);
        lblNgaySinh1.setBounds(210, 260, 170, 20);

        pnMain.add(pnRight);
        pnRight.setBounds(20, 70, 400, 540);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void btnDoiAnhActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDoiAnhActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnDoiAnhActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtMatKhauActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDoiAnh;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxGioiTinh;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnhDaiDien;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMaND;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgaySinh1;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTable tblNguoiDung;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaND;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JComboBox<String> cbxNhomQuyen;
    private javax.swing.JLabel lblNhomQuyen;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTblNguoiDung() {
        return tblNguoiDung;
    }

    public javax.swing.JTextField getTxtMaND() {
        return txtMaND;
    }

    public javax.swing.JTextField getTxtTaiKhoan() {
        return txtTaiKhoan;
    }

    public javax.swing.JTextField getTxtHoTen() {
        return txtHoTen;
    }

    public javax.swing.JComboBox<String> getCbxGioiTinh() {
        return cbxGioiTinh;
    }

    public javax.swing.JTextField getTxtNgaySinh() {
        return txtNgaySinh;
    }

    public javax.swing.JTextField getTxtSDT() {
        return txtSDT;
    }

    public javax.swing.JTextField getTxtEmail() {
        return txtEmail;
    }

    public javax.swing.JComboBox<String> getCbxTrangThai() {
        return cbxTrangThai;
    }

    public javax.swing.JComboBox<String> getCbxNhomQuyen() {
        return cbxNhomQuyen;
    }

    public javax.swing.JLabel getLblAnhDaiDien() {
        return lblAnhDaiDien;
    }

    public javax.swing.JTextField getTxtMatKhau() {
        return txtMatKhau;
    }

    public javax.swing.JTextField getTxtTimKiem() {
        return txtTimKiem;
    }
}
