package com.wms.view.TrangChuQuanLy.QuanLyNguoiDung;

import com.wms.controller.TrangChuQuanLy.QuanLyNhanVien.QuanLyNhanVienController;
import com.wms.model.TrangChuQuanLy.QuanLyNhanVien.VaiTroDTO;
import com.wms.model.TrangChuQuanLy.QuanLyNhanVien.ChucNangDTO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;

public class QuanLyVaiTroForm extends javax.swing.JDialog {
    private final QuanLyNhanVienController controller = new QuanLyNhanVienController();
    private String maVaiTroDangChon = null;
    private final List<VaiTroDTO> danhSachVaiTro = new ArrayList<>();
    private final List<ChucNangDTO> danhSachChucNang = new ArrayList<>();

    public QuanLyVaiTroForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadCbxChucNang();
        loadDanhSachVaiTro();
        pack();
        setLocationRelativeTo(parent);
    }

    private void loadDanhSachVaiTro() {
        DefaultTableModel model = (DefaultTableModel) tblNhomQuyen.getModel();
        model.setRowCount(0);
        danhSachVaiTro.clear();
        List<VaiTroDTO> list = controller.layDanhSachVaiTroNhanVien();
        danhSachVaiTro.addAll(list);
        for (VaiTroDTO vt : list) {
            model.addRow(new Object[] { vt.getMaVaiTro(), vt.getTenVaiTro() });
        }
    }

    private void loadCbxChucNang() {
        cbxChucNang.removeAllItems();
        danhSachChucNang.clear();
        List<ChucNangDTO> list = controller.layTatCaChucNang();
        danhSachChucNang.addAll(list);
        for (ChucNangDTO cn : list) {
            cbxChucNang.addItem(cn.getTenChucNang());
        }
    }

    private void loadChucNangCuaVaiTro(String maVaiTro) {
        DefaultTableModel model = (DefaultTableModel) tblChucNangDaChon.getModel();
        model.setRowCount(0);
        List<String[]> list = controller.layChucNangCuaVaiTro(maVaiTro);
        for (String[] cn : list) {
            model.addRow(new Object[] { cn[0], cn[1] });
        }
    }

    private void lamMoiPanel() {
        maVaiTroDangChon = null;
        txtTenNhom.setText("");
        txtMoTa.setText("");
        ((DefaultTableModel) tblChucNangDaChon.getModel()).setRowCount(0);
        tblNhomQuyen.clearSelection();
    }

    private List<String> layDanhSachMaCNTuBang() {
        List<String> list = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tblChucNangDaChon.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            list.add((String) model.getValueAt(i, 0));
        }
        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        scrollNhomQuyen = new javax.swing.JScrollPane();
        tblNhomQuyen = new javax.swing.JTable();
        pnRight = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblTenNhom = new javax.swing.JLabel();
        txtTenNhom = new javax.swing.JTextField();
        lblMoTa = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        pnLine = new javax.swing.JPanel();
        lblChonQuyen = new javax.swing.JLabel();
        cbxChucNang = new javax.swing.JComboBox<>();
        scrollChucNang = new javax.swing.JScrollPane();
        tblChucNangDaChon = new javax.swing.JTable();
        btnXoaQuyen = new javax.swing.JButton();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoaNhom = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThemQuyen = new javax.swing.JButton();

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(850, 650));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(35, 30, 48));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ VAI TRÒ VÀ NHÓM CHỨC NĂNG");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 850, 50);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 850, 50);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH VAI TRÒ");
        pnLeft.add(lblListTitle);
        lblListTitle.setBounds(15, 15, 250, 30);

        tblNhomQuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Vai trò", "Tên Vai trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhomQuyen.setRowHeight(30);
        tblNhomQuyen.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblNhomQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhomQuyenMouseClicked(evt);
            }
        });
        scrollNhomQuyen.setViewportView(tblNhomQuyen);

        pnLeft.add(scrollNhomQuyen);
        scrollNhomQuyen.setBounds(15, 60, 310, 440);

        pnMain.add(pnLeft);
        pnLeft.setBounds(490, 70, 340, 520);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("CHI TIẾT & CẤP QUYỀN VAI TRÒ");
        pnRight.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 300, 30);

        lblTenNhom.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenNhom.setForeground(new java.awt.Color(35, 30, 48));
        lblTenNhom.setText("Tên vai trò (*)");
        pnRight.add(lblTenNhom);
        lblTenNhom.setBounds(20, 60, 150, 18);

        txtTenNhom.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTenNhom.addActionListener(this::txtTenNhomActionPerformed);
        pnRight.add(txtTenNhom);
        txtTenNhom.setBounds(20, 80, 410, 30);

        lblMoTa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMoTa.setForeground(new java.awt.Color(35, 30, 48));
        lblMoTa.setText("Mô tả");
        pnRight.add(lblMoTa);
        lblMoTa.setBounds(20, 120, 150, 18);

        txtMoTa.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(txtMoTa);
        txtMoTa.setBounds(20, 140, 410, 30);

        pnLine.setBackground(new java.awt.Color(224, 224, 224));
        pnRight.add(pnLine);
        pnLine.setBounds(20, 190, 410, 1);

        lblChonQuyen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChonQuyen.setForeground(new java.awt.Color(35, 30, 48));
        lblChonQuyen.setText("Thêm nhóm chức năng vào vai trò:");
        pnRight.add(lblChonQuyen);
        lblChonQuyen.setBounds(20, 205, 250, 18);

        cbxChucNang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxChucNang.addActionListener(this::cbxChucNangActionPerformed);
        pnRight.add(cbxChucNang);
        cbxChucNang.setBounds(20, 225, 290, 30);

        tblChucNangDaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhóm chức năng", "Tên Nhóm chức năng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChucNangDaChon.setRowHeight(25);
        tblChucNangDaChon.setSelectionBackground(new java.awt.Color(235, 94, 141));
        scrollChucNang.setViewportView(tblChucNangDaChon);
        if (tblChucNangDaChon.getColumnModel().getColumnCount() > 0) {
            tblChucNangDaChon.getColumnModel().getColumn(1).setResizable(false);
        }

        pnRight.add(scrollChucNang);
        scrollChucNang.setBounds(20, 265, 410, 150);

        btnXoaQuyen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaQuyen.setForeground(new java.awt.Color(220, 53, 69));
        btnXoaQuyen.setText("Gỡ nhóm chức năng đang chọn từ bảng ^");
        btnXoaQuyen.addActionListener(this::btnXoaQuyenActionPerformed);
        pnRight.add(btnXoaQuyen);
        btnXoaQuyen.setBounds(20, 420, 280, 30);

        btnThemMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(this::btnThemMoiActionPerformed);
        pnRight.add(btnThemMoi);
        btnThemMoi.setBounds(20, 465, 100, 40);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(this::btnCapNhatActionPerformed);
        pnRight.add(btnCapNhat);
        btnCapNhat.setBounds(130, 465, 100, 40);

        btnXoaNhom.setBackground(new java.awt.Color(220, 53, 69));
        btnXoaNhom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaNhom.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaNhom.setText("Xóa Vai trò");
        btnXoaNhom.addActionListener(this::btnXoaNhomActionPerformed);
        pnRight.add(btnXoaNhom);
        btnXoaNhom.setBounds(240, 465, 190, 40);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(235, 94, 141));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);
        pnRight.add(btnLamMoi);
        btnLamMoi.setBounds(300, 420, 130, 30);

        btnThemQuyen.setBackground(new java.awt.Color(235, 94, 141));
        btnThemQuyen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThemQuyen.setForeground(new java.awt.Color(255, 255, 255));
        btnThemQuyen.setText("+ Thêm vào");
        btnThemQuyen.addActionListener(this::btnThemQuyenActionPerformed);
        pnRight.add(btnThemQuyen);
        btnThemQuyen.setBounds(320, 225, 110, 30);

        pnMain.add(pnRight);
        pnRight.setBounds(10, 70, 450, 520);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {}
    private void cbxChucNangActionPerformed(java.awt.event.ActionEvent evt) {}
    private void txtTenNhomActionPerformed(java.awt.event.ActionEvent evt) {}



    private void tblNhomQuyenMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblNhomQuyen.getSelectedRow();
        if (row < 0 || row >= danhSachVaiTro.size())
            return;
        VaiTroDTO vt = danhSachVaiTro.get(row);
        maVaiTroDangChon = vt.getMaVaiTro();
        txtTenNhom.setText(vt.getTenVaiTro());
        txtMoTa.setText(vt.getMoTa() != null ? vt.getMoTa() : "");
        loadChucNangCuaVaiTro(maVaiTroDangChon);
    }

    private void btnThemQuyenActionPerformed(java.awt.event.ActionEvent evt) {
        int idx = cbxChucNang.getSelectedIndex();
        if (idx < 0 || idx >= danhSachChucNang.size())
            return;
        ChucNangDTO cn = danhSachChucNang.get(idx);
        DefaultTableModel model = (DefaultTableModel) tblChucNangDaChon.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if (cn.getMaChucNang().equals(model.getValueAt(i, 0))) {
                JOptionPane.showMessageDialog(this, "Chức năng này đã có trong danh sách!");
                return;
            }
        }
        model.addRow(new Object[] { cn.getMaChucNang(), cn.getTenChucNang() });
    }

    private void btnXoaQuyenActionPerformed(java.awt.event.ActionEvent evt) {
        int row = tblChucNangDaChon.getSelectedRow();
        if (row >= 0) {
            ((DefaultTableModel) tblChucNangDaChon.getModel()).removeRow(row);
        }
    }

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {
        String ten = txtTenNhom.getText().trim();
        if (ten.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhóm!");
            return;
        }
        VaiTroDTO vt = new VaiTroDTO();
        vt.setTenVaiTro(ten);
        vt.setMoTa(txtMoTa.getText().trim());
        try {
            if (controller.themVaiTro(vt, layDanhSachMaCNTuBang())) {
                JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
                lamMoiPanel();
                loadDanhSachVaiTro();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        if (maVaiTroDangChon == null)
            return;
        String ten = txtTenNhom.getText().trim();
        if (ten.isEmpty())
            return;
        VaiTroDTO vt = new VaiTroDTO();
        vt.setMaVaiTro(maVaiTroDangChon);
        vt.setTenVaiTro(ten);
        vt.setMoTa(txtMoTa.getText().trim());
        try {
            if (controller.capNhatVaiTro(vt, layDanhSachMaCNTuBang())) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                loadDanhSachVaiTro();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnXoaNhomActionPerformed(java.awt.event.ActionEvent evt) {
        if (maVaiTroDangChon == null)
            return;
        int confirm = JOptionPane.showConfirmDialog(this, "Xóa nhóm quyền này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (controller.xoaVaiTro(maVaiTroDangChon)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                lamMoiPanel();
                loadDanhSachVaiTro();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại! (Có thể đang gán cho nhân viên)", "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnThemQuyen;
    private javax.swing.JButton btnXoaNhom;
    private javax.swing.JButton btnXoaQuyen;
    private javax.swing.JComboBox<String> cbxChucNang;
    private javax.swing.JLabel lblChonQuyen;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblTenNhom;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLine;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JScrollPane scrollChucNang;
    private javax.swing.JScrollPane scrollNhomQuyen;
    private javax.swing.JTable tblChucNangDaChon;
    private javax.swing.JTable tblNhomQuyen;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtTenNhom;
    // End of variables declaration//GEN-END:variables
}
