PROMPT === Kiem tra HOADON trung MaPhien ===

SELECT MaPhien, COUNT(*) AS SoHoaDon
FROM HOADON
WHERE MaPhien IS NOT NULL
GROUP BY MaPhien
HAVING COUNT(*) > 1;

DECLARE
    v_Count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_Count
    FROM USER_TABLES
    WHERE TABLE_NAME = 'WMS_HOADON_DUP_REPORT';

    IF v_Count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE WMS_HOADON_DUP_REPORT (
                Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                ThoiGianGhiNhan TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                MaPhien VARCHAR2(50),
                MaHoaDon VARCHAR2(50),
                TrangThaiThanhToan VARCHAR2(50),
                DaTraTruoc NUMBER(18, 2),
                NgayLapHoaDon TIMESTAMP,
                LyDo VARCHAR2(500),
                CONSTRAINT PK_WMS_HOADON_DUP_REPORT PRIMARY KEY (Id)
            )';
    END IF;
END;
/

INSERT INTO WMS_HOADON_DUP_REPORT (
    MaPhien,
    MaHoaDon,
    TrangThaiThanhToan,
    DaTraTruoc,
    NgayLapHoaDon,
    LyDo
)
SELECT h.MaPhien,
       h.MaHoaDon,
       h.TrangThaiThanhToan,
       NVL(h.DaTraTruoc, 0),
       h.NgayLapHoaDon,
       'CAN_XU_LY_THU_CONG: phien co nhieu hoa don da thanh toan thanh cong'
FROM HOADON h
JOIN (
    SELECT MaPhien
    FROM HOADON
    WHERE MaPhien IS NOT NULL
    GROUP BY MaPhien
    HAVING SUM(CASE WHEN TrangThaiThanhToan = 'Đã thanh toán thành công' THEN 1 ELSE 0 END) > 1
) dup ON dup.MaPhien = h.MaPhien;

INSERT INTO WMS_HOADON_DUP_REPORT (
    MaPhien,
    MaHoaDon,
    TrangThaiThanhToan,
    DaTraTruoc,
    NgayLapHoaDon,
    LyDo
)
SELECT MaPhien,
       MaHoaDon,
       TrangThaiThanhToan,
       NVL(DaTraTruoc, 0),
       NgayLapHoaDon,
       'AUTO_CLEANUP_DELETE_DUPLICATE: giu hoa don uu tien theo trang thai va moi nhat'
FROM (
    SELECT h.*,
           COUNT(*) OVER (PARTITION BY MaPhien) AS SoHoaDon,
           SUM(CASE WHEN TrangThaiThanhToan = 'Đã thanh toán thành công' THEN 1 ELSE 0 END)
               OVER (PARTITION BY MaPhien) AS SoHoaDonDaThanhToan,
           ROW_NUMBER() OVER (
               PARTITION BY MaPhien
               ORDER BY
                   CASE
                       WHEN TrangThaiThanhToan = 'Đã thanh toán thành công' THEN 1
                       WHEN TrangThaiThanhToan = 'Đã trả trước' OR NVL(DaTraTruoc, 0) > 0 THEN 2
                       ELSE 3
                   END,
                   NgayLapHoaDon DESC NULLS LAST,
                   MaHoaDon DESC
           ) AS rn
    FROM HOADON h
    WHERE MaPhien IS NOT NULL
)
WHERE SoHoaDon > 1
  AND SoHoaDonDaThanhToan <= 1
  AND rn > 1;

DELETE FROM HOADON
WHERE MaHoaDon IN (
    SELECT MaHoaDon
    FROM (
        SELECT h.MaHoaDon,
               COUNT(*) OVER (PARTITION BY MaPhien) AS SoHoaDon,
               SUM(CASE WHEN TrangThaiThanhToan = 'Đã thanh toán thành công' THEN 1 ELSE 0 END)
                   OVER (PARTITION BY MaPhien) AS SoHoaDonDaThanhToan,
               ROW_NUMBER() OVER (
                   PARTITION BY MaPhien
                   ORDER BY
                       CASE
                           WHEN TrangThaiThanhToan = 'Đã thanh toán thành công' THEN 1
                           WHEN TrangThaiThanhToan = 'Đã trả trước' OR NVL(DaTraTruoc, 0) > 0 THEN 2
                           ELSE 3
                       END,
                       NgayLapHoaDon DESC NULLS LAST,
                       MaHoaDon DESC
               ) AS rn
        FROM HOADON h
        WHERE MaPhien IS NOT NULL
    )
    WHERE SoHoaDon > 1
      AND SoHoaDonDaThanhToan <= 1
      AND rn > 1
);

COMMIT;

DECLARE
    v_UnsafeCount NUMBER;
    v_ConstraintCount NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_UnsafeCount
    FROM (
        SELECT MaPhien
        FROM HOADON
        WHERE MaPhien IS NOT NULL
        GROUP BY MaPhien
        HAVING COUNT(*) > 1
    );

    IF v_UnsafeCount > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20991,
            'Con HOADON trung MaPhien can xu ly thu cong. Xem bang WMS_HOADON_DUP_REPORT.'
        );
    END IF;

    SELECT COUNT(*)
    INTO v_ConstraintCount
    FROM USER_CONSTRAINTS
    WHERE CONSTRAINT_NAME = 'UQ_HOADON_MAPHIEN';

    IF v_ConstraintCount = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD CONSTRAINT UQ_HOADON_MAPHIEN UNIQUE (MaPhien)';
    END IF;
END;
/

PROMPT === Kiem tra lai HOADON trung MaPhien sau cleanup ===

SELECT MaPhien, COUNT(*) AS SoHoaDon
FROM HOADON
WHERE MaPhien IS NOT NULL
GROUP BY MaPhien
HAVING COUNT(*) > 1;
