CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Bookings
BEFORE UPDATE ON Bookings
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Sessions
BEFORE UPDATE ON Sessions
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_SOrders
BEFORE UPDATE ON SessionOrders
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;

CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_SExtensions
BEFORE UPDATE ON SessionExtensions
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Spaces
BEFORE UPDATE ON Spaces
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Users
BEFORE UPDATE ON Users
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Customers
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Invoices
BEFORE UPDATE ON Invoices
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Branches
BEFORE UPDATE ON Branches
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Vouchers
BEFORE UPDATE ON Vouchers
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Products
BEFORE UPDATE ON Products
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Categories
BEFORE UPDATE ON Categories
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_MemberTiers
BEFORE UPDATE ON MembershipTiers
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;

CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_SpaceTypes
BEFORE UPDATE ON SpaceTypes
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Employees
BEFORE UPDATE ON Employees
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Roles
BEFORE UPDATE ON Roles
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;


CREATE OR REPLACE TRIGGER trg_Update_UpdatedAt_Permissions
BEFORE UPDATE ON Permissions
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/