package com.wms.view.TrangChuHoiVien.TrangChu;

import com.wms.controller.TrangChuController;

public class TrangChuForm extends javax.swing.JPanel {

    private com.wms.controller.TrangChuController controller;

    public TrangChuForm() {
        initComponents();
        controller = new com.wms.controller.TrangChuController();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnCard1 = new javax.swing.JPanel();
        lblCard1Title = new javax.swing.JLabel();
        lblCard1Value = new javax.swing.JLabel();
        lblCard1Sub = new javax.swing.JLabel();
        pnCard2 = new javax.swing.JPanel();
        lblCard2Title = new javax.swing.JLabel();
        lblCard2Value = new javax.swing.JLabel();
        lblCard2Sub = new javax.swing.JLabel();
        pnCard3 = new javax.swing.JPanel();
        lblCard3Title = new javax.swing.JLabel();
        lblCard3Value = new javax.swing.JLabel();
        lblCard3Sub = new javax.swing.JLabel();
        lblTableTitle = new javax.swing.JLabel();
        scrollTable = new javax.swing.JScrollPane();
        tblLichSu = new javax.swing.JTable();
        lblPromoTitle = new javax.swing.JLabel();
        pnPromo = new javax.swing.JPanel();
        lblPromoBanner = new javax.swing.JLabel();
        btnDatNgay = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblTitle.setText("Tổng quan hoạt động");
        pnMain.add(lblTitle);
        lblTitle.setBounds(30, 20, 400, 32);

        pnCard1.setBackground(new java.awt.Color(255, 255, 255));
        pnCard1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(235, 94, 141)));
        pnCard1.setLayout(null);

        lblCard1Title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCard1Title.setForeground(new java.awt.Color(136, 136, 136));
        lblCard1Title.setText("ĐIỂM TÍCH LŨY");
        pnCard1.add(lblCard1Title);
        lblCard1Title.setBounds(20, 20, 200, 20);

        lblCard1Value.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCard1Value.setForeground(new java.awt.Color(235, 94, 141));
        lblCard1Value.setText("1,250");
        pnCard1.add(lblCard1Value);
        lblCard1Value.setBounds(20, 45, 200, 48);

        lblCard1Sub.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        lblCard1Sub.setForeground(new java.awt.Color(170, 170, 170));
        lblCard1Sub.setText("Hạng hiện tại: VIP Kim Cương");
        pnCard1.add(lblCard1Sub);
        lblCard1Sub.setBounds(20, 95, 250, 18);

        pnMain.add(pnCard1);
        pnCard1.setBounds(30, 70, 310, 130);

        pnCard2.setBackground(new java.awt.Color(255, 255, 255));
        pnCard2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(94, 141, 235)));
        pnCard2.setLayout(null);

        lblCard2Title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCard2Title.setForeground(new java.awt.Color(136, 136, 136));
        lblCard2Title.setText("TỔNG GIỜ SỬ DỤNG");
        pnCard2.add(lblCard2Title);
        lblCard2Title.setBounds(20, 20, 200, 20);

        lblCard2Value.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCard2Value.setForeground(new java.awt.Color(94, 141, 235));
        lblCard2Value.setText("128");
        pnCard2.add(lblCard2Value);
        lblCard2Value.setBounds(20, 45, 200, 48);

        lblCard2Sub.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        lblCard2Sub.setForeground(new java.awt.Color(170, 170, 170));
        lblCard2Sub.setText("Thống kê trong tháng này");
        pnCard2.add(lblCard2Sub);
        lblCard2Sub.setBounds(20, 95, 250, 18);

        pnMain.add(pnCard2);
        pnCard2.setBounds(370, 70, 310, 130);

        pnCard3.setBackground(new java.awt.Color(255, 255, 255));
        pnCard3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(235, 184, 94)));
        pnCard3.setLayout(null);

        lblCard3Title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCard3Title.setForeground(new java.awt.Color(136, 136, 136));
        lblCard3Title.setText("ƯU ĐÃI CỦA TÔI");
        pnCard3.add(lblCard3Title);
        lblCard3Title.setBounds(20, 20, 200, 20);

        lblCard3Value.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCard3Value.setForeground(new java.awt.Color(235, 184, 94));
        lblCard3Value.setText("3");
        pnCard3.add(lblCard3Value);
        lblCard3Value.setBounds(20, 45, 200, 48);

        lblCard3Sub.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        lblCard3Sub.setForeground(new java.awt.Color(170, 170, 170));
        lblCard3Sub.setText("Phiếu giảm giá đang có hiệu lực");
        pnCard3.add(lblCard3Sub);
        lblCard3Sub.setBounds(20, 95, 250, 18);

        pnMain.add(pnCard3);
        pnCard3.setBounds(710, 70, 310, 130);

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTableTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblTableTitle.setText("Lịch sử đặt chỗ gần đây");
        pnMain.add(lblTableTitle);
        lblTableTitle.setBounds(30, 230, 300, 25);

        tblLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phiếu", "Không gian", "Thời gian", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLichSu.setRowHeight(30);
        tblLichSu.setSelectionBackground(new java.awt.Color(235, 94, 141));
        scrollTable.setViewportView(tblLichSu);

        pnMain.add(scrollTable);
        scrollTable.setBounds(30, 270, 650, 340);

        lblPromoTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPromoTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblPromoTitle.setText("Không gian nổi bật");
        pnMain.add(lblPromoTitle);
        lblPromoTitle.setBounds(710, 230, 300, 25);

        pnPromo.setBackground(new java.awt.Color(255, 255, 255));
        pnPromo.setLayout(null);

        lblPromoBanner.setText("<html><div style='padding:15px; text-align:center;'><h2 style='color:#EB5E8D; margin-bottom:5px;'>Phòng họp SPRING 01</h2><h4 style='color:#888; margin-top:0;'>Sức chứa: 10 Người</h4><p style='font-size:13px; color:#444; line-height:1.5;'>Không gian riêng tư, yên tĩnh. Trang bị đầy đủ máy chiếu, bảng trắng, âm thanh hiện đại.<br><br><b>Giảm 10%</b> cho Hội viên VIP.</p></div></html>");
        lblPromoBanner.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblPromoBanner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnPromo.add(lblPromoBanner);
        lblPromoBanner.setBounds(0, 0, 310, 260);

        btnDatNgay.setBackground(new java.awt.Color(235, 94, 141));
        btnDatNgay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDatNgay.setForeground(new java.awt.Color(255, 255, 255));
        btnDatNgay.setText("Đặt ngay bây giờ");
        btnDatNgay.addActionListener(this::btnDatNgayActionPerformed);
        pnPromo.add(btnDatNgay);
        btnDatNgay.setBounds(0, 290, 310, 50);

        pnMain.add(pnPromo);
        pnPromo.setBounds(710, 270, 310, 340);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void loadData() {
        lblCard1Value.setText(String.format("%,d", controller.layDiemTichLuy()));
        lblCard1Sub.setText("Hạng hiện tại: " + controller.layHangHienTai());
        lblCard2Value.setText(String.valueOf(controller.layTongGioSuDung()));
        lblCard3Value.setText(String.valueOf(controller.laySoUuDai()));

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblLichSu.getModel();
        model.setRowCount(0);
        for (Object[] row : controller.layLichSuDatCho()) {
            model.addRow(row);
        }
        
        loadKhongGianNoiBat();
    }

    private void loadKhongGianNoiBat() {
    }

    private void btnDatNgayActionPerformed(java.awt.event.ActionEvent evt) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatNgay;
    private javax.swing.JLabel lblCard1Sub;
    private javax.swing.JLabel lblCard1Title;
    private javax.swing.JLabel lblCard1Value;
    private javax.swing.JLabel lblCard2Sub;
    private javax.swing.JLabel lblCard2Title;
    private javax.swing.JLabel lblCard2Value;
    private javax.swing.JLabel lblCard3Sub;
    private javax.swing.JLabel lblCard3Title;
    private javax.swing.JLabel lblCard3Value;
    private javax.swing.JLabel lblPromoBanner;
    private javax.swing.JLabel lblPromoTitle;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnCard1;
    private javax.swing.JPanel pnCard2;
    private javax.swing.JPanel pnCard3;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnPromo;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblLichSu;
    // End of variables declaration//GEN-END:variables
}


