CREATE TABLE CHINHANH (
    MaCN VARCHAR2(50),
    TenCN VARCHAR2(100),
    ThoiGianMoCua VARCHAR2(8),
    ThoiGianDongCua VARCHAR2(8),
    DuongDayNong VARCHAR2(20),
    TrangThai VARCHAR2(50),
    DiaChi VARCHAR2(255),
    CONSTRAINT PK_CHINHANH PRIMARY KEY (MaCN)
);

CREATE TABLE LOAIKHONGGIAN (
    MaLoaiKG VARCHAR2(50),
    TenLoaiKG VARCHAR2(100),
    SucChua NUMBER,
    DonGiaTheoGio NUMBER(18, 2),
    TrangThai VARCHAR2(100),
    CONSTRAINT PK_LOAIKHONGGIAN PRIMARY KEY (MaLoaiKG)
);

CREATE TABLE KHONGGIAN (
    MaKG VARCHAR2(50),
    TenKG VARCHAR2(100),
    TrangThaiKG VARCHAR2(50),
    ViTri VARCHAR2(100),
    MaLoaiKG VARCHAR2(50),
    MaCN VARCHAR2(50),
    ToaDoX NUMBER DEFAULT 0,
    ToaDoY NUMBER DEFAULT 0,
    ChieuDai NUMBER DEFAULT 0,
    ChieuRong NUMBER DEFAULT 0,
    CONSTRAINT PK_KHONGGIAN PRIMARY KEY (MaKG)
);

CREATE TABLE HANGTHANHVIEN (
    MaHangThanhVien VARCHAR2(50),
    TenHangThanhVien VARCHAR2(50),
    PhanTramTienGiam NUMBER(5, 2),
    TongChiTieuToiThieu NUMBER(18, 2),
    CONSTRAINT PK_HANGTHANHVIEN PRIMARY KEY (MaHangThanhVien)
);

CREATE TABLE NGUOIDUNG (
    MaND VARCHAR2(50),
    HoTen VARCHAR2(100) NOT NULL,
    TenTaiKhoan VARCHAR2(50),
    MatKhauMaHoa VARCHAR2(255),
    AnhDaiDien BLOB,
    GioiTinh VARCHAR2(10),
    Email VARCHAR2(100),
    SDT VARCHAR2(20),
    NgaySinh DATE,
    ThoiGianTao TIMESTAMP,
    CapNhatLanCuoi TIMESTAMP,
    LanCuoiDangNhap TIMESTAMP,
    TrangThaiND VARCHAR2(50),
    CONSTRAINT PK_NGUOIDUNG PRIMARY KEY (MaND),
    CONSTRAINT UNIQUE_ND_SDT UNIQUE (SDT),
    CONSTRAINT UNIQUE_ND_Email UNIQUE (Email),
    CONSTRAINT UNIQUE_ND_TenTaiKhoan UNIQUE (TenTaiKhoan)
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR2(50),
    LoaiKH VARCHAR2(50),
    TongChiTieu NUMBER(18, 2),
    CapNhatLanCuoi TIMESTAMP,
    MaHangThanhVien VARCHAR2(50),
    MaND VARCHAR2(50),
    CONSTRAINT PK_KHACHHANG PRIMARY KEY (MaKH),
    CONSTRAINT UK_KHACHHANG_MaND UNIQUE (MaND)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR2(50),
    LoaiNV VARCHAR2(50),
    NgayVaoLam DATE,
    TrangThaiLamViec VARCHAR2(50),
    PhuCap NUMBER(18, 2),
    TienThuong NUMBER(18, 2),
    CaLamViec VARCHAR2(50),
    LuongCoBan NUMBER(18, 2),
    MaNQL VARCHAR2(50),
    MaCN VARCHAR2(50),
    MaND VARCHAR2(50),
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MaNV),
    CONSTRAINT UK_NHANVIEN_MaND UNIQUE (MaND)
);

CREATE TABLE VAITRO (
    MaVaiTro VARCHAR2(50),
    TenVaiTro VARCHAR2(100),
    MoTa VARCHAR2(255),
    CONSTRAINT PK_VAITRO PRIMARY KEY (MaVaiTro)
);

CREATE TABLE CHUCNANG (
    MaChucNang VARCHAR2(50),
    TenChucNang VARCHAR2(100),
    MoTa VARCHAR2(255),
    CONSTRAINT PK_CHUCNANG PRIMARY KEY (MaChucNang)
);

CREATE TABLE NHOMCHUCNANG (
    MaNhomChucNang VARCHAR2(50),
    TenNhomChucNang VARCHAR2(100),
    MoTa VARCHAR2(255),
    CONSTRAINT PK_NHOMCHUCNANG PRIMARY KEY (MaNhomChucNang)
);

CREATE TABLE CHITIETVAITRO (
    MaND VARCHAR2(50),
    MaVaiTro VARCHAR2(50),
    MoTa VARCHAR2(255),
    CONSTRAINT PK_CHITIETVAITRO PRIMARY KEY (MaND, MaVaiTro)
);

CREATE TABLE CHITIETCHUCNANG (
    MaNhomChucNang VARCHAR2(50),
    MaChucNang VARCHAR2(50),
    MoTa VARCHAR2(255),
    CONSTRAINT PK_CHITIETCHUCNANG PRIMARY KEY (MaNhomChucNang, MaChucNang)
);

CREATE TABLE CHITIETNHOMCHUCNANG (
    MaVaiTro VARCHAR2(50),
    MaNhomChucNang VARCHAR2(50),
    MoTa VARCHAR2(255),
    CONSTRAINT PK_CHITIETNHOMCHUCNANG PRIMARY KEY (MaVaiTro, MaNhomChucNang)
);

CREATE TABLE PHIEUGIAMGIA (
    MaPGG VARCHAR2(50),
    MaChuSoPGG VARCHAR2(100),
    GiaTriGiamGia NUMBER(18, 2),
    GiaTriApDungToiThieu NUMBER(18, 2),
    NgayBatDauApDung TIMESTAMP,
    NgayKetThucApDung TIMESTAMP,
    SLDaDung NUMBER,
    SLToiDa NUMBER,
    NgayTaoPGG TIMESTAMP,
    MaNV VARCHAR2(50),
    TrangThai VARCHAR2(100),
    CONSTRAINT PK_PHIEUGIAMGIA PRIMARY KEY (MaPGG)
);

CREATE TABLE DATCHO (
    MaDatCho VARCHAR2(50),
    ThoiGianDat TIMESTAMP,
    ThoiGianDuKienToi TIMESTAMP,
    KhoangThoiGianSuDung NUMBER,
    TrangThaiDatTruoc VARCHAR2(50),
    ThanhTien NUMBER(18, 2),
    TongTienGoc NUMBER(18, 2) DEFAULT 0 NOT NULL,
    MaPGG VARCHAR2(50),
    MaChuSoPGG VARCHAR2(100),
    TienGiamVoucher NUMBER(18, 2) DEFAULT 0 NOT NULL,
    PhanTramGiamHangTV NUMBER(5, 2) DEFAULT 0 NOT NULL,
    TienGiamHangTV NUMBER(18, 2) DEFAULT 0 NOT NULL,
    ThanhTienSauGiam NUMBER(18, 2) DEFAULT 0 NOT NULL,
    GhiChu VARCHAR2(255),
    MaQR VARCHAR2(255),
    CapNhatLanCuoi TIMESTAMP,
    MaKH VARCHAR2(50),
    MaKG VARCHAR2(50),
    CONSTRAINT PK_DATCHO PRIMARY KEY (MaDatCho)
);

CREATE TABLE PHIENLAMVIEC (
    MaPhien VARCHAR2(50),
    ThoiGianBatDau TIMESTAMP,
    ThoiGianDuKienKetThuc TIMESTAMP,
    TrangThaiPhien VARCHAR2(50),
    ThoiGianKetThuc TIMESTAMP,
    CapNhatLanCuoi TIMESTAMP,
    MaKG VARCHAR2(50),
    MaKH VARCHAR2(50),
    MaDatCho VARCHAR2(50),
    CONSTRAINT PK_PHIENLAMVIEC PRIMARY KEY (MaPhien)
);

CREATE TABLE HOADON (
    MaHoaDon VARCHAR2(50),
    SoHD VARCHAR2(50),
    TongTien NUMBER(18, 2),
    ThanhTien NUMBER(18, 2),
    TongTienGoc NUMBER(18, 2) DEFAULT 0 NOT NULL,
    TienGocDatTruoc NUMBER(18, 2) DEFAULT 0 NOT NULL,
    TienGocPhatSinh NUMBER(18, 2) DEFAULT 0 NOT NULL,
    MaPGGDatTruoc VARCHAR2(50),
    MaPGGTaiQuay VARCHAR2(50),
    TienGiamVoucherDatTruoc NUMBER(18, 2) DEFAULT 0 NOT NULL,
    TienGiamHangTVDatTruoc NUMBER(18, 2) DEFAULT 0 NOT NULL,
    PhanTramGiamHangTVDatTruoc NUMBER(5, 2) DEFAULT 0 NOT NULL,
    TienGiamVoucherTaiQuay NUMBER(18, 2) DEFAULT 0 NOT NULL,
    TienGiamHangTVTaiQuay NUMBER(18, 2) DEFAULT 0 NOT NULL,
    PhanTramGiamHangTVTaiQuay NUMBER(5, 2) DEFAULT 0 NOT NULL,
    TongTienGiam NUMBER(18, 2) DEFAULT 0 NOT NULL,
    SoTienThanhToanTaiQuay NUMBER(18, 2) DEFAULT 0 NOT NULL,
    NgayLapHoaDon TIMESTAMP,
    PhuongThucThanhToan VARCHAR2(50),
    TrangThaiThanhToan VARCHAR2(50),
    DaTraTruoc NUMBER(18, 2) DEFAULT 0 NOT NULL,
    MaPhien VARCHAR2(50),
    MaPGG VARCHAR2(50),
    MaNV VARCHAR2(50),
    CONSTRAINT PK_HOADON PRIMARY KEY (MaHoaDon)
);

CREATE TABLE LOAIDICHVU (
    MaLoaiDV VARCHAR2(50),
    TenLoaiDV VARCHAR2(100),
    TrangThaiLDV VARCHAR2(50),
    CONSTRAINT PK_LOAIDICHVU PRIMARY KEY (MaLoaiDV)
);

CREATE TABLE DICHVU (
    MaDV VARCHAR2(50),
    TenDV VARCHAR2(100),
    HinhAnh BLOB,
    TrangThaiDV VARCHAR2(50),
    DonGia NUMBER(18, 2),
    MaLoaiDV VARCHAR2(50),
    SoLuong NUMBER,
    GiaNhap NUMBER,
    CONSTRAINT PK_DICHVU PRIMARY KEY (MaDV)
);

CREATE TABLE CHITIETDICHVU (
    MaDV VARCHAR2(50),
    MaPhien VARCHAR2(50),
    SoLuong NUMBER,
    GhiChu VARCHAR2(255),
    CONSTRAINT PK_CHITIETDICHVU PRIMARY KEY (MaDV, MaPhien)
);

CREATE TABLE CHUNGTUNHAPKHO (
    MaChungTu VARCHAR2(50),
    MaDV VARCHAR2(50) NOT NULL,
    MaNV VARCHAR2(50),
    MaCN VARCHAR2(50),
    TenFile VARCHAR2(255),
    NoiDungFile BLOB,
    NgayNhap DATE DEFAULT SYSDATE,
    SoLuongNhap NUMBER,
    CONSTRAINT PK_CHUNGTUNHAPKHO PRIMARY KEY (MaChungTu)
);