DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaND, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM NGUOIDUNG
    WHERE REGEXP_LIKE(MaND, '^ND[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NGUOIDUNG';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_NGUOIDUNG START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_NGUOIDUNG
BEFORE INSERT ON NGUOIDUNG
FOR EACH ROW
BEGIN
    IF :NEW.MaND IS NULL THEN
        :NEW.MaND := 'ND' || LPAD(SEQ_NGUOIDUNG.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaKH, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM KHACHHANG
    WHERE REGEXP_LIKE(MaKH, '^HV[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_KHACHHANG';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_KHACHHANG START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_KHACHHANG
BEFORE INSERT ON KHACHHANG
FOR EACH ROW
BEGIN
    IF :NEW.MaKH IS NULL THEN
        :NEW.MaKH := 'HV' || LPAD(SEQ_KHACHHANG.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaNV, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM NHANVIEN
    WHERE REGEXP_LIKE(MaNV, '^NV[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NHANVIEN';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_NHANVIEN START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_NHANVIEN
BEFORE INSERT ON NHANVIEN
FOR EACH ROW
BEGIN
    IF :NEW.MaNV IS NULL THEN
        :NEW.MaNV := 'NV' || LPAD(SEQ_NHANVIEN.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaCN, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM CHINHANH
    WHERE REGEXP_LIKE(MaCN, '^CN[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHINHANH';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CHINHANH START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_CHINHANH
BEFORE INSERT ON CHINHANH
FOR EACH ROW
BEGIN
    IF :NEW.MaCN IS NULL THEN
        :NEW.MaCN := 'CN' || LPAD(SEQ_CHINHANH.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaKG, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM KHONGGIAN
    WHERE REGEXP_LIKE(MaKG, '^KG[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_KHONGGIAN';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_KHONGGIAN START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_KHONGGIAN
BEFORE INSERT ON KHONGGIAN
FOR EACH ROW
BEGIN
    IF :NEW.MaKG IS NULL THEN
        :NEW.MaKG := 'KG' || LPAD(SEQ_KHONGGIAN.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaLoaiKG, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM LOAIKHONGGIAN
    WHERE REGEXP_LIKE(MaLoaiKG, '^LKG[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOAIKHONGGIAN';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_LOAIKHONGGIAN START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_LOAIKHONGGIAN
BEFORE INSERT ON LOAIKHONGGIAN
FOR EACH ROW
BEGIN
    IF :NEW.MaLoaiKG IS NULL THEN
        :NEW.MaLoaiKG := 'LKG' || LPAD(SEQ_LOAIKHONGGIAN.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaLoaiDV, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM LOAIDICHVU
    WHERE REGEXP_LIKE(MaLoaiDV, '^LDV[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LOAIDICHVU';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_LOAIDICHVU START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_LOAIDICHVU
BEFORE INSERT ON LOAIDICHVU
FOR EACH ROW
BEGIN
    IF :NEW.MaLoaiDV IS NULL THEN
        :NEW.MaLoaiDV := 'LDV' || LPAD(SEQ_LOAIDICHVU.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaDV, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM DICHVU
    WHERE REGEXP_LIKE(MaDV, '^DV[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DICHVU';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_DICHVU START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_DICHVU
BEFORE INSERT ON DICHVU
FOR EACH ROW
BEGIN
    IF :NEW.MaDV IS NULL THEN
        :NEW.MaDV := 'DV' || LPAD(SEQ_DICHVU.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaDatCho, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM DATCHO
    WHERE REGEXP_LIKE(MaDatCho, '^DC[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DATCHO';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_DATCHO START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_DATCHO
BEFORE INSERT ON DATCHO
FOR EACH ROW
BEGIN
    IF :NEW.MaDatCho IS NULL THEN
        :NEW.MaDatCho := 'DC' || LPAD(SEQ_DATCHO.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaPhien, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM PHIENLAMVIEC
    WHERE REGEXP_LIKE(MaPhien, '^PLV[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PHIENLAMVIEC';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PHIENLAMVIEC START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_PHIENLAMVIEC
BEFORE INSERT ON PHIENLAMVIEC
FOR EACH ROW
BEGIN
    IF :NEW.MaPhien IS NULL THEN
        :NEW.MaPhien := 'PLV' || LPAD(SEQ_PHIENLAMVIEC.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaHoaDon, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM HOADON
    WHERE REGEXP_LIKE(MaHoaDon, '^HD[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HOADON';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_HOADON START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_HOADON
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    IF :NEW.MaHoaDon IS NULL THEN
        :NEW.MaHoaDon := 'HD' || LPAD(SEQ_HOADON.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaPGG, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM PHIEUGIAMGIA
    WHERE REGEXP_LIKE(MaPGG, '^PGG[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PHIEUGIAMGIA';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PHIEUGIAMGIA START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_PHIEUGIAMGIA
BEFORE INSERT ON PHIEUGIAMGIA
FOR EACH ROW
BEGIN
    IF :NEW.MaPGG IS NULL THEN
        :NEW.MaPGG := 'PGG' || LPAD(SEQ_PHIEUGIAMGIA.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaChungTu, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM CHUNGTUNHAPKHO
    WHERE REGEXP_LIKE(MaChungTu, '^CT[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHUNGTUNHAPKHO';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CHUNGTUNHAPKHO START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_CHUNGTUNHAPKHO
BEFORE INSERT ON CHUNGTUNHAPKHO
FOR EACH ROW
BEGIN
    IF :NEW.MaChungTu IS NULL THEN
        :NEW.MaChungTu := 'CT' || LPAD(SEQ_CHUNGTUNHAPKHO.NEXTVAL, 4, '0');
    END IF;
END;
/

DECLARE
    v_start NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(MaVaiTro, '[0-9]+$'))), 0) + 1
    INTO v_start
    FROM VAITRO
    WHERE REGEXP_LIKE(MaVaiTro, '^VT[0-9]+$');

    BEGIN
        EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VAITRO';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -2289 THEN RAISE; END IF;
    END;

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_VAITRO START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/

CREATE OR REPLACE TRIGGER TRG_TAO_MA_VAITRO
BEFORE INSERT ON VAITRO
FOR EACH ROW
BEGIN
    IF :NEW.MaVaiTro IS NULL THEN
        :NEW.MaVaiTro := 'VT' || LPAD(SEQ_VAITRO.NEXTVAL, 2, '0');
    END IF;
END;
/
