/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyHoiVien.QuanLyHangThanhVien;

import com.wms.controller.QuanLyHangTVController;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyHangTVForm extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuanLyHangTVForm.class.getName());

    /**
     * Creates new form QuanLyHangTVForm
     */
    private com.wms.controller.QuanLyHangTVController controller = new com.wms.controller.QuanLyHangTVController();
    private java.util.List<com.wms.model.HangThanhVienDTO> hangList;
    private com.wms.model.HangThanhVienDTO selectedHang;

    public QuanLyHangTVForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadDataToTable();
    }

    private void loadDataToTable() {
        hangList = controller.layDanhSachHang();
        fillTable();
    }

    private void fillTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblHangTV.getModel();
        model.setRowCount(0);
        if (hangList != null) {
            for (com.wms.model.HangThanhVienDTO dto : hangList) {
                model.addRow(new Object[]{
                    dto.getMaHangThanhVien(), dto.getTenHangThanhVien(), dto.getPhanTramTienGiam(), dto.getTongChiTieuToiThieu()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaHang = new javax.swing.JLabel();
        txtMaHang = new javax.swing.JTextField();
        lblTenHang = new javax.swing.JLabel();
        cbxTenHang = new javax.swing.JComboBox<>();
        lblPhanTram = new javax.swing.JLabel();
        spnPhanTram = new javax.swing.JSpinner();
        lblChiTieu = new javax.swing.JLabel();
        txtChiTieu = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHangTV = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý Hạng Thành Viên");
        setModal(true);
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(850, 550));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ HẠNG THÀNH VIÊN");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 850, 50);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 850, 50);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("THÔNG TIN HẠNG");
        pnLeft.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 260, 30);

        lblMaHang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaHang.setForeground(new java.awt.Color(35, 30, 48));
        lblMaHang.setText("Mã Hạng (*)");
        pnLeft.add(lblMaHang);
        lblMaHang.setBounds(20, 60, 260, 20);

        txtMaHang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtMaHang);
        txtMaHang.setBounds(20, 80, 260, 35);

        lblTenHang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenHang.setForeground(new java.awt.Color(35, 30, 48));
        lblTenHang.setText("Tên Hạng (*)");
        pnLeft.add(lblTenHang);
        lblTenHang.setBounds(20, 130, 260, 20);

        cbxTenHang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxTenHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng mới", "Thành viên Bạc", "Thành viên Vàng", "VIP Kim Cương" }));
        pnLeft.add(cbxTenHang);
        cbxTenHang.setBounds(20, 150, 260, 35);

        lblPhanTram.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPhanTram.setForeground(new java.awt.Color(35, 30, 48));
        lblPhanTram.setText("% Giảm Giá (0 - 100)");
        pnLeft.add(lblPhanTram);
        lblPhanTram.setBounds(20, 200, 260, 20);

        spnPhanTram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnPhanTram.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.5d));
        pnLeft.add(spnPhanTram);
        spnPhanTram.setBounds(20, 220, 260, 35);

        lblChiTieu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChiTieu.setForeground(new java.awt.Color(35, 30, 48));
        lblChiTieu.setText("Chi Tiêu Tối Thiểu (VNĐ)");
        pnLeft.add(lblChiTieu);
        lblChiTieu.setBounds(20, 270, 260, 20);

        txtChiTieu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtChiTieu);
        txtChiTieu.setBounds(20, 290, 260, 35);

        btnThem.setBackground(new java.awt.Color(235, 94, 141));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm Mới");
        btnThem.addActionListener(this::btnThemActionPerformed);
        pnLeft.add(btnThem);
        btnThem.setBounds(20, 340, 125, 35);

        btnSua.setBackground(new java.awt.Color(235, 94, 141));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Cập Nhật");
        btnSua.addActionListener(this::btnSuaActionPerformed);
        pnLeft.add(btnSua);
        btnSua.setBounds(155, 340, 125, 35);

        btnXoa.setBackground(new java.awt.Color(220, 53, 69));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);
        pnLeft.add(btnXoa);
        btnXoa.setBounds(20, 390, 125, 35);

        btnLamMoi.setBackground(new java.awt.Color(235, 94, 141));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);
        pnLeft.add(btnLamMoi);
        btnLamMoi.setBounds(155, 390, 125, 35);

        pnMain.add(pnLeft);
        pnLeft.setBounds(20, 70, 300, 450);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH HẠNG THÀNH VIÊN");
        pnRight.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 300, 30);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnRight.add(txtTimKiem);
        txtTimKiem.setBounds(20, 60, 350, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnRight.add(btnTimKiem);
        btnTimKiem.setBounds(380, 60, 90, 35);

        tblHangTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hạng", "Tên Hạng", "% Giảm Giá", "Chi Tiêu Tối Thiểu (VNĐ)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHangTV.setRowHeight(30);
        tblHangTV.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblHangTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangTVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHangTV);

        pnRight.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 450, 320);

        pnMain.add(pnRight);
        pnRight.setBounds(340, 70, 490, 450);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {
        com.wms.model.HangThanhVienDTO dto = new com.wms.model.HangThanhVienDTO();
        dto.setMaHangThanhVien(txtMaHang.getText().trim());
        dto.setTenHangThanhVien(cbxTenHang.getSelectedItem().toString());
        dto.setPhanTramTienGiam(Double.valueOf(spnPhanTram.getValue().toString()));
        
        try {
            double chiTieu = Double.parseDouble(txtChiTieu.getText().trim());
            dto.setTongChiTieuToiThieu(chiTieu);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Chi tiêu tối thiểu không hợp lệ!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            controller.themHang(dto);
            javax.swing.JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
            loadDataToTable();
            btnLamMoiActionPerformed(null);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedHang == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hạng thành viên cần sửa!");
            return;
        }
        selectedHang.setTenHangThanhVien(cbxTenHang.getSelectedItem().toString());
        selectedHang.setPhanTramTienGiam(Double.valueOf(spnPhanTram.getValue().toString()));
        try {
            double chiTieu = Double.parseDouble(txtChiTieu.getText().trim());
            selectedHang.setTongChiTieuToiThieu(chiTieu);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Chi tiêu tối thiểu không hợp lệ!", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            controller.capNhatHang(selectedHang);
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadDataToTable();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedHang == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn hạng thành viên cần xóa!");
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa hạng này?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                controller.xoaHang(selectedHang.getMaHangThanhVien());
                javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadDataToTable();
                btnLamMoiActionPerformed(null);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {
        txtMaHang.setText("");
        cbxTenHang.setSelectedIndex(0);
        spnPhanTram.setValue(0.0);
        txtChiTieu.setText("");
        selectedHang = null;
        tblHangTV.clearSelection();
    }

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        hangList = controller.timKiemHang(txtTimKiem.getText().trim());
        fillTable();
    }

    private void tblHangTVMouseClicked(java.awt.event.MouseEvent evt) {
        int idx = tblHangTV.getSelectedRow();
        if (idx >= 0 && idx < hangList.size()) {
            selectedHang = hangList.get(idx);
            txtMaHang.setText(selectedHang.getMaHangThanhVien());
            cbxTenHang.setSelectedItem(selectedHang.getTenHangThanhVien());
            spnPhanTram.setValue(selectedHang.getPhanTramTienGiam() != null ? selectedHang.getPhanTramTienGiam() : 0.0);
            txtChiTieu.setText(selectedHang.getTongChiTieuToiThieu() != null ? String.format("%.0f", selectedHang.getTongChiTieuToiThieu()) : "0");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                QuanLyHangTVForm dialog = new QuanLyHangTVForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxTenHang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChiTieu;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMaHang;
    private javax.swing.JLabel lblPhanTram;
    private javax.swing.JLabel lblTenHang;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JSpinner spnPhanTram;
    private javax.swing.JTable tblHangTV;
    private javax.swing.JTextField txtChiTieu;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}


