CREATE TABLE CHUNGTUNHAPKHO (
    MaChungTu VARCHAR2(50) PRIMARY KEY,
    MaDV VARCHAR2(50) NOT NULL,
    TenFile VARCHAR2(255),
    NgayNhap DATE DEFAULT SYSDATE,
    NhanVienNhap VARCHAR2(100),
    SoLuongNhap NUMBER,
    CONSTRAINT FK_ChungTu_DichVu FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
);

CREATE SEQUENCE SEQ_LOAIDV_NEW START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DICHVU_NEW START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CHUNGTU START WITH 1 INCREMENT BY 1;


select * from  CHUNGTUNHAPKHO