CREATE TABLE CHUNGTUNHAPKHO (
    MaChungTu VARCHAR2(50) PRIMARY KEY,
    MaDV VARCHAR2(50) NOT NULL,
    MaNV VARCHAR2(50),
    MaCN VARCHAR2(50),
    TenFile VARCHAR2(255),
    NoiDungFile BLOB,
    NgayNhap DATE DEFAULT SYSDATE,
    SoLuongNhap NUMBER,
    CONSTRAINT FK_ChungTu_DichVu FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV),
    CONSTRAINT FK_ChungTu_NhanVien FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_ChungTu_ChiNhanh FOREIGN KEY (MaCN) REFERENCES CHINHANH(MaCN)
);

CREATE SEQUENCE SEQ_LOAIDV_NEW START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DICHVU_NEW START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CHUNGTU START WITH 1 INCREMENT BY 1;