CREATE TABLE DICHVU (
    MaDV VARCHAR2(50) PRIMARY KEY,
    TenDV VARCHAR2(100),
    HinhAnh BLOB,
    TrangThaiDV VARCHAR2(50),
    DonGia NUMBER(18, 2),
    MaLoaiDV VARCHAR2(50),
    SoLuong NUMBER,
    GiaGoc NUMBER
);

ALTER TABLE DICHVU RENAME COLUMN GiaGoc TO GiaNhap;
COMMIT;
