CREATE TABLE LOAIDICHVU (
    MaLoaiDV VARCHAR2(50) PRIMARY KEY,
    TenLoaiDV VARCHAR2(100),
    TrangThaiLDV VARCHAR2(50)
);

INSERT INTO LOAIDICHVU (MaLoaiDV, TenLoaiDV) VALUES ('LDV01', 'Tiện ích');
INSERT INTO LOAIDICHVU (MaLoaiDV, TenLoaiDV) VALUES ('LDV02', 'Thức uống');
INSERT INTO LOAIDICHVU (MaLoaiDV, TenLoaiDV) VALUES ('LDV03', 'Đồ ăn');
