/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyLoaiDichVu;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyLoaiDichVuForm extends javax.swing.JPanel {
    private com.wms.controller.TrangChuQuanLy.QuanLyLoaiDichVu.LoaiDichVuController controller;

    /**
     * Creates new form QuanLyLoaiDichVuForm
     */
    public QuanLyLoaiDichVuForm() {
        initComponents();
        controller = new com.wms.controller.TrangChuQuanLy.QuanLyLoaiDichVu.LoaiDichVuController(this);
        setupEvents();
    }

    private void setupEvents() {
        btnThem.addActionListener(e -> controller.handleAdd());
        btnCapNhat.addActionListener(e -> controller.handleUpdate());
        btnLamMoi.addActionListener(e -> controller.clearForm());
        btnTimKiem.addActionListener(e -> controller.search(txtTimKiem.getText()));
        txtTimKiem.addActionListener(e -> controller.search(txtTimKiem.getText()));
        
        tblLoaiDichVu.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                controller.displaySelected();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiDichVu = new javax.swing.JTable();
        pnRight = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaLoai = new javax.swing.JLabel();
        txtMaLoai = new javax.swing.JTextField();
        lblTenLoai = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        cbxTrangThai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1050, 640));
        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ LOẠI DỊCH VỤ");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 60);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 60);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH LOẠI DỊCH VỤ");
        pnLeft.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 250, 30);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(35, 30, 48));
        lblTimKiem.setText("Tìm kiếm loại DV:");
        pnLeft.add(lblTimKiem);
        lblTimKiem.setBounds(20, 55, 130, 35);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pnLeft.add(txtTimKiem);
        txtTimKiem.setBounds(150, 55, 320, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        pnLeft.add(btnTimKiem);
        btnTimKiem.setBounds(480, 55, 90, 35);

        tblLoaiDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Loại", "Tên loại", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiDichVu.setRowHeight(35);
        tblLoaiDichVu.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblLoaiDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiDichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiDichVu);

        pnLeft.add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 550, 410);

        pnMain.add(pnLeft);
        pnLeft.setBounds(440, 70, 590, 540);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("THÔNG TIN CHI TIẾT");
        pnRight.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 200, 30);

        lblMaLoai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaLoai.setForeground(new java.awt.Color(35, 30, 48));
        lblMaLoai.setText("Mã Loại Dịch vụ");
        pnRight.add(lblMaLoai);
        lblMaLoai.setBounds(20, 65, 360, 20);

        txtMaLoai.setEditable(false);
        txtMaLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaLoai.setBackground(new java.awt.Color(240, 240, 240));
        pnRight.add(txtMaLoai);
        txtMaLoai.setBounds(20, 85, 360, 35);

        lblTenLoai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenLoai.setForeground(new java.awt.Color(35, 30, 48));
        lblTenLoai.setText("Tên Loại Dịch vụ (*)");
        pnRight.add(lblTenLoai);
        lblTenLoai.setBounds(20, 135, 360, 20);

        txtTenLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnRight.add(txtTenLoai);
        txtTenLoai.setBounds(20, 155, 360, 35);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(35, 30, 48));
        lblTrangThai.setText("Trạng thái");
        pnRight.add(lblTrangThai);
        lblTrangThai.setBounds(20, 205, 360, 20);

        cbxTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Ngừng kinh doanh" }));
        pnRight.add(cbxTrangThai);
        cbxTrangThai.setBounds(20, 225, 360, 35);

        btnThem.setBackground(new java.awt.Color(235, 94, 141));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm mới");
        pnRight.add(btnThem);
        btnThem.setBounds(20, 290, 170, 35);

        btnCapNhat.setBackground(new java.awt.Color(235, 94, 141));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        pnRight.add(btnCapNhat);
        btnCapNhat.setBounds(210, 290, 170, 35);

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(235, 94, 141));
        btnLamMoi.setText("Làm mới form");
        pnRight.add(btnLamMoi);
        btnLamMoi.setBounds(20, 340, 360, 35);

        pnMain.add(pnRight);
        pnRight.setBounds(20, 70, 400, 540);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblLoaiDichVuMouseClicked(java.awt.event.MouseEvent evt) {
        controller.displaySelected();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMaLoai;
    private javax.swing.JLabel lblTenLoai;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTable tblLoaiDichVu;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtTenLoai;
    private javax.swing.JTextField txtTimKiem;
    // Getters for Controller access
    public javax.swing.JTable getTblLoaiDichVu() { return tblLoaiDichVu; }
    public javax.swing.JTextField getTxtMaLoai() { return txtMaLoai; }
    public javax.swing.JTextField getTxtTenLoai() { return txtTenLoai; }
    public javax.swing.JComboBox<String> getCbxTrangThai() { return cbxTrangThai; }
    public javax.swing.JTextField getTxtTimKiem() { return txtTimKiem; }

    // End of variables declaration//GEN-END:variables
}
