DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DATCHO' AND COLUMN_NAME = 'TONGTIENGOC';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DATCHO ADD (TongTienGoc NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DATCHO' AND COLUMN_NAME = 'MAPGG';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DATCHO ADD (MaPGG VARCHAR2(50))';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DATCHO' AND COLUMN_NAME = 'MACHUSOPGG';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DATCHO ADD (MaChuSoPGG VARCHAR2(100))';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DATCHO' AND COLUMN_NAME = 'TIENGIAMVOUCHER';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DATCHO ADD (TienGiamVoucher NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DATCHO' AND COLUMN_NAME = 'PHANTRAMGIAMHANGTV';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DATCHO ADD (PhanTramGiamHangTV NUMBER(5,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DATCHO' AND COLUMN_NAME = 'TIENGIAMHANGTV';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DATCHO ADD (TienGiamHangTV NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DATCHO' AND COLUMN_NAME = 'THANHTIENSAUGIAM';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DATCHO ADD (ThanhTienSauGiam NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'TONGTIENGOC';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (TongTienGoc NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'TIENGOCDATTRUOC';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (TienGocDatTruoc NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'TIENGOCPHATSINH';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (TienGocPhatSinh NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'MAPGGDATTRUOC';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (MaPGGDatTruoc VARCHAR2(50))';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'MAPGGTAIQUAY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (MaPGGTaiQuay VARCHAR2(50))';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'TIENGIAMVOUCHERDATTRUOC';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (TienGiamVoucherDatTruoc NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'TIENGIAMHANGTVDATTRUOC';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (TienGiamHangTVDatTruoc NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'PHANTRAMGIAMHANGTVDATTRUOC';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (PhanTramGiamHangTVDatTruoc NUMBER(5,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'TIENGIAMVOUCHERTAIQUAY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (TienGiamVoucherTaiQuay NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'TIENGIAMHANGTVTAIQUAY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (TienGiamHangTVTaiQuay NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'PHANTRAMGIAMHANGTVTAIQUAY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (PhanTramGiamHangTVTaiQuay NUMBER(5,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'TONGTIENGIAM';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (TongTienGiam NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HOADON' AND COLUMN_NAME = 'SOTIENTHANHTOANTAIQUAY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD (SoTienThanhToanTaiQuay NUMBER(18,2) DEFAULT 0 NOT NULL)';
    END IF;
END;
/

UPDATE DATCHO DC
SET ThanhTienSauGiam = CASE WHEN NVL(ThanhTienSauGiam, 0) = 0 THEN NVL(ThanhTien, 0) ELSE ThanhTienSauGiam END,
    TongTienGoc = CASE
        WHEN NVL(TongTienGoc, 0) = 0 THEN (
            SELECT NVL(LKG.DonGiaTheoGio, 0) * NVL(DC.KhoangThoiGianSuDung, 0)
            FROM KHONGGIAN KG
            JOIN LOAIKHONGGIAN LKG ON KG.MaLoaiKG = LKG.MaLoaiKG
            WHERE KG.MaKG = DC.MaKG
        )
        ELSE TongTienGoc
    END
WHERE NVL(ThanhTienSauGiam, 0) = 0
   OR NVL(TongTienGoc, 0) = 0;

UPDATE DATCHO
SET ThanhTien = ThanhTienSauGiam
WHERE NVL(ThanhTienSauGiam, 0) > 0
  AND NVL(ThanhTien, 0) <> NVL(ThanhTienSauGiam, 0);

UPDATE HOADON HD
SET TongTienGoc = CASE WHEN NVL(TongTienGoc, 0) = 0 THEN NVL(TongTien, 0) ELSE TongTienGoc END,
    SoTienThanhToanTaiQuay = CASE
        WHEN TrangThaiThanhToan = 'Đã thanh toán thành công' AND NVL(SoTienThanhToanTaiQuay, 0) = 0
        THEN NVL(ThanhTien, 0)
        ELSE SoTienThanhToanTaiQuay
    END
WHERE NVL(TongTienGoc, 0) = 0
   OR (TrangThaiThanhToan = 'Đã thanh toán thành công' AND NVL(SoTienThanhToanTaiQuay, 0) = 0);

COMMIT;
