DECLARE
    v_Count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_Count
    FROM USER_TAB_COLUMNS
    WHERE TABLE_NAME = 'HOADON'
      AND COLUMN_NAME = 'DATRATRUOC';

    IF v_Count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE HOADON ADD DaTraTruoc NUMBER(18, 2) DEFAULT 0 NOT NULL';
    END IF;
END;
/
