CREATE TABLE Roles (
    role_id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name     VARCHAR2(100) NOT NULL UNIQUE,
    description   VARCHAR2(255),
    is_system_role NUMBER(1) DEFAULT 0,            -- Nếu = 1 thì là role mặc định hệ thống, ko được xóa (tránh xóa quyền Admin,...)
    
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active     NUMBER(1) DEFAULT 1,
    is_deleted    NUMBER(1) DEFAULT 0 CHECK (is_deleted IN (0,1))
);