CREATE TABLE Users (
    user_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Thông tin đăng nhập
    username      VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    email         VARCHAR2(150) UNIQUE NOT NULL,
    status        VARCHAR2(20) DEFAULT 'ACTIVE',

    -- Thông tin cá nhân
    full_name     VARCHAR2(100) NOT NULL,
    phone_number  VARCHAR2(20),
    avatar_url    VARCHAR2(255),    -- Để thêm hình avt
    gender        VARCHAR2(10),     -- Nam/Nữ/Khác
    birthday      DATE,             -- Ngay sinh nhật thì có thể thêm khuyến mãi
    address       VARCHAR2(255),
    
    -- Theo dõi hệ thống
    last_login_at TIMESTAMP,                       -- Lần cuối đăng nhập
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted    NUMBER(1) DEFAULT 0 CHECK (is_deleted IN (0,1)) -- Chỉnh thành xóa hay chưa thoi, thay vì xóa khi nào so với trước đó
);