package com.wms.view.TrangChuHoiVien;

public class TrangChuHoiVienForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TrangChuHoiVienForm.class.getName());
    private javax.swing.JButton activeButton;

    public TrangChuHoiVienForm() {
        initComponents();
        setupCustomUI();
        
        com.wms.model.NguoiDungDTO user = com.wms.controller.DangNhapController.getCurrentUser();
        if (user != null) {
            lblGreeting.setText("Xin chào " + user.getHoTen() + "!");
        }

        showPanel(new com.wms.view.TrangChuHoiVien.TrangChu.TrangChuForm());
        setActiveMenu(btnMenuTrangChu);
    }

    private void setupCustomUI() {
        javax.swing.JButton[] menuButtons = {
            btnMenuTrangChu, btnMenuDatCho, btnMenuUuDai, btnMenuTaiKhoan
        };
        
        java.awt.Color defaultColor = new java.awt.Color(255, 255, 255);
        java.awt.Color hoverColor = new java.awt.Color(252, 235, 241); 
        
        for (javax.swing.JButton btn : menuButtons) {
            btn.setOpaque(true);
            btn.setBackground(defaultColor);
            btn.setFocusPainted(false);
            btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 0));
            
            btn.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    if (btn != activeButton) {
                        btn.setBackground(hoverColor); 
                    }
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    if (btn != activeButton) {
                        btn.setBackground(defaultColor); 
                    }
                }
            });
        }
        
        btnDangXuat.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 0));
    }

    private void setActiveMenu(javax.swing.JButton btn) {
        java.awt.Color defaultColor = new java.awt.Color(255, 255, 255);
        java.awt.Color activeColor = new java.awt.Color(252, 235, 241);
        java.awt.Color activeTextColor = new java.awt.Color(235, 94, 141);
        java.awt.Color defaultTextColor = new java.awt.Color(48, 30, 35);
        
        javax.swing.JButton[] menuButtons = {
            btnMenuTrangChu, btnMenuDatCho, btnMenuUuDai, btnMenuTaiKhoan
        };
        
        for (javax.swing.JButton b : menuButtons) {
            if (b == btn) {
                b.setBackground(activeColor);
                b.setForeground(activeTextColor);
                activeButton = b;
            } else {
                b.setBackground(defaultColor);
                b.setForeground(defaultTextColor);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnSidebar = new javax.swing.JPanel();
        pnLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblLogoSub = new javax.swing.JLabel();
        pnMenuContainer = new javax.swing.JPanel();
        btnMenuTrangChu = new javax.swing.JButton();
        btnMenuDatCho = new javax.swing.JButton();
        btnMenuUuDai = new javax.swing.JButton();
        btnMenuTaiKhoan = new javax.swing.JButton();
        pnLogout = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        pnRightMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblGreeting = new javax.swing.JLabel();
        pnUserInfo = new javax.swing.JPanel();
        lblMemberTier = new javax.swing.JLabel();
        pnContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Khu vực Hội viên - Spring System");
        setResizable(false);

        pnMain.setBackground(new java.awt.Color(240, 240, 240));
        pnMain.setPreferredSize(new java.awt.Dimension(1300, 700));
        pnMain.setLayout(new java.awt.BorderLayout());

        pnSidebar.setBackground(new java.awt.Color(255, 255, 255));
        pnSidebar.setPreferredSize(new java.awt.Dimension(260, 700));
        pnSidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(224, 224, 224)));
        pnSidebar.setLayout(new java.awt.BorderLayout());

        pnLogo.setBackground(new java.awt.Color(255, 255, 255));
        pnLogo.setPreferredSize(new java.awt.Dimension(260, 90));
        pnLogo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(224, 224, 224)));
        pnLogo.setLayout(null);

        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(235, 94, 141));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("SPRING MNGT");
        pnLogo.add(lblLogo);
        lblLogo.setBounds(0, 20, 260, 35);

        lblLogoSub.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLogoSub.setForeground(new java.awt.Color(136, 136, 136));
        lblLogoSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoSub.setText("M E M B E R   P O R T A L");
        pnLogo.add(lblLogoSub);
        lblLogoSub.setBounds(0, 55, 260, 20);

        pnSidebar.add(pnLogo, java.awt.BorderLayout.NORTH);

        pnMenuContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnMenuContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 20, 0));
        pnMenuContainer.setLayout(new javax.swing.BoxLayout(pnMenuContainer, javax.swing.BoxLayout.Y_AXIS));

        btnMenuTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMenuTrangChu.setForeground(new java.awt.Color(35, 30, 48));
        btnMenuTrangChu.setText("●  Trang chủ");
        btnMenuTrangChu.setBorderPainted(false);
        btnMenuTrangChu.setContentAreaFilled(false);
        btnMenuTrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuTrangChu.setMaximumSize(new java.awt.Dimension(32767, 50));
        btnMenuTrangChu.addActionListener(this::btnMenuTrangChuActionPerformed);
        pnMenuContainer.add(btnMenuTrangChu);

        btnMenuDatCho.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMenuDatCho.setForeground(new java.awt.Color(35, 30, 48));
        btnMenuDatCho.setText("●  Đặt chỗ không gian");
        btnMenuDatCho.setBorderPainted(false);
        btnMenuDatCho.setContentAreaFilled(false);
        btnMenuDatCho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuDatCho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuDatCho.setMaximumSize(new java.awt.Dimension(32767, 50));
        btnMenuDatCho.addActionListener(this::btnMenuDatChoActionPerformed);
        pnMenuContainer.add(btnMenuDatCho);

        btnMenuUuDai.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMenuUuDai.setForeground(new java.awt.Color(35, 30, 48));
        btnMenuUuDai.setText("●  Ưu đãi của tôi");
        btnMenuUuDai.setBorderPainted(false);
        btnMenuUuDai.setContentAreaFilled(false);
        btnMenuUuDai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuUuDai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuUuDai.setMaximumSize(new java.awt.Dimension(32767, 50));
        btnMenuUuDai.addActionListener(this::btnMenuUuDaiActionPerformed);
        pnMenuContainer.add(btnMenuUuDai);

        btnMenuTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMenuTaiKhoan.setForeground(new java.awt.Color(35, 30, 48));
        btnMenuTaiKhoan.setText("●  Thông tin tài khoản");
        btnMenuTaiKhoan.setBorderPainted(false);
        btnMenuTaiKhoan.setContentAreaFilled(false);
        btnMenuTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuTaiKhoan.setMaximumSize(new java.awt.Dimension(32767, 50));
        btnMenuTaiKhoan.addActionListener(this::btnMenuTaiKhoanActionPerformed);
        pnMenuContainer.add(btnMenuTaiKhoan);

        pnSidebar.add(pnMenuContainer, java.awt.BorderLayout.CENTER);

        pnLogout.setBackground(new java.awt.Color(255, 255, 255));
        pnLogout.setPreferredSize(new java.awt.Dimension(260, 80));
        pnLogout.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(224, 224, 224)));
        pnLogout.setLayout(new java.awt.BorderLayout());

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(150, 150, 150));
        btnDangXuat.setText("← Đăng xuất");
        btnDangXuat.setBorderPainted(false);
        btnDangXuat.setContentAreaFilled(false);
        btnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangXuat.addActionListener(this::btnDangXuatActionPerformed);
        pnLogout.add(btnDangXuat, java.awt.BorderLayout.CENTER);

        pnSidebar.add(pnLogout, java.awt.BorderLayout.SOUTH);

        pnMain.add(pnSidebar, java.awt.BorderLayout.WEST);

        pnRightMain.setLayout(new java.awt.BorderLayout());

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader.setPreferredSize(new java.awt.Dimension(1040, 60));
        pnHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(224, 224, 224)));
        pnHeader.setLayout(new java.awt.BorderLayout());

        lblGreeting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGreeting.setForeground(new java.awt.Color(35, 30, 48));
        lblGreeting.setText("Xin chào Hội viên!");
        lblGreeting.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        pnHeader.add(lblGreeting, java.awt.BorderLayout.WEST);

        pnUserInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnUserInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        pnUserInfo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 15));

        lblMemberTier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMemberTier.setForeground(new java.awt.Color(235, 94, 141));
        lblMemberTier.setText("Hạng: VIP Kim Cương");
        pnUserInfo.add(lblMemberTier);

        pnHeader.add(pnUserInfo, java.awt.BorderLayout.EAST);

        pnRightMain.add(pnHeader, java.awt.BorderLayout.NORTH);

        pnContent.setBackground(new java.awt.Color(254, 248, 250));
        pnContent.setLayout(new java.awt.BorderLayout());
        pnRightMain.add(pnContent, java.awt.BorderLayout.CENTER);

        pnMain.add(pnRightMain, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void showPanel(javax.swing.JPanel panel) {
        pnContent.removeAll();
        pnContent.add(panel, java.awt.BorderLayout.CENTER);
        pnContent.revalidate();
        pnContent.repaint();
    }

    private void btnMenuTrangChuActionPerformed(java.awt.event.ActionEvent evt) {
        showPanel(new com.wms.view.TrangChuHoiVien.TrangChu.TrangChuForm());
        setActiveMenu(btnMenuTrangChu);
    }

    private void btnMenuDatChoActionPerformed(java.awt.event.ActionEvent evt) {
        showPanel(new com.wms.view.TrangChuHoiVien.DatChoKhongGian.XemChiNhanh.XemChiNhanhForm());
        setActiveMenu(btnMenuDatCho);
    }

    private void btnMenuUuDaiActionPerformed(java.awt.event.ActionEvent evt) {
        showPanel(new com.wms.view.TrangChuHoiVien.UuDaiCuaToi.UuDaiCuaToiForm());
        setActiveMenu(btnMenuUuDai);
    }

    private void btnMenuTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {
        showPanel(new com.wms.view.TrangChuHoiVien.ThongTinHoiVien.ThongTinHoiVienForm());
        setActiveMenu(btnMenuTaiKhoan);
    }

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        try {
            new com.wms.view.TrangChuGioiThieu.TrangGioiThieuForm().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TrangChuHoiVienForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnMenuDatCho;
    private javax.swing.JButton btnMenuTaiKhoan;
    private javax.swing.JButton btnMenuTrangChu;
    private javax.swing.JButton btnMenuUuDai;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoSub;
    private javax.swing.JLabel lblMemberTier;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JPanel pnLogout;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenuContainer;
    private javax.swing.JPanel pnRightMain;
    private javax.swing.JPanel pnSidebar;
    private javax.swing.JPanel pnUserInfo;
    // End of variables declaration//GEN-END:variables
}
