/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.wms.view.TrangChuQuanLy.QuanLyPhien;

import com.wms.controller.QuanLyPhienController;

/**
 *
 * @author Thinkapd T14s
 */
public class QuanLyPhienForm extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhienForm
     */
    private com.wms.controller.QuanLyPhienController controller;
    private java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm dd/MM/yyyy");

    public QuanLyPhienForm() {
        initComponents();
        controller = new com.wms.controller.QuanLyPhienController(this);
        loadData("");
    }

    private void loadData(String keyword) {
        controller.loadDanhSachPhien(keyword);
    }

    public void hienThiDanhSachPhien(java.util.List<com.wms.model.PhienLamViecFullDTO> list) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPhienLamViec.getModel();
        model.setRowCount(0);
        for (com.wms.model.PhienLamViecFullDTO p : list) {
            model.addRow(new Object[]{
                p.getMaPhien(),
                p.getTenKhongGian(),
                p.getTenKhachHang(),
                p.getThoiGianBatDau() != null ? sdf.format(p.getThoiGianBatDau()) : "",
                p.getThoiGianKetThuc() != null ? sdf.format(p.getThoiGianKetThuc()) : "(Đang chạy)",
                p.getTrangThaiPhien()
            });
        }
    }

    public void hienThiDichVuTrongPhien(java.util.List<com.wms.model.DichVuTrongPhienDTO> list) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblDichVu.getModel();
        model.setRowCount(0);
        java.text.DecimalFormat df = new java.text.DecimalFormat("#,### VNĐ");
        for (com.wms.model.DichVuTrongPhienDTO dv : list) {
            model.addRow(new Object[]{
                dv.getTenDV(),
                dv.getSoLuong(),
                df.format(dv.getDonGia()),
                df.format(dv.getThanhTien())
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblHeaderTitle = new javax.swing.JLabel();
        pnLeft = new javax.swing.JPanel();
        lblListTitle = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnTaiLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhienLamViec = new javax.swing.JTable();
        pnRight = new javax.swing.JPanel();
        lblDetailTitle = new javax.swing.JLabel();
        lblMaPhien = new javax.swing.JLabel();
        txtMaPhien = new javax.swing.JTextField();
        lblKhongGian = new javax.swing.JLabel();
        txtKhongGian = new javax.swing.JTextField();
        lblKhachHang = new javax.swing.JLabel();
        txtKhachHang = new javax.swing.JTextField();
        lblTrangThai = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        lblBatDau = new javax.swing.JLabel();
        txtBatDau = new javax.swing.JTextField();
        lblDuKien = new javax.swing.JLabel();
        txtDuKien = new javax.swing.JTextField();
        lblKetThuc = new javax.swing.JLabel();
        txtKetThuc = new javax.swing.JTextField();
        lblDichVu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        btnMoPhien = new javax.swing.JButton();
        btnKetThucPhien = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnMain.setBackground(new java.awt.Color(254, 248, 250));
        pnMain.setPreferredSize(new java.awt.Dimension(1050, 640));
        pnMain.setLayout(null);

        pnHeader.setBackground(new java.awt.Color(235, 94, 141));
        pnHeader.setLayout(null);

        lblHeaderTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblHeaderTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderTitle.setText("QUẢN LÝ PHIÊN LÀM VIỆC");
        pnHeader.add(lblHeaderTitle);
        lblHeaderTitle.setBounds(0, 0, 1050, 50);

        pnMain.add(pnHeader);
        pnHeader.setBounds(0, 0, 1050, 50);

        pnLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnLeft.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnLeft.setLayout(null);

        lblListTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblListTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblListTitle.setText("DANH SÁCH PHIÊN");
        pnLeft.add(lblListTitle);
        lblListTitle.setBounds(20, 15, 200, 30);

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTimKiem.setToolTipText("Tìm mã phiên / khách hàng...");
        pnLeft.add(txtTimKiem);
        txtTimKiem.setBounds(20, 55, 340, 35);

        btnTimKiem.setBackground(new java.awt.Color(235, 94, 141));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(this::btnTimKiemActionPerformed);
        pnLeft.add(btnTimKiem);
        btnTimKiem.setBounds(375, 55, 80, 35);

        btnTaiLai.setBackground(new java.awt.Color(235, 94, 141));
        btnTaiLai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTaiLai.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiLai.setText("Tải lại");
        btnTaiLai.addActionListener(this::btnTaiLaiActionPerformed);
        pnLeft.add(btnTaiLai);
        btnTaiLai.setBounds(465, 55, 95, 35);

        tblPhienLamViec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phiên", "Không Gian", "Khách Hàng", "Bắt đầu", "Kết thúc", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhienLamViec.setRowHeight(30);
        tblPhienLamViec.setSelectionBackground(new java.awt.Color(235, 94, 141));
        tblPhienLamViec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhienLamViecMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhienLamViec);

        pnLeft.add(jScrollPane1);
        jScrollPane1.setBounds(20, 105, 540, 425);

        pnMain.add(pnLeft);
        pnLeft.setBounds(20, 70, 580, 550);

        pnRight.setBackground(new java.awt.Color(255, 255, 255));
        pnRight.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 0, 0, 0, new java.awt.Color(235, 94, 141)));
        pnRight.setLayout(null);

        lblDetailTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDetailTitle.setForeground(new java.awt.Color(48, 30, 35));
        lblDetailTitle.setText("CHI TIẾT PHIÊN LÀM VIỆC");
        pnRight.add(lblDetailTitle);
        lblDetailTitle.setBounds(20, 15, 250, 30);

        lblMaPhien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaPhien.setForeground(new java.awt.Color(136, 136, 136));
        lblMaPhien.setText("Mã phiên");
        pnRight.add(lblMaPhien);
        lblMaPhien.setBounds(20, 55, 100, 18);

        txtMaPhien.setEditable(false);
        txtMaPhien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaPhien.setBorder(null);
        pnRight.add(txtMaPhien);
        txtMaPhien.setBounds(20, 75, 180, 30);

        lblKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblKhongGian.setForeground(new java.awt.Color(136, 136, 136));
        lblKhongGian.setText("Không gian");
        pnRight.add(lblKhongGian);
        lblKhongGian.setBounds(210, 55, 100, 18);

        txtKhongGian.setEditable(false);
        txtKhongGian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtKhongGian.setBorder(null);
        pnRight.add(txtKhongGian);
        txtKhongGian.setBounds(210, 75, 180, 30);

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblKhachHang.setForeground(new java.awt.Color(136, 136, 136));
        lblKhachHang.setText("Khách hàng");
        pnRight.add(lblKhachHang);
        lblKhachHang.setBounds(20, 110, 100, 18);

        txtKhachHang.setEditable(false);
        txtKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtKhachHang.setBorder(null);
        pnRight.add(txtKhachHang);
        txtKhachHang.setBounds(20, 130, 180, 30);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(136, 136, 136));
        lblTrangThai.setText("Trạng thái");
        pnRight.add(lblTrangThai);
        lblTrangThai.setBounds(210, 110, 100, 18);

        txtTrangThai.setEditable(false);
        txtTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTrangThai.setForeground(new java.awt.Color(255, 51, 51));
        txtTrangThai.setBorder(null);
        pnRight.add(txtTrangThai);
        txtTrangThai.setBounds(210, 130, 180, 30);

        lblBatDau.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblBatDau.setForeground(new java.awt.Color(136, 136, 136));
        lblBatDau.setText("Giờ bắt đầu");
        pnRight.add(lblBatDau);
        lblBatDau.setBounds(20, 165, 150, 18);

        txtBatDau.setEditable(false);
        txtBatDau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBatDau.setBorder(null);
        pnRight.add(txtBatDau);
        txtBatDau.setBounds(20, 185, 180, 30);

        lblDuKien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDuKien.setForeground(new java.awt.Color(136, 136, 136));
        lblDuKien.setText("Dự kiến kết thúc");
        pnRight.add(lblDuKien);
        lblDuKien.setBounds(210, 165, 150, 18);

        txtDuKien.setEditable(false);
        txtDuKien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDuKien.setBorder(null);
        pnRight.add(txtDuKien);
        txtDuKien.setBounds(210, 185, 180, 30);

        lblKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblKetThuc.setForeground(new java.awt.Color(136, 136, 136));
        lblKetThuc.setText("Thời gian kết thúc thực tế");
        pnRight.add(lblKetThuc);
        lblKetThuc.setBounds(20, 220, 370, 18);

        txtKetThuc.setEditable(false);
        txtKetThuc.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtKetThuc.setForeground(new java.awt.Color(136, 136, 136));
        txtKetThuc.setText("(Chưa kết thúc)");
        txtKetThuc.setBorder(null);
        pnRight.add(txtKetThuc);
        txtKetThuc.setBounds(20, 240, 370, 30);

        lblDichVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDichVu.setForeground(new java.awt.Color(0, 0, 58));
        lblDichVu.setText("Các dịch vụ đã sử dụng trong phiên:");
        pnRight.add(lblDichVu);
        lblDichVu.setBounds(20, 285, 370, 20);

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Dịch Vụ", "SL", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichVu.setRowHeight(25);
        tblDichVu.setSelectionBackground(new java.awt.Color(235, 94, 141));
        jScrollPane2.setViewportView(tblDichVu);

        pnRight.add(jScrollPane2);
        jScrollPane2.setBounds(20, 310, 370, 170);

        btnMoPhien.setBackground(new java.awt.Color(0, 153, 51));
        btnMoPhien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnMoPhien.setForeground(new java.awt.Color(255, 255, 255));
        btnMoPhien.setText("Mở Phiên Mới");
        btnMoPhien.addActionListener(this::btnMoPhienActionPerformed);
        pnRight.add(btnMoPhien);
        btnMoPhien.setBounds(20, 495, 125, 35);

        btnKetThucPhien.setBackground(new java.awt.Color(21, 101, 192));
        btnKetThucPhien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnKetThucPhien.setForeground(new java.awt.Color(255, 255, 255));
        btnKetThucPhien.setText("Kết Thúc Phiên");
        btnKetThucPhien.addActionListener(this::btnKetThucPhienActionPerformed);
        pnRight.add(btnKetThucPhien);
        btnKetThucPhien.setBounds(155, 495, 130, 35);

        btnHuy.setBackground(new java.awt.Color(220, 53, 69));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Làm mới");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        pnRight.add(btnHuy);
        btnHuy.setBounds(295, 495, 95, 35);

        pnMain.add(pnRight);
        pnRight.setBounds(620, 70, 410, 550);

        add(pnMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {
        loadData(txtTimKiem.getText().trim());
    }

    private void btnTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {
        txtTimKiem.setText("");
        loadData("");
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        txtMaPhien.setText("");
        txtKhongGian.setText("");
        txtKhachHang.setText("");
        txtTrangThai.setText("");
        txtBatDau.setText("");
        txtDuKien.setText("");
        txtKetThuc.setText("(Chưa kết thúc)");
        ((javax.swing.table.DefaultTableModel) tblDichVu.getModel()).setRowCount(0);
        tblPhienLamViec.clearSelection();
    }

    private void btnKetThucPhienActionPerformed(java.awt.event.ActionEvent evt) {
        String maPhien = txtMaPhien.getText().trim();
        if (maPhien.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một phiên đang chạy!");
            return;
        }
        
        if ("Hoàn thành".equals(txtTrangThai.getText())) {
            javax.swing.JOptionPane.showMessageDialog(this, "Phiên này đã kết thúc rồi!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Xác nhận kết thúc phiên " + maPhien + "?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            if (controller.ketThucPhien(maPhien)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Đã kết thúc phiên thành công!");
                loadData("");
                btnHuyActionPerformed(null);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi kết thúc phiên!");
            }
        }
    }

    private void btnMoPhienActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng sử dụng chức năng Đặt Chỗ để mở phiên mới!");
    }

    private void tblPhienLamViecMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblPhienLamViec.getSelectedRow();
        if (row >= 0) {
            String maPhien = tblPhienLamViec.getValueAt(row, 0).toString();
            txtMaPhien.setText(maPhien);
            txtKhongGian.setText(tblPhienLamViec.getValueAt(row, 1).toString());
            txtKhachHang.setText(tblPhienLamViec.getValueAt(row, 2).toString());
            txtBatDau.setText(tblPhienLamViec.getValueAt(row, 3).toString());
            txtKetThuc.setText(tblPhienLamViec.getValueAt(row, 4).toString());
            txtTrangThai.setText(tblPhienLamViec.getValueAt(row, 5).toString());
            
            // Tìm thời gian dự kiến từ danh sách gốc (vì trên bảng có thể không hiện đủ hoặc format khác)
            // Ở đây tạm lấy từ bảng nếu có, hoặc fetch lại. Để đơn giản, ta chỉ hiển thị những gì có.
            
            controller.loadChiTietDichVu(maPhien);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnKetThucPhien;
    private javax.swing.JButton btnMoPhien;
    private javax.swing.JButton btnTaiLai;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBatDau;
    private javax.swing.JLabel lblDetailTitle;
    private javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblDuKien;
    private javax.swing.JLabel lblHeaderTitle;
    private javax.swing.JLabel lblKetThuc;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKhongGian;
    private javax.swing.JLabel lblListTitle;
    private javax.swing.JLabel lblMaPhien;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnRight;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblPhienLamViec;
    private javax.swing.JTextField txtBatDau;
    private javax.swing.JTextField txtDuKien;
    private javax.swing.JTextField txtKetThuc;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextField txtKhongGian;
    private javax.swing.JTextField txtMaPhien;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}


